### ISSUE TITLE
Koin Test: Could not inject an object when trying to instantiate with a named argument

### ISSUE THREAD

**Issue by Armen101** [InsertKoinIO/koin#1000]
**Koin module**

```
private const val USER_PREFS = "UserPrefs"

val sharedPrefsModule = module {

    single(named(USER_PREFS)) {
        androidApplication().getSharedPreferences(USER_PREFS, Context.MODE_PRIVATE)
    }

    factory<IBioAuthStorage> { BioAuthStorage(get(named(USER_PREFS))) }

}
```

**Test class**
```
import org.koin.core.component.inject
import org.koin.test.AutoCloseKoinTest

class BioAuthStorageTest : AutoCloseKoinTest() {

    private val bioAuthStorage by inject<IBioAuthStorage>()

    @Test
    fun storePin() { 
         ...
         //Act
         bioAuthStorage.storePin(PIN_CODE)
         ....
    }
 }
```

**Gradle**
```
    def koin_version = "2.2.0"
    implementation "org.koin:koin-androidx-viewmodel:$koin_version"
    implementation "org.koin:koin-androidx-ext:$koin_version"
    testImplementation "org.koin:koin-test:$koin_version"
```

**Stacktrace**
```
org.koin.core.error.InstanceCreationException: Could not create instance for [Factory:'path.IBioAuthStorage']
	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:62)
	at org.koin.core.instance.FactoryInstanceFactory.get(FactoryInstanceFactory.kt:36)
	at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:103)
	at org.koin.core.scope.Scope.resolveInstance(Scope.kt:236)
	at org.koin.core.scope.Scope.get(Scope.kt:204)
	at path.BioAuthStorageTest$$special$$inlined$inject$1.invoke(KoinComponent.kt:79)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at path.BioAuthStorageTest.getBioAuthStorage(BioAuthStorageTest.kt)
	at path.BioAuthStorageTest.restorePin(BioAuthStorageTest.kt:34)
```

**Comment by Armen101** [comment]
**It fixed by**
```

  @Before
    open fun setUp() {
        startKoin {
            printLogger(Level.NONE)
            modules(modules)
        }
        
        val preferences = stubSharedPref()
        val application = stubApplication(preferences)

        loadKoinModules(
            listOf(
                module { single(override = true) { preferences } },
                module { single(override = true) { application } })
        )
    }

   open fun stubApplication(preferences: SharedPreferences) = declareMock<Application> {
        whenever(getSharedPreferences(anyString(), anyInt())).thenReturn(preferences)
   }
    
```
