### ISSUE TITLE
Injecting by getViewModel issue

### ISSUE THREAD

**Issue by MartinBirn** [InsertKoinIO/koin#1020]
`Koin version 2.2.2`

**Exception:**

     java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.example.library/com.example.library.MainActivity}: java.lang.IllegalStateException: Your activity is not yet attached to the Application instance. You can't request ViewModel before onCreate call.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3194)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:915)
     Caused by: java.lang.IllegalStateException: Your activity is not yet attached to the Application instance. You can't request ViewModel before onCreate call.
        at androidx.activity.ComponentActivity.getViewModelStore(ComponentActivity.java:472)
        at org.koin.androidx.viewmodel.ViewModelOwner$Companion.from(ViewModelOwner.kt:19)
        at org.koin.androidx.viewmodel.ViewModelOwner$Companion.from$default(ViewModelOwner.kt:18)
        at org.koin.androidx.viewmodel.compat.ViewModelCompat$getViewModel$1.invoke(ViewModelCompat.kt:66)
        at org.koin.androidx.viewmodel.compat.ViewModelCompat$getViewModel$1.invoke(ViewModelCompat.kt:31)
        at org.koin.androidx.viewmodel.scope.ScopeExtKt.getViewModel(ScopeExt.kt:71)
        at org.koin.androidx.viewmodel.koin.KoinExtKt.getViewModel(KoinExt.kt:41)
        at org.koin.androidx.viewmodel.compat.ViewModelCompat.getViewModel(ViewModelCompat.kt:66)
        at org.koin.androidx.viewmodel.compat.ViewModelCompat.getViewModel$default(ViewModelCompat.kt:65)
        at com.example.library.MainActivity.<init>(MainActivity.kt:10)
        at java.lang.Class.newInstance(Native Method)
        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
        at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:45)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1250)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3182)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:915)

**MainActivity code:**
```kotlin
import android.os.Bundle
import androidx.appcompat.app.AppCompatActivity
import com.example.library.login.LoginViewModel
import org.koin.androidx.viewmodel.compat.ViewModelCompat.getViewModel

class MainActivity : AppCompatActivity(){

    private val loginViewModel = getViewModel(this, LoginViewModel::class.java)

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_login)
    }
}
```    

**module object:**
```kotlin
val loginModule = module {
    viewModel { LoginViewModel(get()) }
}
```

**Comment by arnaudgiuliani** [comment]
just replace `private val loginViewModel = getViewModel(this, LoginViewModel::class.java)` with `private val loginViewModel by viewModel()`

**Comment by arnaudgiuliani** [comment]
I think you've used the app compat helper

**Comment by MartinBirn** [comment]
@arnaudgiuliani Yes, I understand that there is a lazy initialization. But in my case I need to directly get a ViewModel instance, just like in the example from the [documentation](https://insert-koin.io/docs/reference/koin-android/viewmodel/), to execute the init block. If it's possible of course

**Comment by arnaudgiuliani** [comment]
THere is a mistake here. You can get your ViewModel in your property, the Activity won't be ready. To get it directly, get it from `onCreate`

**Comment by MartinBirn** [comment]
Okay, thank you
