### ISSUE TITLE
org.koin.core.error.NoBeanDefFoundException after upgrading from 2.0.1 to 3.0.1

### ISSUE THREAD

**Issue by Pjnous** [InsertKoinIO/koin#1078]
**Describe the bug**
Hello,
we have upgraded Koin from 2.0.1 to 3.0.1 in our application and now we got the exception org.koin.core.error.NoBeanDefFoundException (full exception is attached at the end of the bug report). I have created sample app to reproduce the problem and attached it as ZIP here.
[SampleApp.zip](https://github.com/InsertKoinIO/koin/files/6403349/SampleApp.zip)

The module is

```
val appModule = module {
     factory { MainPresenter(get(), get()) }

    scope(named(ACTIVITY_SCOPE))
    {
        scoped { ObservableLifecycleManager(get()) }
    }
}
```

the purpose of the named ACTIVITY_SCOPE is that we want to inject ObservableLifecycleManager (it takes care of the rxJava subscriptions based on the activity lifecycle) to each presenter of the activity (so we created named scope that is common for all activities via BaseActivity). 

The ACTIVITY_SCOPE is simple string

```
  companion object
  {
        public const val ACTIVITY_SCOPE = "ACTIVITY"
  }

```
We have inject the presenter like this

```
class MainActivity : BaseActivity() {

    private val mPresenter : MainPresenter by  getScope().inject()

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        
        mPresenter.test()
    }

}
```

and in the BaseActivity

```
abstract class BaseActivity : AppCompatActivity() {

    private val scope: Scope = getCurrentScope(ACTIVITY_SCOPE)
    protected fun getScope() = scope

    override fun onCreate(savedInstanceState: Bundle?) {

        declareActivityDependencies()
        super.onCreate(savedInstanceState)
    }

    private fun declareActivityDependencies() {
        this.scope.declare(this as LifecycleOwner)
    }

}
```

we create the scope and declare the LifecycleOwner from the current activity.

The creation of the named scoped for each activity is handled like this

```
private fun Activity.getScopeId() = this::class.getFullName() + "@" + System.identityHashCode(this)

private fun Activity.getOrCreateCurrentScope(name:String): Scope {
    return KoinJavaComponent.getKoin().getScopeOrNull(getScopeId()) ?: createAndBindScope(getScopeId(), named(name))
}

private fun Activity.createAndBindScope(scopeId: String, qualifier: Qualifier): Scope {
    val scope = KoinJavaComponent.getKoin().createScope(scopeId, qualifier)
    bindScope(scope)
    return scope
}

fun Activity.bindScope(scope: Scope, event: Lifecycle.Event = Lifecycle.Event.ON_DESTROY) {
    (this as LifecycleOwner).lifecycle.addObserver(ScopeObserver(event, this, scope))
}

fun Activity.getCurrentScope(name:String) : Scope = getOrCreateCurrentScope(name)
```

The class ScopeObserver is taken from the Koin 2.0.1

I have digged down the code of the exception and I thnik the main problem in 3.0.1 is that when is starts looking for the dependencies it goes to Root scope for MainPresenter (hilighted in image below), and then it start looking for ObservableLifecycleManager but it cannot find it because it does not exist in root scope but it lives in the named scope.

![image](https://user-images.githubusercontent.com/42221914/116657489-c3c74a00-a98e-11eb-85a9-9f0017dcf856.png)

I have tried to link root scope and named scope but the result was the same.

**To Reproduce**
1. Run the attached application and the exception is thrown -  Caused by: org.koin.core.error.NoBeanDefFoundException: No definition found for class:'koin.scope.test.ObservableLifecycleManager'. Check your definitions!
2. If you comment in project build.gradle line 41 - 
`implementation 'io.insert-koin:koin-android:3.0.1'`
and comment out lines 43-45 in project build.gradle
```
    implementation 'org.koin:koin-android-scope:2.0.1'
    implementation 'org.koin:koin-android:2.0.1'
    implementation 'org.koin:koin-java:2.0.1'
```
3. Change the namespace of KoinComponent in ScopeObserver ln 6 from `org.koin.core.component.KoinComponent` to `org.koin.core.KoinComponent`
4. Run the application and everything works ok

**Expected behavior**
We expect that in 3.0.1 the dependencies should be injected.

**Koin project used and used version (please complete the following information):**
We are using the` io.insert-koin:koin-android:3.0.1` which causes the exception

Version

```
    implementation 'org.koin:koin-android-scope:2.0.1'
    implementation 'org.koin:koin-android:2.0.1'
    implementation 'org.koin:koin-java:2.0.1'
```

Works OK.

**Additional moduleDefinition**
--
```
2021-04-30 08:38:39.637 10868-10868/koin.scope.test E/[Koin]: Instance creation error : could not create instance for [Factory:'koin.scope.test.MainPresenter']: org.koin.core.error.NoBeanDefFoundException: No definition found for class:'koin.scope.test.ObservableLifecycleManager'. Check your definitions!
    	org.koin.core.scope.Scope.throwDefinitionNotFound(Scope.kt:264)
    	org.koin.core.scope.Scope.resolveInstance(Scope.kt:233)
    	org.koin.core.scope.Scope.get(Scope.kt:204)
    	koin.scope.test.KoinModuleKt$appModule$1$1.invoke(KoinModule.kt:21)
    	koin.scope.test.KoinModuleKt$appModule$1$1.invoke(Unknown Source:4)
    	org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:54)
    	org.koin.core.instance.FactoryInstanceFactory.get(FactoryInstanceFactory.kt:36)
    	org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:103)
    	org.koin.core.scope.Scope.resolveInstance(Scope.kt:218)
    	org.koin.core.scope.Scope.get(Scope.kt:204)
    	org.koin.core.scope.Scope.getOrNull(Scope.kt:172)
    	org.koin.core.scope.Scope.findInOtherScope(Scope.kt:249)
    	org.koin.core.scope.Scope.resolveInstance(Scope.kt:229)
    	org.koin.core.scope.Scope.get(Scope.kt:204)
    	koin.scope.test.MainActivity$$special$$inlined$inject$1.invoke(Scope.kt:421)
    	kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
    	koin.scope.test.MainActivity.getMPresenter(Unknown Source:2)
    	koin.scope.test.MainActivity.onCreate(MainActivity.kt:18)
    	android.app.Activity.performCreate(Activity.java:8000)
    	android.app.Activity.performCreate(Activity.java:7984)
    	android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
    	android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
    	android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
    	android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
    	android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
    	android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
    	android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
    	android.os.Handler.dispatchMessage(Handler.java:106)
    	android.os.Looper.loop(Looper.java:223)
    	android.app.ActivityThread.main(ActivityThread.java:7656)
    	java.lang.reflect.Method.invoke(Native Method)
    	com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
    	com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
2021-04-30 08:38:39.696 10868-10868/koin.scope.test E/AndroidRuntime: FATAL EXCEPTION: main
    Process: koin.scope.test, PID: 10868
    java.lang.RuntimeException: Unable to start activity ComponentInfo{koin.scope.test/koin.scope.test.MainActivity}: org.koin.core.error.InstanceCreationException: Could not create instance for [Factory:'koin.scope.test.MainPresenter']
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3449)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: org.koin.core.error.InstanceCreationException: Could not create instance for [Factory:'koin.scope.test.MainPresenter']
        at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:61)
        at org.koin.core.instance.FactoryInstanceFactory.get(FactoryInstanceFactory.kt:36)
        at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:103)
        at org.koin.core.scope.Scope.resolveInstance(Scope.kt:218)
        at org.koin.core.scope.Scope.get(Scope.kt:204)
        at org.koin.core.scope.Scope.getOrNull(Scope.kt:172)
        at org.koin.core.scope.Scope.findInOtherScope(Scope.kt:249)
        at org.koin.core.scope.Scope.resolveInstance(Scope.kt:229)
        at org.koin.core.scope.Scope.get(Scope.kt:204)
        at koin.scope.test.MainActivity$$special$$inlined$inject$1.invoke(Scope.kt:421)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at koin.scope.test.MainActivity.getMPresenter(Unknown Source:2)
        at koin.scope.test.MainActivity.onCreate(MainActivity.kt:18)
        at android.app.Activity.performCreate(Activity.java:8000)
        at android.app.Activity.performCreate(Activity.java:7984)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
     Caused by: org.koin.core.error.NoBeanDefFoundException: No definition found for class:'koin.scope.test.ObservableLifecycleManager'. Check your definitions!
        at org.koin.core.scope.Scope.throwDefinitionNotFound(Scope.kt:264)
        at org.koin.core.scope.Scope.resolveInstance(Scope.kt:233)
        at org.koin.core.scope.Scope.get(Scope.kt:204)
        at koin.scope.test.KoinModuleKt$appModule$1$1.invoke(KoinModule.kt:21)
        at koin.scope.test.KoinModuleKt$appModule$1$1.invoke(Unknown Source:4)
        at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:54)
        at org.koin.core.instance.FactoryInstanceFactory.get(FactoryInstanceFactory.kt:36) 
        at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:103) 
        at org.koin.core.scope.Scope.resolveInstance(Scope.kt:218) 
        at org.koin.core.scope.Scope.get(Scope.kt:204) 
        at org.koin.core.scope.Scope.getOrNull(Scope.kt:172) 
        at org.koin.core.scope.Scope.findInOtherScope(Scope.kt:249) 
        at org.koin.core.scope.Scope.resolveInstance(Scope.kt:229) 
        at org.koin.core.scope.Scope.get(Scope.kt:204) 
        at koin.scope.test.MainActivity$$special$$inlined$inject$1.invoke(Scope.kt:421) 
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74) 
        at koin.scope.test.MainActivity.getMPresenter(Unknown Source:2) 
        at koin.scope.test.MainActivity.onCreate(MainActivity.kt:18) 
        at android.app.Activity.performCreate(Activity.java:8000) 
        at android.app.Activity.performCreate(Activity.java:7984) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
```

Thank you, with best regards Pavel Tupec

**Comment by Pjnous** [comment]
Is there any update of this ?

**Comment by Pjnous** [comment]
I have tried it with 3.1.4 and the problem persists.
