### ISSUE TITLE
java.lang.ClassCastException: org.koin.core.context.GlobalContext cannot be cast to org.koin.core.context.KoinContext

### ISSUE THREAD

**Issue by jonatan88291** [InsertKoinIO/koin#1090]
**Describe the bug**
I trying to migrate from Koin 2.1.6 to 2.2.2 or 3.0.1 but on both versions during run tests I have many issues related to GlobalContext. Each test related to ViewModel finishing with error.

Error after migration to 3.0.1
```
com.example.myapp.screens.screens.MenuViewModelTest > menuDataShouldDisplayMinimum3Items FAILED
    java.lang.ClassCastException: org.koin.core.context.GlobalContext cannot be cast to org.koin.core.context.KoinContext
        at org.koin.mp.KoinPlatformTools.defaultContext(PlatformToolsJVM.kt:19)
        at org.koin.core.context.DefaultContextExtKt.startKoin(DefaultContextExt.kt:31)
        at com.example.myapp.BaseTest.setUp(BaseTest.kt:33)
        at com.example.myapp.BaseViewModelTest.setUp(BaseViewModelTest.kt:24)
        at com.example.myapp.screens.screens.MenuViewModelTest.setUp(MenuViewModelTest.kt:28)

    java.lang.IllegalStateException: KoinApplication has not been started
        at org.koin.core.context.GlobalContext.get(GlobalContext.kt:37)
        at org.koin.core.KoinComponent$DefaultImpls.getKoin(KoinComponent.kt:32)
        at org.koin.test.KoinTest$DefaultImpls.getKoin(KoinTest.kt)
        at com.example.myapp.BaseTest.getKoin(BaseTest.kt:22)
        at com.example.myapp.BaseTest.tearDown(BaseTest.kt:119)
        at com.example.myapp.screens.screens.MenuViewModelTest.tearDown(MenuViewModelTest.kt:36)

```

In 2.2.2:

```
com.example.myapp.screens.screens.MenuViewModelTest > menuDataShouldDisplayMinimum3Items FAILED
    java.lang.ClassCastException: org.koin.core.context.GlobalContext cannot be cast to org.koin.core.context.KoinContext
        at org.koin.core.context.GlobalContextExtKt.startKoin$default(GlobalContextExt.kt:31)
        at com.example.myapp.BaseTest.setUp(BaseTest.kt:33)
        at com.example.myapp.BaseViewModelTest.setUp(BaseViewModelTest.kt:24)
        at com.example.myapp.screens.screens.MenuViewModelTest.setUp(MenuViewModelTest.kt:28)

    java.lang.IllegalStateException: KoinApplication has not been started
        at org.koin.core.context.GlobalContext.get(GlobalContext.kt:37)
        at org.koin.core.KoinComponent$DefaultImpls.getKoin(KoinComponent.kt:32)
        at org.koin.test.KoinTest$DefaultImpls.getKoin(KoinTest.kt)
        at org.koin.test.AutoCloseKoinTest.getKoin(AutoCloseKoinTest.kt:26)
        at com.example.myapp.BaseTest.tearDown(BaseTest.kt:119)
        at com.example.myapp.screens.screens.MenuViewModelTest.tearDown(MenuViewModelTest.kt:36)

    java.lang.IncompatibleClassChangeError: Expecting non-static method org.koin.core.context.GlobalContext.stop()V
        at org.koin.core.context.GlobalContextExtKt.stopKoin(GlobalContextExt.kt:37)
        at org.koin.test.AutoCloseKoinTest.autoClose(AutoCloseKoinTest.kt:30)
        at sun.reflect.GeneratedMethodAccessor38.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
        at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
        at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
        at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
        at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
        at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
        at sun.reflect.GeneratedMethodAccessor42.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
        at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:119)
        at sun.reflect.GeneratedMethodAccessor41.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
        at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
        at java.lang.Thread.run(Thread.java:748)
```

**Expected behavior**
Unit test should be passed

**Koin project used and used version (please complete the following information):**
> implementation "io.insert-koin:koin-android:3.0.1"
> testImplementation "io.insert-koin:koin-test:3.0.1"

Please note that on 2.1.6 tests using KoinTest or AutoCloseKoinTest without any changes works perfectly.

**Comment by jonatan88291** [comment]
Tests run by Android Studio passed
Tests run by _gradlew clean test_ have errors mentioned above
Used the same JDK:
`.\gradlew -D org.gradle.java.home="C:\\Program Files\\Android\\Android Studio\\jre" clean test`

**Comment by arnaudgiuliani** [comment]
cache problem? `GlobalContext` is the new Koin context holder. Do you use `KoinContext` directly?

**Comment by jonatan88291** [comment]
Hmm, I found rootcause for this problem. I using in project both: mavenCentral and JCenter because some dependencies still are not republished on MavenCentral. So when I removed one of repository (it doesn't matter which one) then issue has gone.

**Comment by arnaudgiuliani** [comment]
could it be a mix of versions? like in 3.0.x you don't `koin-androidx-viewmodel` as it has been merged in `koin-android`
