### ISSUE TITLE
Crash on Instrumented test

### ISSUE THREAD

**Issue by Drsdavi62** [InsertKoinIO/koin#1096]
My application works fine and so do my Instrumented Tests, but as soon as I add koin-test to the dependencies all Instrumented Tests start crashing, even the ones that don't use koin.

1. Add koin-test dependency
2. Run any Instrumented test

**Expected behavior**

Here's the stacktrace I get:
2021-05-18 15:19:29.029 9741-9741/com.davi.mesanews E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.davi.mesanews, PID: 9741
    java.lang.RuntimeException: Unable to create application com.davi.mesanews.MesaNewsApplication: java.lang.ClassCastException: org.koin.core.context.GlobalContext cannot be cast to org.koin.core.context.KoinContext
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6123)
        at android.app.ActivityThread.access$1200(ActivityThread.java:213)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1807)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6923)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)
     Caused by: java.lang.ClassCastException: org.koin.core.context.GlobalContext cannot be cast to org.koin.core.context.KoinContext
        at org.koin.mp.KoinPlatformTools.defaultContext(PlatformToolsJVM.kt:19)
        at org.koin.core.context.DefaultContextExtKt.startKoin(DefaultContextExt.kt:31)
        at com.davi.mesanews.MesaNewsApplication.onCreate(MesaNewsApplication.kt:14)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1176)
        at androidx.test.runner.MonitoringInstrumentation.callApplicationOnCreate(MonitoringInstrumentation.java:428)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6118)
        at android.app.ActivityThread.access$1200(ActivityThread.java:213) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1807) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6923) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870) 
2021-05-18 15:19:29.029 9741-9741/com.davi.mesanews E/AndroidJUnitRunner: An unhandled exception was thrown by the app.
2021-05-18 15:19:29.032 9741-9741/com.davi.mesanews E/InstrumentationResultPrinter: Failed to mark test No Tests as finished after process crash

This is how I start koin in my Application
![image](https://user-images.githubusercontent.com/59269556/118703554-9d0d6e00-b7ec-11eb-9d1a-e41e043bb80a.png)

And these are my dependencies on gradle
![image](https://user-images.githubusercontent.com/59269556/118703609-adbde400-b7ec-11eb-8e02-721e6f145eed.png)

**Comment by arnaudgiuliani** [comment]
> java.lang.ClassCastException: org.koin.core.context.GlobalContext cannot be cast to org.koin.core.context.KoinContext

Perhaps a cache problem as it's still using old `org.koin.core.context.KoinContext`?
