### ISSUE TITLE
ArrayIndexOutOfBoundsException on empty string environment variable

### ISSUE THREAD

**Issue by rt-works** [InsertKoinIO/koin#1099]
**Describe the bug**
When I'm using `environmentProperties()` in such code block:
```
startKoin {
        printLogger(Level.DEBUG)
        environmentProperties()

        modules(
            module {
                single { HelloService(getProperty("SOME_PROPERTY", "ssss")) }
            }
        )
    }
```

I'm getting following exception
```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at org.koin.ext.StringExtKt.clearQuotes(StringExt.kt:21)
	at org.koin.core.registry.PropertyRegistryExtKt.saveProperties(PropertyRegistryExt.kt:20)
	at org.koin.core.registry.PropertyRegistryExtKt.loadEnvironmentProperties(PropertyRegistryExt.kt:58)
	at org.koin.KoinApplicationExtKt.environmentProperties(KoinApplicationExt.kt:24)
```

That happens when one of the environmental variables has empty string value.

**Expected behavior**
Environmental variables with empty values should get loaded as it is with empty value without throwing the exception.

**Koin project used and used version (please complete the following information):**
 [e.g]: `koin-core version 3.0.2`

**Comment by arnaudgiuliani** [comment]
Fixed in `9b9dec8792277b13341140a4c1cbd167e604e37b`
