### ISSUE TITLE
Koin android compose 3.1.0 statehandler issue

### ISSUE THREAD

**Issue by Shusshu** [InsertKoinIO/koin#1114]
https://search.maven.org/search?q=g:io.insert-koin

@arnaudgiuliani  Could you release it too please?

**Comment by Shusshu** [comment]
Include this PR too https://github.com/InsertKoinIO/koin/pull/1113

**Comment by Egi10** [comment]
@arnaudgiuliani why **Could not find io.insert-koin:koin-androidx-scope:3.1.0.** ?

**Comment by Shusshu** [comment]
3.1.0 is now on maven central and migrating from 3.0.1 I get this error

 17:50:28.987 30502-30502/com.itsdino.app.debug E/[Koin]: Instance creation error : could not create instance for [Factory:'cxxxxxxViewModel']: org.koin.core.error.NoBeanDefFoundException: No definition found for class:'androidx.lifecycle.SavedStateHandle'. Check your definitions!
    	org.koin.core.scope.Scope.throwDefinitionNotFound(Scope.kt:240)
    	org.koin.core.scope.Scope.resolveInstance(Scope.kt:209)
    	org.koin.core.scope.Scope.get(Scope.kt:188)
    	com.itsdino.app.KoinModulesKt$appModule$1$2.invoke(KoinModules.kt:158)
    	com.itsdino.app.KoinModulesKt$appModule$1$2.invoke(KoinModules.kt:64)
    	org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:57)
    	org.koin.core.instance.FactoryInstanceFactory.get(FactoryInstanceFactory.kt:38)
    	org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:94)
    	org.koin.core.scope.Scope.resolveInstance(Scope.kt:202)
    	org.koin.core.scope.Scope.get(Scope.kt:188)
    	org.koin.androidx.viewmodel.factory.StateViewModelFactory.create(StateViewModelFactory.kt:19)
    	androidx.lifecycle.AbstractSavedStateViewModelFactory.create(AbstractSavedStateViewModelFactory.java:69)
    	androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:185)
    	androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:150)
    	org.koin.androidx.viewmodel.ViewModelResolverKt.get(ViewModelResolver.kt:23)
    	org.koin.androidx.viewmodel.ViewModelResolverKt.resolveInstance(ViewModelResolver.kt:12)
    	org.koin.androidx.viewmodel.scope.ScopeExtKt.getViewModel(ScopeExt.kt:86)
    	org.koin.androidx.viewmodel.scope.ScopeExtKt.getViewModel(ScopeExt.kt:72)
    	org.koin.androidx.viewmodel.ext.android.SavedStateRegistryOwnerExtKt.getStateViewModel(SavedStateRegistryOwnerExt.kt:73)
    	xxpackagexx.x.x.MainActivity$special$$inlined$stateViewModel$default$1.invoke(SavedStateRegistryOwnerExt.kt:80)
    	xxpackagexx.x.x.MainActivity$special$$inlined$stateViewModel$default$1.invoke(SavedStateRegistryOwnerExt.kt:43)
    	kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81)
    	xxpackagexx.x.x.MainActivity.getFeedViewModel(MainActivity.kt:62)
    	xxpackagexx.x.x.MainActivity.onCreate(MainActivity.kt:105)
    	android.app.Activity.performCreate(Activity.java:8036)
    	android.app.Activity.performCreate(Activity.java:8016)
    	android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
    	android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3581)
    	android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3765)
    	android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:102)
    	android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
    	android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
    	android.app.ActivityThread$H.handleMessage(ActivityThread.java:2193)
    	android.os.Handler.dispatchMessage(Handler.java:106)
    	android.os.Looper.loopOnce(Looper.java:201)
    	android.os.Looper.loop(Looper.java:288)
    	android.app.ActivityThread.main(ActivityThread.java:7796)
    	java.lang.reflect.Method.invoke(Native Method)
    	com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    	com.android.internal.os.ZygoteInit.main(ZygoteInit.java:974)
2021-06-11 17:50:28.988 30502-30502/com.itsdino.app.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.itsdino.app.debug, PID: 30502
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.itsdino.app.debug/xxpackagexx.x.x.MainActivity}: org.koin.core.error.InstanceCreationException: Could not create instance for [Factory:'xxpackagexx.x.x.FeedViewModel']
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3608)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3765)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:102)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2193)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7796)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:974)
     Caused by: org.koin.core.error.InstanceCreationException: Could not create instance for [Factory:'xxpackagexx.x.x.FeedViewModel']
        at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:64)
        at org.koin.core.instance.FactoryInstanceFactory.get(FactoryInstanceFactory.kt:38)
        at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:94)
        at org.koin.core.scope.Scope.resolveInstance(Scope.kt:202)
        at org.koin.core.scope.Scope.get(Scope.kt:188)
        at org.koin.androidx.viewmodel.factory.StateViewModelFactory.create(StateViewModelFactory.kt:19)
        at androidx.lifecycle.AbstractSavedStateViewModelFactory.create(AbstractSavedStateViewModelFactory.java:69)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:185)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:150)
        at org.koin.androidx.viewmodel.ViewModelResolverKt.get(ViewModelResolver.kt:23)
        at org.koin.androidx.viewmodel.ViewModelResolverKt.resolveInstance(ViewModelResolver.kt:12)
        at org.koin.androidx.viewmodel.scope.ScopeExtKt.getViewModel(ScopeExt.kt:86)
        at org.koin.androidx.viewmodel.scope.ScopeExtKt.getViewModel(ScopeExt.kt:72)
        at org.koin.androidx.viewmodel.ext.android.SavedStateRegistryOwnerExtKt.getStateViewModel(SavedStateRegistryOwnerExt.kt:73)
        at xxpackagexx.x.x.MainActivity$special$$inlined$stateViewModel$default$1.invoke(SavedStateRegistryOwnerExt.kt:80)
        at xxpackagexx.x.x.MainActivity$special$$inlined$stateViewModel$default$1.invoke(SavedStateRegistryOwnerExt.kt:43)
        at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81)
        at xxpackagexx.x.x.MainActivity.getFeedViewModel(MainActivity.kt:62)
        at xxpackagexx.x.x.MainActivity.onCreate(MainActivity.kt:105)
        at android.app.Activity.performCreate(Activity.java:8036)
        at android.app.Activity.performCreate(Activity.java:8016)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3581)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3765) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:102) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2193) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:201) 
        at android.os.Looper.loop(Looper.java:288) 
        at android.app.ActivityThread.main(ActivityThread.java:7796) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:974) 
     Caused by: org.koin.core.error.NoBeanDefFoundException: No definition found for class:'androidx.lifecycle.SavedStateHandle'. Check your definitions!
        at org.koin.core.scope.Scope.throwDefinitionNotFound(Scope.kt:240)
        at org.koin.core.scope.Scope.resolveInstance(Scope.kt:209)
        at org.koin.core.scope.Scope.get(Scope.kt:188)
        at com.itsdino.app.KoinModulesKt$appModule$1$2.invoke(KoinModules.kt:158)
        at com.itsdino.app.KoinModulesKt$appModule$1$2.invoke(KoinModules.kt:64)
        at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:57)
        at org.koin.core.instance.FactoryInstanceFactory.get(FactoryInstanceFactory.kt:38) 
        at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:94) 
        at org.koin.core.scope.Scope.resolveInstance(Scope.kt:202) 
        at org.koin.core.scope.Scope.get(Scope.kt:188) 
        at org.koin.androidx.viewmodel.factory.StateViewModelFactory.create(StateViewModelFactory.kt:19) 
        at androidx.lifecycle.AbstractSavedStateViewModelFactory.create(AbstractSavedStateViewModelFactory.java:69) 
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:185) 
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:150) 
        at org.koin.androidx.viewmodel.ViewModelResolverKt.get(ViewModelResolver.kt:23) 
        at org.koin.androidx.viewmodel.ViewModelResolverKt.resolveInstance(ViewModelResolver.kt:12) 
        at org.koin.androidx.viewmodel.scope.ScopeExtKt.getViewModel(ScopeExt.kt:86) 
        at org.koin.androidx.viewmodel.scope.ScopeExtKt.getViewModel(ScopeExt.kt:72) 
        at org.koin.androidx.viewmodel.ext.android.SavedStateRegistryOwnerExtKt.getStateViewModel(SavedStateRegistryOwnerExt.kt:73) 
        at xxpackagexx.x.x.MainActivity$special$$inlined$stateViewModel$default$1.invoke(SavedStateRegistryOwnerExt.kt:80) 
        at xxpackagexx.x.x.MainActivity$special$$inlined$stateViewModel$default$1.invoke(SavedStateRegistryOwnerExt.kt:43) 
        at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81) 
        at xxpackagexx.x.x.MainActivity.getFeedViewModel(MainActivity.kt:62) 
        at xxpackagexx.x.x.MainActivity.onCreate(MainActivity.kt:105) 
        at android.app.Activity.performCreate(Activity.java:8036) 
        at android.app.Activity.performCreate(Activity.java:8016) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3581) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3765) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:102) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2193) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:201) 
        at android.os.Looper.loop(Looper.java:288) 
        at android.app.ActivityThread.main(ActivityThread.java:7796) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:974)

**Comment by Shusshu** [comment]
It seems like you need to define your viewmodel module using `params` 

```viewModel { params -> MyViewModel(params.get(), get()) }```

**Comment by Shusshu** [comment]
@arnaudgiuliani is it intended ? 
 `get()` used to be fine 
API wise I'd suggest writing `get()` instead of `params.get()`

**Comment by arnaudgiuliani** [comment]
Yes, but finally let me check.

**Comment by arnaudgiuliani** [comment]
Yep, it's due to parameter resolution via `get()`.

It's reverted in 3.1.1
