### ISSUE TITLE
Test / Koin 3.1.0 / startKoin / KoinAppAlreadyStartedException: A Koin Application has already been started

### ISSUE THREAD

**Issue by frist008** [InsertKoinIO/koin#1120]
**Describe the bug**
After upgrading from 3.0.2 to 3.1.0, the tests were no longer successful. I do not see a change log that would prevent the use of startKoin. What happened?

**To Reproduce**
Dependencies
```
    implementation("io.insert-koin:koin-core:${Versions.DI.koin}")
    implementation("io.insert-koin:koin-core-ext:${Versions.DI.koinExt}")
    implementation("io.insert-koin:koin-android:${Versions.DI.koin}")
    implementation("io.insert-koin:koin-android-ext:${Versions.DI.koinExt}")

    testImplementation("io.insert-koin:koin-test-junit4:${Versions.DI.koin}")
```

Versions
```
        const val koin = "3.1.0"
        const val koinExt = "3.0.2"
```

My Class
```
import android.content.Context
import android.os.Build
import androidx.appcompat.app.AppCompatActivity
import androidx.fragment.app.Fragment
import androidx.test.core.app.ApplicationProvider
import com.frist008.pocketquest.TestApplication
import com.frist008.pocketquest.di.scoped.baseActivityScoped
import io.mockk.every
import io.mockk.mockk
import org.junit.Test
import org.junit.experimental.categories.Category
import org.junit.runner.RunWith
import org.koin.android.ext.koin.androidLogger
import org.koin.core.context.startKoin
import org.koin.core.logger.Level
import org.koin.core.module.Module
import org.koin.dsl.module
import org.koin.test.category.CheckModuleTest
import org.koin.test.check.checkModules
import org.koin.test.mock.MockProvider
import org.robolectric.RobolectricTestRunner
import org.robolectric.annotation.Config

@RunWith(RobolectricTestRunner::class)
@Config(
    manifest = Config.NONE,
    application = TestApplication::class,
    sdk = [Build.VERSION_CODES.P],
)
@Category(CheckModuleTest::class)
class KoinModuleTest {

    @Test
    fun checkKoinModules() {
        MockProvider.register {}

        checkModules {
            val activity = mockk<AppCompatActivity>(relaxed = true)
            val fragment = mockk<Fragment>(relaxed = true) {
                every { requireActivity() } returns activity
            }

            startKoin(this) // org.koin.core.error.KoinAppAlreadyStartedException: A Koin Application has already been started

            androidLogger(Level.ERROR)
            modules(
                createMockModuleForTest(activity, fragment),
                activitiesModule,
                executionModule,
                fragmentsModule,
                serviceModule,
                singletonRepositoryModule,
                utilsModule
            )
        }
    }

    private fun createMockModuleForTest(activity: AppCompatActivity, fragment: Fragment) =
        module {
            single { ApplicationProvider.getApplicationContext<Context>() }
            single { activity }
            single { fragment }
            createSharedScopeBetweenActivityAndFragment()
        }

    private fun Module.createSharedScopeBetweenActivityAndFragment() =
        scope<AppCompatActivity> {
            baseActivityScoped()
        }
}
```

**Expected behavior**
```
org.koin.core.error.KoinAppAlreadyStartedException: A Koin Application has already been started

	at org.koin.core.context.GlobalContext.register(GlobalContext.kt:44)
	at org.koin.core.context.GlobalContext.startKoin(GlobalContext.kt:57)
	at org.koin.core.context.DefaultContextExtKt.startKoin(DefaultContextExt.kt:26)
	at com.frist008.pocketquest.di.KoinModuleTest$checkKoinModules$2.invoke(KoinModuleTest.kt:45)
	at com.frist008.pocketquest.di.KoinModuleTest$checkKoinModules$2.invoke(KoinModuleTest.kt:39)
	at org.koin.core.context.GlobalContext.startKoin(GlobalContext.kt:64)
	at org.koin.core.context.DefaultContextExtKt.startKoin(DefaultContextExt.kt:31)
	at org.koin.test.check.CheckModulesKt.checkModules(CheckModules.kt:49)
	at org.koin.test.check.CheckModulesKt.checkModules$default(CheckModules.kt:42)
	at com.frist008.pocketquest.di.KoinModuleTest.checkKoinModules(KoinModuleTest.kt:39)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:575)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:278)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Additional moduleDefinition**
robolectric last stable version and io.mockk.mockk

**Comment by frist008** [comment]
In 3.1.1 I removed startKoin(this) and it worked. Thank you!
