### ISSUE TITLE
java.lang.IllegalStateException: Can't access ViewModels from detached fragment

### ISSUE THREAD

**Issue by chhatrasal09** [InsertKoinIO/koin#1132]
I am using viewpager2 with FragmentStateAdapter. I have 5 page in the viewpager2 and one of the fragment has viewmodel in it. If I use that same fragment in an activity it works perfectly fine.
The hierarchy of my pages are : 
``` 
Activity
|--MainFragmnet
  |--ViewPager2
    |--Fragment1
    |--Fragment2
    |--Fragment3
    |--Fragment4
    |--Fragment5
```

This is my fragment adapter :
```
class ViewPagerAdapter(f: Fragment) : FragmentStateAdapter(f) {

        override fun getItemCount(): Int {
            return 5
        }

        override fun createFragment(position: Int): Fragment {
            return when (position) {
                0 -> Fragment1()
                1 -> Fragment2()
                2 -> Fragment3()
                3 -> Fragment4()
                4 -> Fragment5().also { it.arguments = bundleOf("id" to 147) }
                else -> throw IllegalStateException()
            }
        }
    }
```

This is my Koin in Application class:
```
startKoin {
            androidLogger(Level.ERROR)
            androidContext(this@App)
            modules(appModule)
            preferenceManager = koin.get()
        }
```

This is my **Fragment5** class:
```
open class Fragment5() : Fragment() {

    protected val mViewModel: MyViewModel by viewModel()

    private lateinit var mBinding: Fragment5Binding

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        requireArguments().apply {
            mViewModel.value1 = getString("key1")
            mViewModel.value2 = getString("key2")
            mViewModel.value3 = getString("key3")
        }
    }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        mBinding.viewModel = mViewModel
   }
}
```

This the stack trace i am getting when i use this fragment in the viewpager2 :
```
java.lang.IllegalStateException: Can't access ViewModels from detached fragment
        at androidx.fragment.app.Fragment.getViewModelStore(Fragment.java:398)
        at org.koin.androidx.viewmodel.ViewModelOwner$Companion.from(ViewModelOwner.kt:19)
        at com.app.Fragment5$$special$$inlined$viewModel$1.invoke(FragmentExt.kt:37)
        at com.app.Fragment5$$special$$inlined$viewModel$1.invoke(FragmentExt.kt:37)
        at org.koin.androidx.viewmodel.scope.ScopeExtKt.getViewModel(ScopeExt.kt:71)
        at org.koin.androidx.viewmodel.koin.KoinExtKt.getViewModel(KoinExt.kt:41)
        at org.koin.androidx.viewmodel.ext.android.FragmentExtKt.getViewModel(FragmentExt.kt:71)
        at com.app.Fragment5.$$special$$inlined$viewModel$2.invoke(FragmentExt.kt:73)
        at com.app.Fragment5.$$special$$inlined$viewModel$2.invoke(FragmentExt.kt:40)
        at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81)
        at com.app.Fragment5.getViewModel(Unknown Source:2)
        at com.app.Fragment5..<init>(Fragment5.kt:31)
        at com.app.mainMenu.MainFragment$ViewPagerAdapter.createFragment(MainFragment.kt:333)
        at androidx.viewpager2.adapter.FragmentStateAdapter.ensureFragment(FragmentStateAdapter.java:276)
        at androidx.viewpager2.adapter.FragmentStateAdapter.onBindViewHolder(FragmentStateAdapter.java:183)
        at androidx.viewpager2.adapter.FragmentStateAdapter.onBindViewHolder(FragmentStateAdapter.java:72)
        at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7254)
        at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7337)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6194)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6460)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6300)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6296)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2330)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1631)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1591)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:668)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4309)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4012)
        at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4578)
        at android.view.View.layout(View.java:20699)
        at android.view.ViewGroup.layout(ViewGroup.java:6198)
        at androidx.viewpager2.widget.ViewPager2.onLayout(ViewPager2.java:526)
        at android.view.View.layout(View.java:20699)
        at android.view.ViewGroup.layout(ViewGroup.java:6198)
        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1083)
        at android.view.View.layout(View.java:20699)
        at android.view.ViewGroup.layout(ViewGroup.java:6198)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1213)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:899)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:919)
        at android.view.View.layout(View.java:20699)
        at android.view.ViewGroup.layout(ViewGroup.java:6198)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:20699)
        at android.view.ViewGroup.layout(ViewGroup.java:6198)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
2021-06-25 13:20:44.727 30274-30274/short.video.app.test E/AndroidRuntime:     at android.view.View.layout(View.java:20699)
        at android.view.ViewGroup.layout(ViewGroup.java:6198)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
        at android.view.View.layout(View.java:20699)
        at android.view.ViewGroup.layout(ViewGroup.java:6198)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:20699)
        at android.view.ViewGroup.layout(ViewGroup.java:6198)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
        at android.view.View.layout(View.java:20699)
        at android.view.ViewGroup.layout(ViewGroup.java:6198)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:757)
        at android.view.View.layout(View.java:20699)
        at android.view.ViewGroup.layout(ViewGroup.java:6198)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2865)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2392)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1529)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7407)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1009)
        at android.view.Choreographer.doCallbacks(Choreographer.java:821)
        at android.view.Choreographer.doFrame(Choreographer.java:756)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:995)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6826)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
```

**Expected behavior**
The koin should be able to inject the viewModel in the class as viewModel is injected at oncreate of the fragment/activity.

**Koin project used and used version**
```
classpath "io.insert-koin:koin-gradle-plugin:2.2.3"

apply plugin: 'koin'


def koin_version = "2.2.3"
// Koin for Android
    implementation "io.insert-koin:koin-android:$koin_version"
    // Koin AndroidX Scope features
    implementation "io.insert-koin:koin-androidx-scope:$koin_version"
// Koin AndroidX ViewModel features
    implementation "io.insert-koin:koin-androidx-viewmodel:$koin_version"
// Koin AndroidX Fragment features
    implementation "io.insert-koin:koin-androidx-fragment:$koin_version"
```

Plaese let me know if you need any extra info.

**Comment by tfreeman82** [comment]
I have the exact same setup and am experiencing the same issue on 3.1.2

**Comment by Alexs784** [comment]
I am having the same exact thing but only on some Android versions (Android 8 and 9 till now, from Android 10 seems all good)
