### ISSUE TITLE
When call Library to StartKoin, app force close and give error NoClassDefFoundError: koin/core/context/DefaultContextExtKt

### ISSUE THREAD

**Issue by raafaelima** [InsertKoinIO/koin#1165]
Hi Folks, 

I'm writing a library that uses Koin, so I initialize koin using an entry point class on the library. However, when I start the application or run a test that uses the library's classes, I receive a force close with the message of `NoClassDefFoundError: koin/core/context/DefaultContextExtKt`. Could you folks help me to understand what is happening?

Complete Error:
```
2021-08-11 17:36:41.677 11384-11384/com.myapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.myapp, PID: 11384
    java.lang.NoClassDefFoundError: Failed resolution of: Lorg/koin/core/context/DefaultContextExtKt;
        at com.myapp.MainApplication.onCreate(MainApplication.kt:50)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1189)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6460)
        at android.app.ActivityThread.access$1300(ActivityThread.java:219)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "org.koin.core.context.DefaultContextExtKt" on path: DexPathList[[zip file "/data/app/com.myapp-t3CQX_0Q94Rge7fKul7mDA==/base.apk"],nativeLibraryDirectories=[/data/app/com.myapp-t3CQX_0Q94Rge7fKul7mDA==/lib/x86_64, /system/lib64, /system/product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        ...
    ...
```

Koin Dependencies at the Library Project: 
```
implementation "io.insert-koin:koin-core:3.2.1"
implementation "io.insert-koin:koin-android:3.1.2"
testImplementation "io.insert-koin:koin-test-junit4:3.1.2"
testImplementation "io.insert-koin:koin-test:3.1.2"

```

Library Entrypoint:
```
class MyLibrary private constructor() {
    companion object {
        @Synchronized
        fun initialize(application: Application) {
            startKoin {
                androidLogger()
                androidContext(application)
                modules(coreModule, databaseModule, repositoryModule)
            }
        }
    }
}
```

Initialization on myApp:
```
class MyApplication : Application() {
    override fun onCreate() {
        super.onCreate()
        MyLibrary.initialize(this@MyApplication)
    }
}
```

**Comment by Zhuinden** [comment]
Sounds like version mismatch?

    implementation "io.insert-koin:koin-core:3.2.1" // 3.2.1
    implementation "io.insert-koin:koin-android:3.1.2"  // 3.1.2

should be same version for both

**Comment by Novikov** [comment]
Have you solved?

**Comment by andybdahl** [comment]
@raafaelima how did you fix this, I am in the same situation as of right now, developing a library as well and using koin for internal injection in the library like you in this issue. Did you ever find a way to make the app build? 🤞

**Comment by thiagokimo** [comment]
> @raafaelima how did you fix this, I am in the same situation as of right now, developing a library as well and using koin for internal injection in the library like you in this issue. Did you ever find a way to make the app build? crossed_fingers

Did you figure out what was the issue?

**Comment by Novikov** [comment]
jitpack.io helped me
