### ISSUE TITLE
Dependency Graph unit test: withInstance<*>() is not working as expected

### ISSUE THREAD

**Issue by bigman212** [InsertKoinIO/koin#1213]
**Describe the bug**
Hi!
I'm trying to validate my simple dependency graph using Unit test examples from [checkmodules](https://insert-koin.io/docs/reference/koin-test/checkmodules) :
```kotlin
// KoinAppModule.kt
object KoinAppModule {
    private val prefsModule = module {
        single { PrefsManager(context = get()) } // package.PrefsManager constructor(context: Context)
    }
    val appModule = prefsModule
}

// KoinModulesTest.kt
class KoinModulesTest : KoinTest {
    @get:Rule
    val mockProvider = MockProviderRule.create { kClass: KClass<*> ->
        // invokes properly with android.content.Context
        Mockito.mock(kClass.java)
    }

    @Test
    fun checkAllModules() {
        checkKoinModules(KoinAppModule.appModule, logLevel = Level.DEBUG) {
            withInstance<Context>() // <----
            withInstance<Application>()
        }
    }
}
```

When launching, unit test is failing with this trace:
```
[ERROR] [Koin] Instance creation error : could not create instance for [Singleton:'package.PrefsManager']: org.koin.core.error.NoBeanDefFoundException: No definition found for class:'android.content.Context'. Check your definitions!
	org.koin.core.scope.Scope.throwDefinitionNotFound(Scope.kt:293)
	org.koin.core.scope.Scope.resolveValue(Scope.kt:263)
	org.koin.core.scope.Scope.resolveInstance(Scope.kt:231)
	org.koin.core.scope.Scope.access$resolveInstance(Scope.kt:36)
	org.koin.core.scope.Scope$get$1.invoke(Scope.kt:190)
	org.koin.core.time.MeasureKt.measureDurationForResult(Measure.kt:64)
	org.koin.core.scope.Scope.get(Scope.kt:189)
	di.KoinAppModule$prefsModule$1$1.invoke(AppModule.kt:78) 
<...>

Could not create instance for [Singleton:'package.PrefsManager']
org.koin.core.error.InstanceCreationException: Could not create instance for [Singleton:'package.PrefsManager']
	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:60)
	at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
<...>
```

As you can see, Koin can't see `withInstance<Context>` definition above. 
I tried to debug all method calls and found out that:
1. Koin tries to create `PrefsManager` in `get` with valid `parameters (defaultValues=[android.content.Context])`
2. Koin sees that first constructor dependency is `android.content.Context`, it invokes `get` again, but with `parameters = null` this time.
3. Test fails

**To Reproduce**
Try to create dependency graph unit test with dependency that requires Context

**Expected behavior**
Unit test passes, dependency graph is valid

**Koin project used and used version (please complete the following information):**
```groovy
    def koin_version = "3.1.3"
    implementation "io.insert-koin:koin-core:$koin_version"
    implementation "io.insert-koin:koin-android:$koin_version"
    testImplementation "io.insert-koin:koin-test-junit4:$koin_version"
```

**Additional moduleDefinition**
DEBUG.INFO from console:
```
[DEBUG] [Koin] add mapping 'package.PrefsManager::_' for [Singleton:'package.PrefsManager']
[DEBUG] [Koin] create eager instances ...
[DEBUG] [Koin] eager instances created in 0.0154 ms
[INFO] [Koin] loaded 1 definitions - 5.556 ms
[INFO] [Koin] [Check] checking modules ...
[INFO] [Koin] [Check] definition: [Singleton:'package.PrefsManager']
[DEBUG] [Koin] +- 'package.PrefsManager'
[DEBUG] [Koin] | create instance for [Singleton:'package.PrefsManager']
[DEBUG] [Koin] +- 'android.content.Context'
[DEBUG] [Koin] 'android.content.Context' - q:'null' look in injected parameters
[DEBUG] [Koin] 'android.content.Context' - q:'null' look at scope source
[DEBUG] [Koin] 'android.content.Context' - q:'null' look in other scopes
[DEBUG] [Koin] 'android.content.Context' - q:'null' not found
```

Could you give me a hint what am I doing wrong please?

**Comment by bigman212** [comment]
Someone? 
If you are looking into it please write, Im feeling totally ignored

**Comment by arnaudgiuliani** [comment]
Let me check 👍
