### ISSUE TITLE
Null reference used for synchronization (monitor-enter)

### ISSUE THREAD

**Issue by ikartiks** [InsertKoinIO/koin#1307]
java.lang.NullPointerException: Null reference used for synchronization (monitor-enter)
at androidx.lifecycle.ViewModel.setTagIfAbsent(ViewModel.java:156)
at androidx.lifecycle.AbstractSavedStateViewModelFactory.create(AbstractSavedStateViewModelFactory.java:70)
at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:169)
at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:139)
at org.koin.androidx.viewmodel.ViewModelResolverKt.resolveInstance(ViewModelResolver.kt:15)
at org.koin.androidx.viewmodel.scope.ScopeExtKt.getViewModel(ScopeExt.kt:67)
at org.koin.androidx.viewmodel.scope.ScopeExtKt.getViewModel(ScopeExt.kt:53)
at org.koin.androidx.viewmodel.scope.ScopeExtKt.getViewModel$default(ScopeExt.kt:45)
at org.koin.androidx.viewmodel.ext.android.ComponentCallbackExtKt.getViewModel(ComponentCallbackExt.kt:63)
at com.kartik.grevocab.FragmentWordPacket$special$$inlined$viewModel$default$2.invoke(ComponentCallbackExt.kt:65)
at com.kartik.grevocab.FragmentWordPacket$special$$inlined$viewModel$default$2.invoke(ComponentCallbackExt.kt:42)
at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81)
at com.kartik.grevocab.FragmentWordPacket.getViewModel(FragmentWordPacket.kt:26)
at com.kartik.grevocab.FragmentWordPacket.onCreateView(FragmentWordPacket.kt:41)
at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2995)
at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:523)
at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1840)
at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1758)
at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1701)
at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:488)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:7839)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

[FragmentWordPacketTest.txt](https://github.com/InsertKoinIO/koin/files/8183260/FragmentWordPacketTest.txt)
[OurFragmentTestRule.txt](https://github.com/InsertKoinIO/koin/files/8183261/OurFragmentTestRule.txt)

**Expected behavior**
I expect the test to run, it was running in the previous version

**Koin project used and used version (please complete the following information):**
 `koin-core version 3.1.4`

**Comment by arnaudgiuliani** [comment]
can you give more details of your code, the part that is calling this?

**Comment by ikartiks** [comment]
@arnaudgiuliani Do you want the code for the fragment?
Its just the normal fragment with a few injected modules. I am unable to inject those modules in test using above test rule. let me know  if i am missing something.

**Comment by NickButcher1** [comment]
I also see this after upgrading Koin from 3.1.2 to 3.1.6.  All my unit tests that mock a ViewModel fail in the same way.

**Comment by arnaudgiuliani** [comment]
yes, if you have content to help 👍

**Comment by arnaudgiuliani** [comment]
Fixed in 3.2.0 - https://github.com/InsertKoinIO/koin/blob/3.2.x/android/koin-android/src/main/java/org/koin/androidx/viewmodel/ViewModelResolver.kt
