### ISSUE TITLE
Can't get ViewModel after onStop (Activity Results API)

### ISSUE THREAD

**Issue by moopat** [InsertKoinIO/koin#1308]
**Describe the bug**
My `Activity` has a `ViewModel` that is injected via `by viewModel()`. That activity launches another activity and expects a result via the [Activity Results API](https://developer.android.com/training/basics/intents/result). When the second activity returns with a result accessing the `ViewModel` results in a crash, because the `Activity` has been stopped before.

Is this expected behaviour and there's an issue with my implementation or is this a bug in Koin? This code works well in Koin 3.1.2, but breaks in all versions >= 3.1.3.

**To Reproduce**
The `MainActivity` looks like this:

```kotlin
class MainActivity : AppCompatActivity() {

    companion object {
        private const val TAG = "Koin Example"
    }

    private val model: MainViewModel by viewModel()

    private val secondActivityLauncher =
        registerForActivityResult(ActivityResultContracts.StartActivityForResult()) {
            Log.d(TAG, "Activity has returned with a result")
            handleNewData(it.data?.getIntExtra("age", -1) ?: -1)
        }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        findViewById<Button>(R.id.goToSecondActivity).setOnClickListener {
            secondActivityLauncher.launch(Intent(this, SecondActivity::class.java))
        }
    }

    private fun handleNewData(data: Int) {
        model.setAge(data)
    }

    override fun onStop() {
        super.onStop()
        Log.d(TAG, "onStop is called")
    }

    override fun onStart() {
        super.onStart()
        Log.d(TAG, "onStart is called")
    }

}
```
The crash now happens when the `model` is accessed in `handleNewData` when the second activity returns
with a result. (So I start the activity, click the button to invoke the click listener, back-press on the second activity to return to the first one, :boom:.)

The resulting logs:

```
2022-03-07 15:45:11.111 9954-9954/com.example.koin D/Koin Example: onStart is called
2022-03-07 15:45:24.487 9954-9954/com.example.koin D/Koin Example: onStop is called
2022-03-07 15:45:25.200 9954-9954/com.example.koin D/Koin Example: onStart is called
2022-03-07 15:45:25.200 9954-9954/com.example.koin D/Koin Example: Activity has returned with a result
```

And the stacktrace:

```
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
        at androidx.savedstate.SavedStateRegistry.runOnNextRecreation(SavedStateRegistry.java:168)
        at androidx.lifecycle.SavedStateHandleController.tryToAddRecreator(SavedStateHandleController.java:109)
        at androidx.lifecycle.SavedStateHandleController.create(SavedStateHandleController.java:71)
        at androidx.lifecycle.AbstractSavedStateViewModelFactory.create(AbstractSavedStateViewModelFactory.java:67)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:169)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:139)
        at org.koin.androidx.viewmodel.ViewModelResolverKt.resolveInstance(ViewModelResolver.kt:15)
        at org.koin.androidx.viewmodel.scope.ScopeExtKt.getViewModel(ScopeExt.kt:67)
        at org.koin.androidx.viewmodel.scope.ScopeExtKt.getViewModel(ScopeExt.kt:53)
        at org.koin.androidx.viewmodel.scope.ScopeExtKt.getViewModel$default(ScopeExt.kt:45)
        at org.koin.androidx.viewmodel.ext.android.ComponentCallbackExtKt.getViewModel(ComponentCallbackExt.kt:63)
        at com.example.koin.MainActivity$special$$inlined$viewModel$default$2.invoke(ComponentCallbackExt.kt:65)
        at com.example.koin.MainActivity$special$$inlined$viewModel$default$2.invoke(ComponentCallbackExt.kt:42)
        at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81)
        at com.example.koin.MainActivity.getModel(MainActivity.kt:17)
        at com.example.koin.MainActivity.handleNewData(MainActivity.kt:35)
        at com.example.koin.MainActivity.secondActivityLauncher$lambda-0(MainActivity.kt:22)
        at com.example.koin.MainActivity.$r8$lambda$I4gcesQJCvi70hpZygT64iLpFtA(Unknown Source:0)
        at com.example.koin.MainActivity$$ExternalSyntheticLambda1.onActivityResult(Unknown Source:4)
        at androidx.activity.result.ActivityResultRegistry$1.onStateChanged(ActivityResultRegistry.java:148)
        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
        at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:265)
        at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:307)
        at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:148)
        at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:134)
        at androidx.lifecycle.ReportFragment.dispatch(ReportFragment.java:68)
        at androidx.lifecycle.ReportFragment$LifecycleCallbacks.onActivityPostStarted(ReportFragment.java:187)
        at android.app.Activity.dispatchActivityPostStarted(Activity.java:1377)
        at android.app.Activity.performStart(Activity.java:8116)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3732)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2253)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7870)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

The app targets and compiles against API 31, the phone also runs API 31.

**Expected behavior**
Since the activity is being restarted, it should also get a `ViewModel`.

**Koin project used and used version (please complete the following information):**

```groovy
implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:2.4.1"
implementation "io.insert-koin:koin-android:3.1.5"
```
I could reproduce the issue with `3.2.0-beta-1` as well. It first occurred in 3.1.3.

**Additional moduleDefinition**

```kotlin
startKoin {
    androidContext(this@ExampleApplication)
    modules(listOf(
        module {
            viewModel { MainViewModel() }
        }
    ))
}
```

**Comment by arnaudgiuliani** [comment]
ok let me check

**Comment by arnaudgiuliani** [comment]
can you log the onDestroy also?

Can you try with `by viewModels()` from google API? Not sure it's related to Koin here 🤔

**Comment by moopat** [comment]
Updated example using `androidx.activity.viewModels` and logging `onDestroy` and `onResume` as well:

```kotlin
import androidx.activity.viewModels
// Other imports ommitted for brevity

class MainActivity : AppCompatActivity() {

    companion object {
        private const val TAG = "Koin Example"
    }

    private val model: MainViewModel by viewModels()

    private val secondActivityLauncher =
        registerForActivityResult(ActivityResultContracts.StartActivityForResult()) {
            Log.d(TAG, "Activity has returned with a result")
            handleNewData(it.data?.getIntExtra("age", -1) ?: -1)
        }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        findViewById<Button>(R.id.goToSecondActivity).setOnClickListener {
            secondActivityLauncher.launch(Intent(this, SecondActivity::class.java))
        }
    }

    private fun handleNewData(data: Int) {
        model.setAge(data)
    }

    override fun onResume() {
        super.onResume()
        Log.d(TAG, "onResume is called; $model")
    }

    override fun onStop() {
        super.onStop()
        Log.d(TAG, "onStop is called")
    }

    override fun onStart() {
        super.onStart()
        Log.d(TAG, "onStart is called")
    }

    override fun onDestroy() {
        super.onDestroy()
        Log.d(TAG, "onDestroy is called")
    }
}
```

Output for opening the app, navigating to the second activity and pressing back:
```
2022-03-31 10:56:18.664 28031-28031/com.example.koin D/Koin Example: onStart is called
2022-03-31 10:56:18.667 28031-28031/com.example.koin D/Koin Example: onResume is called; com.example.koin.MainViewModel@aef0118
2022-03-31 10:56:22.239 28031-28031/com.example.koin D/Koin Example: onStop is called
2022-03-31 10:56:23.497 28031-28031/com.example.koin D/Koin Example: onStart is called
2022-03-31 10:56:23.498 28031-28031/com.example.koin D/Koin Example: Activity has returned with a result
2022-03-31 10:56:23.499 28031-28031/com.example.koin D/Koin Example: onResume is called; com.example.koin.MainViewModel@aef0118
```

**Comment by arnaudgiuliani** [comment]
Fixed 🎉 - The API has been realigned with Google's API.

It should be ok for 3.1.6
