### ISSUE TITLE
Crash on viewModel initialization

### ISSUE THREAD

**Issue by naivekook** [InsertKoinIO/koin#137]
**Koin project used and used version:**
`org.koin:koin-core:1.0.0-alpha-11`
`org.koin:koin-androidx:1.0.0-alpha-11`

**Describe the bug**
Crash on fragment initialization. Works fine with koin 0.9.3.

**To Reproduce**
on activity I have this
`val viewModel by viewModel<CalendarDetailsViewModel> { parametersOf(intent.getStringExtra(EXTRA_EVENT_ID)) }`

viewModel looks like
`open class CalendarDetailsViewModel(private val eventId: String) : BaseViewModel() {
    init {
        CalendarStore.Task().fetchSingleEvent(eventId)
    }
`

CalendarStore.Task() is singleton with function 
`fun fetchSingleEvent(eventId: String) = async {
            AppKoin.get<Api.Events>().getById(eventId).awaitFirst().let { save to db }
}`

**Expected behavior**
run code without crashing :)

**Stacktrace**
`java.lang.RuntimeException: Unable to start activity ComponentInfo{CalendarDetailsActivity}: java.util.EmptyStackException
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.util.EmptyStackException
        at java.util.Stack.peek(Stack.java:102)
        at java.util.Stack.pop(Stack.java:84)
        at org.koin.core.stack.ResolutionStack.checkStackExit(ResolutionStack.kt:47)
        at org.koin.core.stack.ResolutionStack.resolve(ResolutionStack.kt:25)
        at org.koin.core.KoinContext.resolveInstance(KoinContext.kt:100)
        at org.koin.android.architecture.ext.koin.KoinContextExtKt.getWithDefinitions(KoinContextExt.kt:38)
        at org.koin.android.architecture.ext.koin.KoinContextExtKt.getByTypeName(KoinContextExt.kt:14)
        at org.koin.android.architecture.ext.koin.KoinComponentExtKt.get(KoinComponentExt.kt:13)
        at org.koin.android.architecture.KoinFactory.create(KoinFactory.kt:39)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:135)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:103)
        at org.koin.android.architecture.ext.android.LifecycleOwnerExtKt.getViewModelByClass(LifecycleOwnerExt.kt:102)
        at org.koin.android.architecture.ext.android.LifecycleOwnerExtKt$viewModelByClass$1.invoke(LifecycleOwnerExt.kt:45)
        at org.koin.android.architecture.ext.android.LifecycleOwnerExtKt$viewModelByClass$1.invoke(Unknown Source:0)
        at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:131)
        at CalendarDetailsActivity.getViewModel(Unknown Source:11)
        at CalendarDetailsActivity.initVM(CalendarDetailsActivity.kt:68)
        at CalendarDetailsActivity.onCreate(CalendarDetailsActivity.kt:53)
        at android.app.Activity.performCreate(Activity.java:6999)
        at android.app.Activity.performCreate(Activity.java:6990)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) `

**Comment by arnaudgiuliani** [comment]
thanks, I'll check that.

**Comment by naivekook** [comment]
this is coroutine(with kovenant wrapper) where I get retrofit instance from koin and request event by Id from backend

**Comment by arnaudgiuliani** [comment]
Ok,  we need more info about the crash. Can you make a very small project (public Github) to help reproduce your case?

**Comment by naivekook** [comment]
Hello, I have no time for this now, sorry, I'm trying to do this as soon as possible.

After debugging my app I see, that this crash appears, when I'm trying to get Koin dependency, which not exists in Koin scope, in init block of view model. May be this helps to you.

https://gist.github.com/naivekook/194ceba6c23267e612c07d82a922a254

**Comment by arnaudgiuliani** [comment]
Hello @naivekook , can you try again with `koin-androidx-viewmodel:1.0.0-beta-1`?

**Comment by naivekook** [comment]
`//Koin
    implementation "org.koin:koin-core:$koin_version"
    implementation "org.koin:koin-androidx-viewmodel:$koin_version"`

Failed to resolve: org.koin:koin-reflect:1.0.0-beta-1

**Comment by arnaudgiuliani** [comment]
Yep, sorry. I broke the `beta-1` with a wrong link with a new lib. Just published for the `beta-2`.

**Comment by arnaudgiuliani** [comment]
@naivekook did you tried with `beta-2`?

**Comment by naivekook** [comment]
Hi, sorry for late response
yeap, it works well on beta3
thank you very much

**Comment by arnaudgiuliani** [comment]
Nice !
