### ISSUE TITLE
Using sharedViewModel, fragment not attached to an activity.

### ISSUE THREAD

**Issue by shanlinhtet** [InsertKoinIO/koin#1371]
**Describe the bug**
```
Fatal Exception: java.lang.IllegalStateException: Fragment SaleFragment{2cdf2fa} (947870c3-822d-4ba6-aa6e-4300ce3d6499) not attached to an activity.
       at androidx.fragment.app.Fragment.requireActivity(Fragment.java:928)
       at org.koin.androidx.viewmodel.ext.android.FragmentExtKt$sharedViewModel$1.invoke(FragmentExtKt.java:36)
       at com.amdsys.ecommerce.ui.home.SaleFragment$special$$inlined$sharedViewModel$default$1.invoke(FragmentExt.kt:36)
       at org.koin.androidx.viewmodel.ext.android.FragmentExtKt$sharedViewModel$1.invoke(FragmentExtKt.java:36)
       at com.amdsys.ecommerce.ui.home.SaleFragment$special$$inlined$sharedViewModel$default$1.invoke(FragmentExt.kt:36)
       at org.koin.androidx.viewmodel.scope.ScopeExtKt.getViewModel(ScopeExt.kt:52)
       at org.koin.androidx.viewmodel.scope.ScopeExtKt.getViewModel$default(ScopeExt.kt:45)
       at org.koin.androidx.viewmodel.ext.android.FragmentExtKt.getSharedViewModel(FragmentExt.kt:59)
       at org.koin.androidx.viewmodel.ext.android.FragmentExtKt.getSharedViewModel$default(FragmentExtKt.java:49)
       at com.amdsys.ecommerce.ui.home.SaleFragment$special$$inlined$sharedViewModel$default$2.invoke(FragmentExt.kt:40)
       at org.koin.androidx.viewmodel.ext.android.FragmentExtKt$sharedViewModel$2.invoke(FragmentExtKt.java:39)
       at com.amdsys.ecommerce.ui.home.SaleFragment$special$$inlined$sharedViewModel$default$2.invoke(FragmentExt.kt:39)
       at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81)
       at com.amdsys.ecommerce.ui.home.SaleFragment.getSaleViewModel(SaleFragment.kt:23)
       at com.amdsys.ecommerce.ui.home.SaleFragment.access$getSaleViewModel(SaleFragment.kt:20)
       at com.amdsys.ecommerce.ui.home.SaleFragment$onViewCreated$2$2$3.onClick(SaleFragment.kt:69)
       at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7656)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**To Reproduce**

**Expected behavior**
declare : `private val saleViewModel by sharedViewModel<SaleViewModel>()` but found crash, when sharedViewModel needs `requireActivity()` from the ext of sharedViewModel.
```
inline fun <reified T : ViewModel> Fragment.sharedViewModel(
    qualifier: Qualifier? = null,
    noinline owner: ViewModelOwnerDefinition = { from(requireActivity(), requireActivity()) },
    noinline parameters: ParametersDefinition? = null,
): Lazy<T> {
    return lazy(LazyThreadSafetyMode.NONE) {
        getSharedViewModel(qualifier, owner, parameters)
    }
}
```
think don't need to aware for life cycle for the declaration of sharedViewModel.

**Koin project used and used version (please complete the following information):**
 [e.g]: `koin-core version 3.1.5`

**Additional moduleDefinition**
multi module project, and happen in sale module

**Comment by arnaudgiuliani** [comment]
can you try this on `3.2.0`?

**Comment by WaseemSabir** [comment]
I am having the same issue and it still exists on `3.2.0`

```
Fatal Exception: java.lang.IllegalStateException
Fragment AuditVehicleLoadedDialog{36c0aa7} (14cf55f6-c734-4006-b1db-504b786b6770) not attached to an activity.
androidx.fragment.app.Fragment.requireActivity (Fragment.java:995)
org.koin.androidx.viewmodel.ext.android.FragmentSharedVMKt$sharedViewModel$1.invoke (FragmentSharedVMKt.java:31)
com.tajir.zapp.auditor.auditvehicleloaded.AuditVehicleLoadedDialog$special$$inlined$sharedViewModel$default$1.invoke (FragmentSharedVM.kt:31)
org.koin.androidx.viewmodel.ext.android.FragmentSharedVMKt$sharedViewModel$1.invoke (FragmentSharedVMKt.java:31)
com.tajir.zapp.auditor.auditvehicleloaded.AuditVehicleLoadedDialog$special$$inlined$sharedViewModel$default$1.invoke (FragmentSharedVM.kt:31)
org.koin.androidx.viewmodel.ext.android.FragmentVMKt$viewModel$2.invoke (FragmentVMKt.java:43)
com.tajir.zapp.auditor.auditvehicleloaded.AuditVehicleLoadedDialog$special$$inlined$sharedViewModel$default$2.invoke (FragmentVM.kt:43)
org.koin.androidx.viewmodel.ext.android.FragmentVMKt$viewModel$2.invoke (FragmentVMKt.java:42)
com.tajir.zapp.auditor.auditvehicleloaded.AuditVehicleLoadedDialog$special$$inlined$sharedViewModel$default$2.invoke (FragmentVM.kt:42)
androidx.lifecycle.ViewModelLazy.getValue (ViewModelLazy.kt:47)

androidx.lifecycle.ViewModelLazy.getValue (ViewModelLazy.kt:35)
com.tajir.zapp.auditor.auditvehicleloaded.AuditVehicleLoadedDialog.getActivityViewModel (AuditVehicleLoadedDialog.kt:23)
com.tajir.zapp.auditor.auditvehicleloaded.AuditVehicleLoadedDialog.onUiStateUpdated$lambda-2 (AuditVehicleLoadedDialog.kt:90)
com.tajir.zapp.auditor.auditvehicleloaded.AuditVehicleLoadedDialog.$r8$lambda$cccpM8rJyQtQFdEH-eDmosRlT0A (AuditVehicleLoadedDialog.kt)
com.tajir.zapp.auditor.auditvehicleloaded.AuditVehicleLoadedDialog$$InternalSyntheticLambda$2$b51da61a151ebda4fdf47e6a08e4b86ee4f88c2a9a106cb54db2afede9c4d612$0.run (AuditVehicleLoadedDialog.java:2)
android.os.Handler.handleCallback (Handler.java:883)
```

**Comment by arnaudgiuliani** [comment]
Owner resolution was not lazy. `3.2.1` is bringing such fix. Make a new attempt with 3.2.1, reopen the ticket if needed 👍
