### ISSUE TITLE
Share an overridden ViewModel injected in the main flavor with a Fragment from another flavor

### ISSUE THREAD

**Issue by ivan8m8** [InsertKoinIO/koin#1467]
**Describe the bug**
When I try to share a `ViewModel`, which is overridden in the second flavor and is injected in a `Fragment` which is placed in the main flavor, with a `Fragment` which exists only in the second flavor, an exception is thrown.

**To Reproduce** [you could launch a simple demo app from [here](https://github.com/ivan8m8/KoinViewModelBug)]
Given an android project with an additional flavor except the main one.
For the main flavor we have the following structure: [`MainActivity`] **->** [`ContainerFragment`] **->** [`MyFragment`].
For the second one we go with: [`FlavoredMainActivity`] **->** [`FlavoredContainerFragment`] **->** [`MyFragment` **&&** `FlavoredFragment`].
`FlavoredMainActivity` extends `MainActivity`.
`FlavoredContainerFragment` extends `ContainerFragment`.
`MyFragment` is not placed in the second flavor. (**worth remembering**)
For `MyFragment` we have `MyViewModel`.

So, basically we have a single screen on which, depending on the flavor, one or two fragments are displayed.
And in the second flavor I want to extend `MyViewModel` to `MyFlavoredViewModel` and share it with `FlavoredFragment`.
That's all.

To achieve that I created two Koin modules:
```
object MainModule {
  val module = module {
    viewModel(named(Constants.MY_VIEW_MODEL)) { params -> MyViewModel(params.get()) }
  }
}

object FlavoredModule {
  val flavoredModule = module {
    viewModel(named(Constants.MY_VIEW_MODEL)) { params -> MyFlavoredViewModel(params.get()) } bind MyViewModel::class
  }
}
```
The `flavoredModule` gets injected last.

In `MyFragment` I inject the view model like this:
```
private val viewModel: MyViewModel by viewModel(named(Constants.MY_VIEW_MODEL)) {
  parametersOf(requireArguments().getString(KEY)!!)
}
```
And in `FlavoredFragment` I'm trying to obtain the same view model like this:
```
private val viewModel: MyFlavoredViewModel by viewModel(
  named(Constants.MY_VIEW_MODEL),
  {
    requireParentFragment()
      .childFragmentManager
      .findFragmentByTag(MyFragment.TAG)!!
  }
)
```

(Remember, `MyFragment` is placed in the main flavor, and `FlavoredFragment` placed in the second flavor.)

And the app crashes with:
```
FATAL EXCEPTION: main
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
...
Caused by: org.koin.core.error.InstanceCreationException: Could not create instance for [Factory:'io.github.ivan8m8.koinviewmodelbug.MyFlavoredViewModel',qualifier:my_view_model,binds:io.github.ivan8m8.koinviewmodelbug.MyViewModel]
at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:61)
at org.koin.core.instance.FactoryInstanceFactory.get(FactoryInstanceFactory.kt:38)
at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:111)
at org.koin.core.scope.Scope.resolveValue(Scope.kt:237)
at org.koin.core.scope.Scope.resolveInstance(Scope.kt:224)
at org.koin.core.scope.Scope.access$resolveInstance(Scope.kt:36)
at org.koin.core.scope.Scope$get$1.invoke(Scope.kt:200)
at org.koin.core.time.MeasureKt.measureTimedValue(Measure.kt:47)
at org.koin.core.time.MeasureKt.measureDurationForResult(Measure.kt:41)
at org.koin.core.scope.Scope.get(Scope.kt:199)
at org.koin.androidx.viewmodel.factory.KoinViewModelFactory.create(KoinViewModelFactory.kt:36)
at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:187)
at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:153)
at org.koin.androidx.viewmodel.GetViewModelKt.resolveViewModel(GetViewModel.kt:43)
at org.koin.androidx.viewmodel.GetViewModelKt.resolveViewModel$default(GetViewModel.kt:28)
at io.github.ivan8m8.koinviewmodelbug.FlavoredFragment$special$$inlined$viewModel$default$1.invoke(FragmentVM.kt:83)
at io.github.ivan8m8.koinviewmodelbug.FlavoredFragment$special$$inlined$viewModel$default$1.invoke(FragmentVM.kt:49)
at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81)
at io.github.ivan8m8.koinviewmodelbug.FlavoredFragment.getViewModel(FlavoredFragment.kt:22)
at io.github.ivan8m8.koinviewmodelbug.FlavoredFragment.onViewCreated(FlavoredFragment.kt:50)
at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3128)
...
Caused by: org.koin.core.error.DefinitionParameterException: No value found for type 'java.lang.String'
at io.github.ivan8m8.koinviewmodelbug.FlavoredModule$flavoredModule$1$1.invoke(FlavoredModule.kt:15)
at io.github.ivan8m8.koinviewmodelbug.FlavoredModule$flavoredModule$1$1.invoke(FlavoredModule.kt:10)
at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:54)
```

The thing is Koin is trying to create a new `MyFlavoredViewModel` instance while I expect it returns the already existing one.

The problem could be solved if in `FlavoredFragment` we resolve the view model like this:
```
private val viewModel: MyFlavoredViewModel by lazy {
  requireParentFragment()
    .childFragmentManager
    .findFragmentByTag(MyFragment.TAG)!!
    .getViewModel<MyViewModel>(named(Constants.MY_VIEW_MODEL)) as MyFlavoredViewModel
}
```
But that seems like an ugly hack to me.

Possibly, the crash will not happen if in the second flavor we extend `MyFragment` and override the view model type there.
Something like:
```
class MyFlavoredFragment : MyFragment() {
  overrride val viewModel: MyFlavoredViewModel ...
}
```
And that's a workaround again.

**Expected behavior**
`MyFlavoredViewModel` is shared between `MyFragment` (from the main flavor) and `FlavoredFragment` (from the second flavor).

**Koin project used and used version (please complete the following information):**
`io.insert-koin:koin-core:3.2.2`
`io.insert-koin:koin-android:3.3.01`

**Upd**.:
One of the key things I forgot to mention.
On the version 2.1.6 _nearly_ the same implementation [works](https://github.com/ivan8m8/KoinViewModelBug/tree/koin-2.1.6) as intended.
That's why I'm considering this case as a bug.

**Comment by ivan8m8** [comment]
I made a debug & found out that when using `named("MY_KEY")`:

- on 2.1.6 a `ViewModel` gets put into `ViewModelStore` with the key `"MY_KEY"`;
- on 3.3.0 a `ViewModel` gets put into `ViewModelStore` with the key `"androidx.lifecycle.ViewModelProvider.DefaultKey:io.github.ivan8m8.koinviewmodelbug.ViewModel"`.

Is this a bug or the behavior changed intentionally?
