### ISSUE TITLE
androidContext crashes version 3.3.0

### ISSUE THREAD

**Issue by dybarsky** [InsertKoinIO/koin#1493]
**Describe the bug**
Koin is crashing when trying to call `androidContext`: 
```kotlin

class App : Application() {
    override fun onCreate() {
        super.onCreate()
        initKoin(this)
    }
}

internal fun initKoin(context: Context) = startKoin {
    androidContext(context) // THIS CRASHES
    modules(
        gatewayModule(),
        repositoryModule(),
        interactorsModule(),
    )
}
```
Stacktace:
```
java.lang.NoSuchMethodError: No static method binds(Lkotlin/Pair;[Lkotlin/reflect/KClass;)Lkotlin/Pair; in class Lorg/koin/dsl/DefinitionBindingKt; or its super classes (declaration of 'org.koin.dsl.DefinitionBindingKt' appears in /data/app/....6.dex)
	at org.koin.android.ext.koin.KoinExtKt$androidContext$1.invoke(KoinExt.kt:60)
	at org.koin.android.ext.koin.KoinExtKt$androidContext$1.invoke(KoinExt.kt:59)
	at org.koin.dsl.ModuleDSLKt.module(ModuleDSL.kt:40)
	at org.koin.dsl.ModuleDSLKt.module$default(ModuleDSL.kt:38)
	at org.koin.android.ext.koin.KoinExtKt.androidContext(KoinExt.kt:59)
	at dybarsky.rss.app.InjectionKt$initKoin$1.invoke(Injection.kt:11)
```

Kotin 1.7.20
Koin 3.3.0

Dependencies:
```
implementation("io.insert-koin:koin-core:3.3.0")
implementation("io.insert-koin:koin-android:3.3.0")
```

**Comment by dybarsky** [comment]
3.2.2 works fine.

**Comment by skolson** [comment]
Had this issue with kotlin 1.7.21, koin core 3.3.0, koin android 3.3.0. Changed to koin android 3.3.1 and it is working now.

**Comment by arnaudgiuliani** [comment]
yes, update to the latest 3.3.1 or 3.3.2

**Comment by dybarsky** [comment]
Thanks

**Comment by usamayasin-is** [comment]
@arnaudgiuliani  Hey , I am facing the same issue on koin 3.3.0 but I cannot update koin version to 3.3.1/3.3.2 because of some limitations - what would be work around for this?
