### ISSUE TITLE
java.lang.IllegalStateException: Method addObserver must be called on the main thread

### ISSUE THREAD

**Issue by ckenergy** [InsertKoinIO/koin#1511]
**Describe the bug**
```
2023-01-30 17:22:24.520 21630-23176/com. W/System.err: java.lang.IllegalStateException: Method addObserver must be called on the main thread
2023-01-30 17:22:24.521 21630-23176/com. W/System.err:     at androidx.lifecycle.LifecycleRegistry.enforceMainThreadIfNeeded(LifecycleRegistry.java:323)
2023-01-30 17:22:24.521 21630-23176/com. W/System.err:     at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:178)
2023-01-30 17:22:24.521 21630-23176/com. W/System.err:     at org.koin.androidx.scope.ComponentActivityExtKt.registerScopeForLifecycle(ComponentActivityExt.kt:65)
2023-01-30 17:22:24.521 21630-23176/com. W/System.err:     at org.koin.androidx.scope.ComponentActivityExtKt.createScopeForCurrentLifecycle(ComponentActivityExt.kt:58)
2023-01-30 17:22:24.521 21630-23176/com. W/System.err:     at org.koin.androidx.scope.ComponentActivityExtKt.createActivityScope(ComponentActivityExt.kt:53)
2023-01-30 17:22:24.521 21630-23176/com. W/System.err:     at org.koin.androidx.scope.ComponentActivityExtKt$activityScope$1.invoke(ComponentActivityExt.kt:34)
2023-01-30 17:22:24.521 21630-23176/com. W/System.err:     at org.koin.androidx.scope.ComponentActivityExtKt$activityScope$1.invoke(ComponentActivityExt.kt:34)
2023-01-30 17:22:24.521 21630-23176/com. W/System.err:     at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
2023-01-30 17:22:24.521 21630-23176/com. W/System.err:     at com.yeahka.base.BaseKoinActivity.getScope(BaseKoinActivity.kt:13)
2023-01-30 17:22:24.521 21630-23176/com. W/System.err:     at org.koin.android.ext.android.AndroidKoinScopeExtKt.getKoinScope(AndroidKoinScopeExt.kt:15)
2023-01-30 17:22:24.522 21630-23176/com. W/System.err:     at com..main.merchant.AuthActivity$special$$inlined$viewModel$default$1.invoke(ActivityVM.kt:79)
2023-01-30 17:22:24.522 21630-23176/com. W/System.err:     at com..main.merchant.AuthActivity$special$$inlined$viewModel$default$1.invoke(ActivityVM.kt:46)
2023-01-30 17:22:24.522 21630-23176/com. W/System.err:     at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81)
2023-01-30 17:22:24.522 21630-23176/com. W/System.err:     at com.*.AuthActivity.getViewModel(AuthActivity.kt:42)
```

```
class AuthActivity : BaseKoinActivity() {
    private val viewModel by viewModel<ModifySettleTypeAuthViewModel>()

private fun getShareUrl() {
    lifecycleScope.launch { 
        val res = withContext(Dispatchers.IO) {
            try {
                //getShareUrl is suspend
                viewModel.getShareUrl()
            } catch (e: Exception) {
                e.printStackTrace()
                null
            }
        }
    }
}
```

### The first click will report an error, and then click again to be normal, and use io.insert-koin:koin-android:3.2.0 not happen

**Koin project used and used version (please complete the following information):**
 [e.g]: `io.insert-koin:koin-android:3.3.2`

**Comment by arnaudgiuliani** [comment]
Here you have `androidx.lifecycle.LifecycleRegistry.enforceMainThreadIfNeeded(LifecycleRegistry.java:323)`, android paltform check that the running thead behind VM is the main one. Take a look at your concurrent call?
