### ISSUE TITLE
sharedViewModel and activityViewModel not having the same behaviour in dynamic feature module android.

### ISSUE THREAD

**Issue by victorkemboi** [InsertKoinIO/koin#1531]
**Describe the bug**
I want to implement a shared ViewModel between two fragments in a dynamic feature module. When I provide it using `sharedViewModel` deprecated delegate, the ViewModel works as expected, but upon using `activityViewModel` the app crashes when the fragment is instantiated with the following error"
  ```
FATAL EXCEPTION: main
                 Process: app.rejareja.debug, PID: 8794
                 java.lang.RuntimeException: Cannot create an instance of class  ***ViewModel
                 	at androidx.lifecycle.ViewModelProvider$NewInstanceFactory.create(ViewModelProvider.kt:204)
                 	at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:324)
                 	at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:306)
                 	at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:280)
                 	at androidx.lifecycle.SavedStateViewModelFactory.create(SavedStateViewModelFactory.kt:128)
                 	at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:187)
                 	at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:153)
                 	at androidx.lifecycle.ViewModelLazy.getValue(ViewModelLazy.kt:53)
                 	at androidx.lifecycle.ViewModelLazy.getValue(ViewModelLazy.kt:35)
                 	at ***
                 	at ***
                 	at androidx.fragment.app.Fragment.performCreate(Fragment.java:3090)
                 	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:475)
                 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:257)
                 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1899)
                 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1823)
                 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1760)
                 	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:547)
                 	at android.os.Handler.handleCallback(Handler.java:942)
                 	at android.os.Handler.dispatchMessage(Handler.java:99)
                 	at android.os.Looper.loopOnce(Looper.java:201)
                 	at android.os.Looper.loop(Looper.java:288)
                 	at android.app.ActivityThread.main(ActivityThread.java:7872)
                 	at java.lang.reflect.Method.invoke(Native Method)
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
                 Caused by: java.lang.NoSuchMethodException: ***ViewModel.<init> []
                 	at java.lang.Class.getConstructor0(Class.java:2363)
                 	at java.lang.Class.getDeclaredConstructor(Class.java:2201)
                 	at androidx.lifecycle.ViewModelProvider$NewInstanceFactory.create(ViewModelProvider.kt:202)
                 	at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:324) 
                 	at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:306) 
                 	at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.kt:280) 
                 	at androidx.lifecycle.SavedStateViewModelFactory.create(SavedStateViewModelFactory.kt:128) 
                 	at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:187) 
                 	at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:153) 
                 	at androidx.lifecycle.ViewModelLazy.getValue(ViewModelLazy.kt:53) 
                 	at androidx.lifecycle.ViewModelLazy.getValue(ViewModelLazy.kt:35) 
                 	at *** 
                 	at ***
                 	at androidx.fragment.app.Fragment.performCreate(Fragment.java:3090) 
                 	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:475) 
                 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:257) 
                 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1899) 
                 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1823) 
                 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1760) 
                 	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:547) 
                 	at android.os.Handler.handleCallback(Handler.java:942) 
                 	at android.os.Handler.dispatchMessage(Handler.java:99) 
                 	at android.os.Looper.loopOnce(Looper.java:201) 
                 	at android.os.Looper.loop(Looper.java:288) 
                 	at android.app.ActivityThread.main(ActivityThread.java:7872) 
                 	at java.lang.reflect.Method.invoke(Native Method) 
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936) 
  ```
**Expected behavior**
When I navigate to the first fragment using a shared view model, the view model should be instantiated properly. From that first fragment, navigate to the next fragment using the shared view model. Update the state in the second fragment, then navigate back to the first fragment and the state should reflect as updated in the second fragment.

**Koin project used and used version (please complete the following information):**
 koin:koin-android version 3.3.3

**Additional moduleDefinition**
The module is a dynamic feature module

**Comment by victorkemboi** [comment]
Using the following retrieval instance: `getActivityViewModel` in `onCreate` of the fragment, the fragment is instantiated, but the state is not preserved across the fragments. I presume the same ViewModel instance is not used.
