### ISSUE TITLE
Provide more helpful error message for CheckModules with secondary types

### ISSUE THREAD

**Issue by mreichelt** [InsertKoinIO/koin#1569]
Let's say we have an invalid secondary type definition:

```kotlin
single { "the_string" } binds arrayOf(
    CharSequence::class,
    Int::class,   // <---- invalid
)
```

When we use the `checkModules()` functionality, the exception will look like this:

```
java.lang.IllegalArgumentException: Failed requirement.
    at org.koin.test.check.CheckModulesKt.checkDefinition(CheckModules.kt:155)
```

This does not include any info of what goes wrong.

### The idea

Let's provide a helpful error message for developers!

```
java.lang.IllegalArgumentException: instance of class kotlin.String is not inheritable from class kotlin.Int
    at org.koin.test.check.CheckModulesKt.checkDefinition(CheckModules.kt:155)
```

**Comment by arnaudgiuliani** [comment]
Checking your PR 👍

**Comment by arnaudgiuliani** [comment]
merged PR 👍
