### ISSUE TITLE
`koinApplication{}.checkModules() ` closes the scope, making testing feel complicating

### ISSUE THREAD

**Issue by egslava** [InsertKoinIO/koin#1596]
**Describe the bug**
I have an error: `Scope '_root_' is closed` after calling `checkModules()`. It's not clear, how to test dependencies, without calling `koinApplication{...}` again.

**To Reproduce**
```kotlin
val koin = koinApplication { modules(
    module { single { "Hello" } }
)}

class App : KoinComponent {
    override fun getKoin() = koin.koin
    val str: String by inject()
}

class ExampleUnitTest {
    @Test fun a() { koin.checkModules() }
    @Test fun b() { App().str }  // crash:  `Scope '_root_' is closed`
}
```

**Expected behavior**
I expected, that, calling `checkModules()` should not make the whole `KoinApplication` unusable anymore, thus, I expected, that the code above should work. I thought, that it's okay to have a singletone variable of `KoinApplication` type, that's initialized just once during an application start up. But if `checkModules` makes it unusable, it means, that this variable's lifecycle (`val koin: KoinApplication`) should be managed somehow to overcome it (I haven't thought much yet how exactly it should be done). I also know that there's approach via: `stopKoin()` + `startKoin()`, but, afaik, it doesn't work with isolated contexts.

**Koin project used and used version:**
'io.insert-koin:koin-core:3.4.0'
'io.insert-koin:koin-test:3.4.0'

I tried on Android and KMM.

I'm pretty sure, that it's not a bug, rather a questions, but I haven't found anything related in docs. I wonder, what would be an official approach to solve this?

**Comment by egslava** [comment]
A complete stacktrace:


```

Scope '_root_' is closed
org.koin.core.error.ClosedScopeException: Scope '_root_' is closed
	at app//org.koin.core.scope.Scope.resolveInstance(Scope.kt:221)
	at app//org.koin.core.scope.Scope.get(Scope.kt:210)
	at app//com.egslava.firstkmm.App$special$$inlined$inject$default$1.invoke(KoinComponent.kt:74)
	at app//kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at app//com.egslava.firstkmm.App.getStr(commonTest.kt:21)
	at app//com.egslava.firstkmm.TestSuit.testB(commonTest.kt:30)
	at java.base@17.0.7/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@17.0.7/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base@17.0.7/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@17.0.7/java.lang.reflect.Method.invoke(Method.java:568)
	at app//org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at app//org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at app//org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at app//org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at app//org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at app//org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at app//org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at app//org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at app//org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at app//org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at app//org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at app//org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at app//org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at app//org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at app//org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at app//org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at app//org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:108)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:40)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:60)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:52)
	at java.base@17.0.7/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@17.0.7/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base@17.0.7/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@17.0.7/java.lang.reflect.Method.invoke(Method.java:568)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at jdk.proxy1/jdk.proxy1.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:176)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:113)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:65)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
```

**Comment by egslava** [comment]
A complete stacktrace for kmm (iOS x64):

```
org.koin.core.error.ClosedScopeException: Scope '_root_' is closed
org.koin.core.error.ClosedScopeException: Scope '_root_' is closed
	at kotlin.Throwable#<init>(/opt/buildAgent/work/acafc8c59a79cc1/kotlin/kotlin-native/runtime/src/main/kotlin/kotlin/Throwable.kt:25)
	at kotlin.Exception#<init>(/opt/buildAgent/work/acafc8c59a79cc1/kotlin/kotlin-native/runtime/src/main/kotlin/kotlin/Exceptions.kt:23)
	at org.koin.core.error.ClosedScopeException#<init>(/Users/runner/work/koin/koin/core/koin-core/src/commonMain/kotlin/org/koin/core/error/ClosedScopeException.kt:23)
	at org.koin.core.scope.Scope.resolveInstance#internal(/Users/runner/work/koin/koin/core/koin-core/src/commonMain/kotlin/org/koin/core/scope/Scope.kt:221)
	at org.koin.core.scope.Scope#get(/Users/runner/work/koin/koin/core/koin-core/src/commonMain/kotlin/org/koin/core/scope/Scope.kt:210)
	at com.egslava.firstkmm.App.<init>$lambda$0#internal(/Users/runner/work/koin/koin/core/koin-core/src/commonMain/kotlin/org/koin/core/component/KoinComponent.kt:61)
	at com.egslava.firstkmm.App.$<init>$lambda$0$FUNCTION_REFERENCE$3.invoke#internal(/Users/egslava/git/boombet/shared/src/commonTest/kotlin/com/egslava/firstkmm/commonTest.kt:32)
	at kotlin.native.concurrent.SafePublicationLazyImpl#<get-value>(/opt/buildAgent/work/acafc8c59a79cc1/kotlin/kotlin-native/runtime/src/main/kotlin/kotlin/native/concurrent/Lazy.kt:187)
	at com.egslava.firstkmm.App#<get-str>(/Users/egslava/git/boombet/shared/src/commonTest/kotlin/com/egslava/firstkmm/commonTest.kt:21)
	at com.egslava.firstkmm.TestSuit#testB(/Users/egslava/git/boombet/shared/src/commonTest/kotlin/com/egslava/firstkmm/commonTest.kt:30)
	at com.egslava.firstkmm.$TestSuit$test$0.$testB$FUNCTION_REFERENCE$7.invoke#internal(/Users/egslava/git/boombet/shared/src/commonTest/kotlin/com/egslava/firstkmm/commonTest.kt:30)
	at com.egslava.firstkmm.$TestSuit$test$0.$testB$FUNCTION_REFERENCE$7.$<bridge-UNNN>invoke(/Users/egslava/git/boombet/shared/src/commonTest/kotlin/com/egslava/firstkmm/commonTest.kt:30)
	at kotlin.native.internal.test.BaseClassSuite.TestCase#run(/opt/buildAgent/work/acafc8c59a79cc1/kotlin/kotlin-native/runtime/src/main/kotlin/kotlin/native/internal/test/TestSuite.kt:85)
	at kotlin.native.internal.test.TestRunner.run#internal(/opt/buildAgent/work/acafc8c59a79cc1/kotlin/kotlin-native/runtime/src/main/kotlin/kotlin/native/internal/test/TestRunner.kt:245)
	at kotlin.native.internal.test.TestRunner.runIteration#internal(/opt/buildAgent/work/acafc8c59a79cc1/kotlin/kotlin-native/runtime/src/main/kotlin/kotlin/native/internal/test/TestRunner.kt:271)
	at kotlin.native.internal.test.TestRunner#run(/opt/buildAgent/work/acafc8c59a79cc1/kotlin/kotlin-native/runtime/src/main/kotlin/kotlin/native/internal/test/TestRunner.kt:286)
	at kotlin.native.internal.test#testLauncherEntryPoint(/opt/buildAgent/work/acafc8c59a79cc1/kotlin/kotlin-native/runtime/src/main/kotlin/kotlin/native/internal/test/Launcher.kt:30)
	at kotlin.native.internal.test#main(/opt/buildAgent/work/acafc8c59a79cc1/kotlin/kotlin-native/runtime/src/main/kotlin/kotlin/native/internal/test/Launcher.kt:34)
	at <global>.Konan_start(/Users/egslava/.gradle/daemon/8.0/entryPointOwner:1)
	at <global>.Init_and_run_start(Unknown Source)
	at <global>.0x0(Unknown Source)

```

**Comment by arnaudgiuliani** [comment]
Yeah sure, I see your problem. Do you run it with directly, or use `startKoin`. 

You can use the local koin instance tocheck, like follow:

```kotlin
@Test
fun test() {
      // run local koin instance
      koinApplication {
              modules(modules)
              // run checks
              checkModules {
                  // ...
              }
      }
}

```

**Comment by ubuntudroid** [comment]
Sorry about necroing this, but I've stumbled onto the exact same issue. Using `koinApplication` doesn't fix the issue, unfortunately.

**Comment by adrianczuczka** [comment]
Same issue here

**Comment by wagarcdev** [comment]
So, I using the custom instrumentation runner from the Docs, on a multimodule project, without Roboeletric and cannot perform subsequent tests here too...

Only running them individually or spliting each one to its own test class and rules seems to work so far...

Any updates?

**Comment by arnaudgiuliani** [comment]
Did you tried with `verify()` API?
