### ISSUE TITLE
App is crashing for few users due to "Unable to start activity ComponentInfo" exception

### ISSUE THREAD

**Issue by Dilip-007** [InsertKoinIO/koin#1611]
**Describe the bug**
App is crashing for some of our users on production. The crash is happening in across android versions (android 9, 11,12, 13)

**To Reproduce**
Crash is happening on production in our released application and it is not reproducible manually.
So no idea how to reproduce it.
Below are few details we have at the moment:

**crash logs on firebase console**

Fatal Exception: java.lang.RuntimeException
Unable to start activity ComponentInfo{com.scripps.android.foodnetwork/com.scripps.android.foodnetwork.activities.MainActivity}: org.koin.core.error.InstanceCreationException: Could not create instance for [type:Factory,primary_type:'com.scripps.android.foodnetwork.activities.w']

Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.scripps.android.foodnetwork/com.example.foodnetwork.activities.MainActivity}: org.koin.core.error.InstanceCreationException: Could not create instance for [type:Factory,primary_type:'com.example.foodnetwork.activities.w']
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4035)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4201)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8669)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

--------------------------------------------------------------------------------------------------------------------------

Caused by org.koin.core.error.InstanceCreationException: Could not create instance for [type:Factory,primary_type:'com.example.foodnetwork.activities.w']
       at org.koin.core.instance.DefinitionInstance.create(DefinitionInstance.java:61)
       at org.koin.core.instance.FactoryDefinitionInstance.get(FactoryDefinitionInstance.java:37)
       at org.koin.core.definition.BeanDefinition.resolveInstance(BeanDefinition.java:70)
       at org.koin.core.scope.Scope.resolveInstance(Scope.java:165)
       at org.koin.core.scope.Scope.get(Scope.java:128)
       at org.koin.androidx.viewmodel.ViewModelResolutionKt$createViewModelProvider$1.create(ViewModelResolution.kt:66)
       at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:171)
       at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:139)
       at org.koin.androidx.viewmodel.ViewModelResolutionKt.getInstance(ViewModelResolution.kt:43)
       at org.koin.androidx.viewmodel.ViewModelResolutionKt.getViewModel(ViewModelResolution.kt:23)
       at org.koin.androidx.viewmodel.ext.android.LifecycleOwnerExtKt.getViewModel(LifecycleOwnerExt.kt:85)
       at org.koin.androidx.viewmodel.ext.android.LifecycleOwnerExtKt.getViewModel$default(LifecycleOwnerExt.kt:83)
       at com.scripps.android.foodnetwork.viewmodels.base.ViewModelActivity$viewModel$2.invoke(ViewModelActivity.java:79)
       at com.scripps.android.foodnetwork.viewmodels.base.ViewModelActivity$viewModel$2.invoke(ViewModelActivity.java:78)
       at kotlin.SynchronizedLazyImpl.getValue(SynchronizedLazyImpl.java:74)
       at com.scripps.android.foodnetwork.viewmodels.base.ViewModelActivity.getViewModel(ViewModelActivity.java:78)
       at com.scripps.android.foodnetwork.viewmodels.base.ViewModelActivity.onCreate(ViewModelActivity.java:95)
       at com.scripps.android.foodnetwork.activities.MainActivity.onCreate(MainActivity.java:237)
       at android.app.Activity.performCreate(Activity.java:8290)
       at android.app.Activity.performCreate(Activity.java:8270)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4009)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4201)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8669)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

-------------------------------------------------------------------------------------------------------------------------

Caused by org.koin.core.error.InstanceCreationException: Could not create instance for [type:Single,primary_type:'com.example.foodnetwork.auth.d']
       at org.koin.core.instance.DefinitionInstance.create(DefinitionInstance.java:61)
       at org.koin.core.instance.SingleDefinitionInstance.get(SingleDefinitionInstance.java:40)
       at org.koin.core.definition.BeanDefinition.resolveInstance(BeanDefinition.java:70)
       at org.koin.core.scope.Scope.resolveInstance(Scope.java:165)
       at org.koin.core.scope.Scope.get(Scope.java:128)
       at com.scripps.android.foodnetwork.app.di.koin.UiModuleKt$uiModule$1$1.invoke(UiModule.kt:777)
       at com.scripps.android.foodnetwork.app.di.koin.UiModuleKt$uiModule$1$1.invoke(UiModule.kt:126)
       at org.koin.core.instance.DefinitionInstance.create(DefinitionInstance.java:54)
       at org.koin.core.instance.FactoryDefinitionInstance.get(FactoryDefinitionInstance.java:37)
       at org.koin.core.definition.BeanDefinition.resolveInstance(BeanDefinition.java:70)
       at org.koin.core.scope.Scope.resolveInstance(Scope.java:165)
       at org.koin.core.scope.Scope.get(Scope.java:128)
       at org.koin.androidx.viewmodel.ViewModelResolutionKt$createViewModelProvider$1.create(ViewModelResolution.kt:66)
       at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:171)
       at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:139)
       at org.koin.androidx.viewmodel.ViewModelResolutionKt.getInstance(ViewModelResolution.kt:43)
       at org.koin.androidx.viewmodel.ViewModelResolutionKt.getViewModel(ViewModelResolution.kt:23)
       at org.koin.androidx.viewmodel.ext.android.LifecycleOwnerExtKt.getViewModel(LifecycleOwnerExt.kt:85)
       at org.koin.androidx.viewmodel.ext.android.LifecycleOwnerExtKt.getViewModel$default(LifecycleOwnerExt.kt:83)
       at com.scripps.android.foodnetwork.viewmodels.base.ViewModelActivity$viewModel$2.invoke(ViewModelActivity.java:79)
       at com.scripps.android.foodnetwork.viewmodels.base.ViewModelActivity$viewModel$2.invoke(ViewModelActivity.java:78)
       at kotlin.SynchronizedLazyImpl.getValue(SynchronizedLazyImpl.java:74)
       at com.scripps.android.foodnetwork.viewmodels.base.ViewModelActivity.getViewModel(ViewModelActivity.java:78)
       at com.scripps.android.foodnetwork.viewmodels.base.ViewModelActivity.onCreate(ViewModelActivity.java:95)
       at com.scripps.android.foodnetwork.activities.MainActivity.onCreate(MainActivity.java:237)
       at android.app.Activity.performCreate(Activity.java:8290)
       at android.app.Activity.performCreate(Activity.java:8270)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4009)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4201)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8669)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

**Expected behavior**
Users should get crash free and smooth experience while using the app

**Koin project used and used version (please complete the following information):**
 `koin-core version 2.0.1`
`koin-core-ext version 2.0.1`

Please let me know if further details required

**Comment by arnaudgiuliani** [comment]
First, I advise you to upgrade to Koin 3.4.x. 2.x is quite old version.

Do you have any more details, Koin can't create your instance. Do you change some proguard rules recently?
