### ISSUE TITLE
NoBeanDefFoundException for scope source when scope declared with interface

### ISSUE THREAD

**Issue by amal** [InsertKoinIO/koin#1646]
Koin can't resolve the scope source if you declare a scope with an interface or intermediate class Instead of the implementation you can't get an instance of the scope source querying an interface. `getSource` works fine, but it's deprecated.

Code example:
```kotlin
interface ScopeInterface
class Scoped(val s: ScopeInterface)

fun main(args: Array<String>) {
    val koin = startKoin {
        module {
            scope<ScopeInterface> {
                scopedOf(::Scoped)
            }
        }
    }.koin
    val scope = koin.createScope(
        scopeId = "i",
        TypeQualifier(ScopeInterface::class),
        source = object : ScopeInterface {}
    )
    scope.get<Scoped>()
}
```

Error stack trace:
```
Exception in thread "main" org.koin.core.error.NoBeanDefFoundException: No definition found for class:'Scoped' q:''. Check your definitions!
	at org.koin.core.scope.Scope.throwDefinitionNotFound(Scope.kt:304)
	at org.koin.core.scope.Scope.resolveValue(Scope.kt:274)
	at org.koin.core.scope.Scope.resolveInstance(Scope.kt:231)
	at org.koin.core.scope.Scope.get(Scope.kt:210)
```

Please make it resolvable or at least undeprecate the `getSource` method. As simple `get` can not replace it right now.

**Comment by giangpham96** [comment]
This may be a duplication of my [issue](https://github.com/InsertKoinIO/koin/issues/1595)

but it will be fixed in 3.5.0
