### ISSUE TITLE
`rememberKoinInject` not working on Web target in Kotlin Multiplatform project

### ISSUE THREAD

**Issue by JoelKanyi** [InsertKoinIO/koin#1675]
**Describe the bug**
I have a Kotlin Multiplatform project that works well on Android, iOS and Desktop. I am trying to add Web support but I keep getting  an error that it Could not create instance for '[Singleton:'MainViewModel']' yet it working well on other platforms. 

`val mainViewModel = rememberKoinInject<MainViewModel>()`

```
ERROR
Could not create instance for '[Singleton:'MainViewModel']'
InstanceCreationException: Could not create instance for '[Singleton:'MainViewModel']'
    at protoOf.create_jnbvc8_k$ (webpack-internal:///./kotlin/core-koin-core.js:829:15)
    at protoOf.create_jnbvc8_k$ (webpack-internal:///./kotlin/core-koin-core.js:996:55)
    at eval (webpack-internal:///./kotlin/core-koin-core.js:969:33)
    at protoOf.synchronized_5h0e7m_k$ (webpack-internal:///./kotlin/core-koin-core.js:2464:12)
    at protoOf.get_kchvk2_k$ (webpack-internal:///./kotlin/core-koin-core.js:1004:9)
    at protoOf.resolveInstance_cs8p06_k$ (webpack-internal:///./kotlin/core-koin-core.js:1602:70)
    at resolveValue (webpack-internal:///./kotlin/core-koin-core.js:1883:73)
    at resolveInstance (webpack-internal:///./kotlin/core-koin-core.js:1875:17)
    at protoOf.get_ocvqe2_k$ (webpack-internal:///./kotlin/core-koin-core.js:2134:13)
    at FocusBloomApp$composable (webpack-internal:///./kotlin/FocusBloom-shared.js:2057:30)
```

**Koin module and version:**
`koin-core:3.5.0`
`koin-compse:1.1.0`

**Comment by JoelKanyi** [comment]
I found the issue was on my side: 

it seems you cannot use - coroutineScope (`import cafe.adriel.voyager.core.model.coroutineScope`) on Kotlin/JS
