### ISSUE TITLE
Koin+Ktor: injecting a component defined in a different Ktor module leads to ClassCastException

### ISSUE THREAD

**Issue by semiaquatic** [InsertKoinIO/koin#1682]
Hi everyone, first of all, thanks for this great library! I have an issue using it with Ktor.

What I would like to achieve is to load a configuration before running the server (i.e. the Koin app), and to have a Ktor module that configures the server ("main module") - this module wires together app level services, basic routes, and also creates a DI module that publishes app-wide resources other modules can consume:

`build.gradle.kts`:
```kotlin
val ktor_version = "2.3.4"
val logback_version = "1.4.11"
val koin_version = "3.5.0"
val koin_ktor_version = "3.5.1"

plugins {
    kotlin("jvm") version "1.9.0"
}

group = "org.example"
version = "1.0-SNAPSHOT"

repositories {
    mavenCentral()
}

dependencies {
    implementation("ch.qos.logback:logback-classic:$logback_version")
    implementation("io.ktor:ktor-server-netty:$ktor_version")
    implementation("io.insert-koin:koin-core:$koin_version")
    implementation("io.insert-koin:koin-ktor:$koin_version")
    implementation("io.insert-koin:koin-logger-slf4j:$koin_ktor_version")
}

kotlin {
    jvmToolchain(8)
}
```

Source code, put together to one file, but in practice separated to multiple files:
```kotlin
import io.ktor.server.application.*
import io.ktor.server.engine.*
import io.ktor.server.netty.*
import io.ktor.server.response.*
import io.ktor.server.routing.*
import org.koin.dsl.module
import org.koin.ktor.ext.inject
import org.koin.ktor.plugin.Koin
import org.koin.ktor.plugin.koin
import org.koin.logger.slf4jLogger

// Config.kt
data class Config(
    val devMode: Boolean = true,
    val watch: List<String> = listOf("classes", "resources"),
    val host: String = "localhost",
    val port: Int = 8080
)

// Util.kt
fun appModule(module: Application.() -> Unit) = module

// AppModuleDI.kt
fun appWideKoinModule(config: Config) = module {
    single { config }
}

// FeatureModuleDI.kt
val featureSpecificKoinModule = module {
    //...
}

// AppModule.kt
fun mainModule(config: Config) = appModule {
    install(Koin) {
        slf4jLogger()
        modules(appWideKoinModule(config))
    }
}

// FeatureModule.kt
val featureModule = appModule {
    koin {
        modules(featureSpecificKoinModule)
    }

    routing {
        val cfg by inject<Config>()
        get("/") {
            call.respondText {
                cfg.toString()
            }
        }
    }
}

// Main.kt
fun main() {
    val cfg = Config() // IRL load from external source

    System.setProperty("io.ktor.development", cfg.devMode.toString())

    embeddedServer(Netty, applicationEngineEnvironment {
        watchPaths += cfg.watch

        connector {
            host = cfg.host
            port = cfg.port
        }

        modules += mainModule(cfg)
        modules += featureModule
    }).start(wait = true)
}
```

The problem is, that when I call the `/` endpoint I get the following exception:
```
14:36:46.977 [eventLoopGroupProxy-4-2] ERROR Application -- Unhandled: GET - /
java.lang.ClassCastException: class Config cannot be cast to class Config (Config is in unnamed module of loader 'app'; Config is in unnamed module of loader io.ktor.server.engine.OverridingClassLoader$ChildURLClassLoader @4fe767f3)
	at MainKt$featureModule$1$2.invoke$lambda$0(Main.kt:48)
	at MainKt$featureModule$1$2.access$invoke$lambda$0(Main.kt:47)
	at MainKt$featureModule$1$2$1$1.invokeSuspend(Main.kt:51)
	at MainKt$featureModule$1$2$1$1.invoke(Main.kt)
	at MainKt$featureModule$1$2$1$1.invoke(Main.kt)
	at io.ktor.server.response.ApplicationResponseFunctionsKt.respondText(ApplicationResponseFunctions.kt:139)
	at io.ktor.server.response.ApplicationResponseFunctionsKt.respondText$default(ApplicationResponseFunctions.kt:134)
	at MainKt$featureModule$1$2$1.invokeSuspend(Main.kt:50)
	at MainKt$featureModule$1$2$1.invoke(Main.kt)
	at MainKt$featureModule$1$2$1.invoke(Main.kt)
	at io.ktor.server.routing.Route$buildPipeline$1$1.invokeSuspend(Route.kt:116)
	at io.ktor.server.routing.Route$buildPipeline$1$1.invoke(Route.kt)
	at io.ktor.server.routing.Route$buildPipeline$1$1.invoke(Route.kt)
	at io.ktor.util.pipeline.DebugPipelineContext.proceedLoop(DebugPipelineContext.kt:80)
	at io.ktor.util.pipeline.DebugPipelineContext.proceed(DebugPipelineContext.kt:57)
	at io.ktor.util.pipeline.DebugPipelineContext.execute$ktor_utils(DebugPipelineContext.kt:63)
	at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:77)
	at io.ktor.server.routing.Routing$executeResult$$inlined$execute$1.invokeSuspend(Pipeline.kt:478)
	at io.ktor.server.routing.Routing$executeResult$$inlined$execute$1.invoke(Pipeline.kt)
	at io.ktor.server.routing.Routing$executeResult$$inlined$execute$1.invoke(Pipeline.kt)
	at io.ktor.util.debug.ContextUtilsKt.initContextInDebugMode(ContextUtils.kt:17)
	at io.ktor.server.routing.Routing.executeResult(Routing.kt:190)
	at io.ktor.server.routing.Routing.interceptor(Routing.kt:64)
	at io.ktor.server.routing.Routing$Plugin$install$1.invokeSuspend(Routing.kt:140)
	at io.ktor.server.routing.Routing$Plugin$install$1.invoke(Routing.kt)
	at io.ktor.server.routing.Routing$Plugin$install$1.invoke(Routing.kt)
	at io.ktor.util.pipeline.DebugPipelineContext.proceedLoop(DebugPipelineContext.kt:80)
	at io.ktor.util.pipeline.DebugPipelineContext.proceed(DebugPipelineContext.kt:57)
	at io.ktor.server.engine.BaseApplicationEngineKt$installDefaultTransformationChecker$1.invokeSuspend(BaseApplicationEngine.kt:124)
	at io.ktor.server.engine.BaseApplicationEngineKt$installDefaultTransformationChecker$1.invoke(BaseApplicationEngine.kt)
	at io.ktor.server.engine.BaseApplicationEngineKt$installDefaultTransformationChecker$1.invoke(BaseApplicationEngine.kt)
	at io.ktor.util.pipeline.DebugPipelineContext.proceedLoop(DebugPipelineContext.kt:80)
	at io.ktor.util.pipeline.DebugPipelineContext.proceed(DebugPipelineContext.kt:57)
	at io.ktor.util.pipeline.DebugPipelineContext.execute$ktor_utils(DebugPipelineContext.kt:63)
	at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:77)
	at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$1$invokeSuspend$$inlined$execute$1.invokeSuspend(Pipeline.kt:478)
	at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$1$invokeSuspend$$inlined$execute$1.invoke(Pipeline.kt)
	at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$1$invokeSuspend$$inlined$execute$1.invoke(Pipeline.kt)
	at io.ktor.util.debug.ContextUtilsKt.initContextInDebugMode(ContextUtils.kt:17)
	at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$1.invokeSuspend(DefaultEnginePipeline.kt:123)
	at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$1.invoke(DefaultEnginePipeline.kt)
	at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$1.invoke(DefaultEnginePipeline.kt)
	at io.ktor.util.pipeline.DebugPipelineContext.proceedLoop(DebugPipelineContext.kt:80)
	at io.ktor.util.pipeline.DebugPipelineContext.proceed(DebugPipelineContext.kt:57)
	at io.ktor.util.pipeline.DebugPipelineContext.execute$ktor_utils(DebugPipelineContext.kt:63)
	at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:77)
	at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1$invokeSuspend$$inlined$execute$1.invokeSuspend(Pipeline.kt:478)
	at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1$invokeSuspend$$inlined$execute$1.invoke(Pipeline.kt)
	at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1$invokeSuspend$$inlined$execute$1.invoke(Pipeline.kt)
	at io.ktor.util.debug.ContextUtilsKt.initContextInDebugMode(ContextUtils.kt:17)
	at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1.invokeSuspend(NettyApplicationCallHandler.kt:119)
	at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1.invoke(NettyApplicationCallHandler.kt)
	at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1.invoke(NettyApplicationCallHandler.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:44)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at io.ktor.server.netty.NettyApplicationCallHandler.handleRequest(NettyApplicationCallHandler.kt:37)
	at io.ktor.server.netty.NettyApplicationCallHandler.channelRead(NettyApplicationCallHandler.kt:29)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:61)
	at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:425)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.ktor.server.netty.EventLoopGroupProxy$Companion.create$lambda$1$lambda$0(NettyApplicationEngine.kt:296)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

After some research I found some tickets mentioning that the auto-reload mechanism causes this, and indeed disabling the dev mode is a valid workaround, we would like to use it however since it makes development much more painless.

I also found that if I change the feature module to explicitly "include" the app-wide DI module I get no exception and everything works:
```kotlin
// FeatureModule.kt
fun featureModule(config: Config) = appModule {
    koin {
        modules(appWideKoinModule(config), featureSpecificKoinModule)
    }
    //...
}
```

But this kind of defeats the purpose of DI since I need to pass around the config object to each module definiton instead of simpy be able to inject it.

I'm new to Ktor and Koin also, so maybe the whole above concept is wrong, I'm open to any suggestions.

**Comment by arnaudgiuliani** [comment]
don't you use the Koin ktor plugin with `installKoin()`?

**Comment by semiaquatic** [comment]
Hi @arnaudgiuliani ,

I do use the Ktor plugin, see in the above snipper:

```kotlin
// AppModule.kt
fun mainModule(config: Config) = appModule {
    install(Koin) {
        slf4jLogger()
        modules(appWideKoinModule(config))
    }
}
```

**Comment by arnaudgiuliani** [comment]
can you point out where it clashes? I don't know if it's a mix with Ktor or something 🤔

**Comment by semiaquatic** [comment]
Hi @arnaudgiuliani , sorry for the late reply!

I created a minimal code repo to reproduce the issue: https://github.com/semiaquatic/koin-1682

If you run the code and visit `http://localhost:8080`, the exception is thrown:

```
foo() works
11:10:31.543 [eventLoopGroupProxy-4-1] ERROR Application -- Unhandled: GET - /
java.lang.ClassCastException: class config.Config cannot be cast to class config.Config (config.Config is in unnamed module of loader 'app'; config.Config is in unnamed module of loader io.ktor.server.engine.OverridingClassLoader$ChildURLClassLoader @4c6e276e)
```

You can also see that a dependency declared in the feature module could be successfully injected since `foo() works` appears in the output before the exception is thrown.

**Comment by arnaudgiuliani** [comment]
seems a classloader issue with ktor, and reload stuff. It's even more complex here, because you pass the value from point and load it in another Ktor point/module
