### ISSUE TITLE
Can't create instance on Desktop when using Kotlin Multiplatform

### ISSUE THREAD

**Issue by DawnHNguyen** [InsertKoinIO/koin#1703]
**Describe the bug**
I'm using KMP in my project, so I want it both have android, iOS, and desktop. The Koin work well on iOS and Android. But when I run my code on desktop, the log say that koin can't create instance of my UseCase and Repository

**Expected behavior**
Koin should create instance of my UseCase and Repository with single and factory, so that I can inject it into my ViewModel and do the thing I need

**Koin module and version:**
`koin-core:3.4.3` (even if I upgrade it to `3.5.0`, nothing change)
`koin-compose:1.1.0`

**My Log**
```
Exception in thread "AWT-EventQueue-0" org.koin.core.error.InstanceCreationException: Could not create instance for '[Factory:'com.mypackage.usecases.MyUseCase']'
	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:57)
	at org.koin.core.instance.FactoryInstanceFactory.get(FactoryInstanceFactory.kt:38)
	at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:116)
	at org.koin.core.scope.Scope.resolveValue(Scope.kt:247)
	at org.koin.core.scope.Scope.resolveInstance(Scope.kt:233)
	at org.koin.core.scope.Scope.get(Scope.kt:212)
```

**Comment by DawnHNguyen** [comment]
Sorry guys, it my fail at my SQL code.
