### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by kmenager** [InsertKoinIO/koin#172]
**Describe the bug**
I have a crash caused by a ConcurrentModificationException with the following stack trace:
```
Caused by: java.util.ConcurrentModificationException
        at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)
        at org.koin.core.bean.BeanRegistry.searchDefinition(BeanRegistry.kt:120)
        at org.koin.core.bean.BeanRegistry.searchAll(BeanRegistry.kt:77)
        at com.myapp.app.common.BaseAppActivity$$special$$inlined$inject$1$1.invoke(KoinContext.kt:58)
        at com.myapp.app.common.BaseAppActivity$$special$$inlined$inject$1$1.invoke(KoinContext.kt:23)
        at org.koin.KoinContext.getVisibleBeanDefinition(KoinContext.kt:113)
        at org.koin.KoinContext.resolveInstance(KoinContext.kt:77)
        at com.myapp.app.common.BaseAppActivity$$special$$inlined$inject$1.invoke(AndroidExt.kt:179)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at com.myapp.app.common.BaseAppActivity.getPreferencesRepository(BaseAppActivity.kt)
        at com.myapp.app.common.BaseAppActivity.onStart(BaseAppActivity.kt:45)
```
My BaseAppActivity look like this :
```kt
abstract class BaseAppActivity : AppCompatActivity() {

    val preferencesRepository: PreferencesRepository by inject()

    override fun onStart() {
        super.onStart()
        val data = preferencesRepository.getData()
    }
}
```
And my module: 
```kt
val preferencesModule = applicationContext {
    bean {
        androidApplication().getSharedPreferences("shared_pref_file", Context.MODE_PRIVATE)
    }
    bean { PreferencesRepositoryImpl(get()) as PreferencesRepository }
}
```
And my application
```kt
class MyApplication : Application() {

    private val preferencesRepository by inject<PreferencesRepository>()

    override fun onCreate() {
        super.onCreate()

        startKoin(preferencesModule)
        val otherData = preferencesRepository.getOtherData()
    }
}
```

I use koin version 0.9.3

Anyone have similar issue?

**Comment by mdevilnsk** [comment]
koin 0.9.1 same issue

Starts in Application class in onCreate function
initialize when fcm push received.

Maby application can twice call onCreate?

**Comment by arnaudgiuliani** [comment]
Can you check that you are calling Koin API from different threads?

**Comment by mdevilnsk** [comment]
I call the same object (`by inject()`) from different threads (application and service)
