### ISSUE TITLE
Type resolution error

### ISSUE THREAD

**Issue by sough** [InsertKoinIO/koin#175]
Hello, I can't run app with such Koin module config:
```
factory { MyUseCase1(get(), get("executor"), get("postExecutor")) as UseCase< Response, MyUseCase1.Params> }
factory { MyUseCase2(get(), get("executor"), get("postExecutor")) as UseCase<Response, MyUseCase2.Params> }
```

Got the following error:
```
FATAL EXCEPTION: main
    Process: com.my, PID: 7399
    java.lang.RuntimeException: Unable to create application com.my.App: org.koin.error.BeanOverrideException: Try to override definition Factory [class='com.my.domain.interactor.UseCase'] with Factory [class='com.my.domain.interactor.UseCase'], but override is not allowed. Use 'override' option in your definition or module.
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5677)
        at android.app.ActivityThread.-wrap2(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1637)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:156)
        at android.app.ActivityThread.main(ActivityThread.java:6523)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
     Caused by: org.koin.error.BeanOverrideException: Try to override definition Factory [class='com.my.domain.interactor.UseCase'] with Factory [class='com.my.domain.interactor.UseCase'], but override is not allowed. Use 'override' option in your definition or module.
        at org.koin.core.bean.BeanRegistry.declare(BeanRegistry.kt:49)
        at org.koin.core.Koin.registerDefinitions(Koin.kt:103)
        at org.koin.core.Koin.registerDefinitions$default(Koin.kt:91)
        at org.koin.core.Koin.build(Koin.kt:78)
        at org.koin.standalone.StandAloneContext.loadKoinModules(StandAloneContext.kt:66)
        at org.koin.standalone.StandAloneContext.startKoin(StandAloneContext.kt:147)
        at org.koin.android.ext.android.ComponentCallbacksExtKt.startKoin(ComponentCallbacksExt.kt:59)
        at org.koin.android.ext.android.ComponentCallbacksExtKt.startKoin$default(ComponentCallbacksExt.kt:55)
        at com.my.App.onCreate(App.kt:21)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1028)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5658)
        at android.app.ActivityThread.-wrap2(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1637) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:156) 
        at android.app.ActivityThread.main(ActivityThread.java:6523) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832) 
```

**Comment by Narayane** [comment]
https://beta.insert-koin.io/docs/1.0/documentation/reference/index.html#_overriding_a_definition_or_a_module

**Comment by sough** [comment]
Problem is not in overriding, its 2 different types by parameters, problem in type erasure and I can't imaging how to handle that.

**Comment by sough** [comment]
Hello again, I resolved my issue with bean naming
`
factory("UseCase1") { MyUseCase1(get(), get("executor"), get("postExecutor")) as UseCase< Response, MyUseCase1.Params> }
 
factory("UseCase2") { MyUseCase2(get(), get("executor"), get("postExecutor")) as UseCase<Response, MyUseCase2.Params> }
`

**Comment by arnaudgiuliani** [comment]
that's it yes.
