### ISSUE TITLE
Injecting dependencies into Worker class (androidx.WorkManager)

### ISSUE THREAD

**Issue by noloman** [InsertKoinIO/koin#186]
I need to have a Worker class do an API request every x hours, and I need to inject a repository into the class. Nevertheless if I do it via constructor injection, I get the following error:

`2018-08-05 14:21:54.252 19213-19634/E/WorkerWrapper: Trouble instantiating PortfolioChangesWorker
java.lang.InstantiationException: java.lang.Class<PortfolioChangesWorker> has no zero argument constructor
    at java.lang.Class.newInstance(Native Method)
    at androidx.work.impl.WorkerWrapper.workerFromClassName(WorkerWrapper.java:496)
    at androidx.work.impl.WorkerWrapper.workerFromWorkSpec(WorkerWrapper.java:468)
    at androidx.work.impl.WorkerWrapper.runWorker(WorkerWrapper.java:173)
    at androidx.work.impl.WorkerWrapper.run(WorkerWrapper.java:105)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
    at java.lang.Thread.run(Thread.java:764)
2018-08-05 14:21:54.253 19213-19634/E/WorkerWrapper: Could for create Worker PortfolioChangesWorker`

Is there any other way of doing this, or is it a limitation in the current version of the Koin DI framework? 
Thanks a lot and keep up the good job!

**Comment by arnaudgiuliani** [comment]
For WorkerManager, you can check this: https://github.com/InsertKoinIO/koin/issues/157

Use the `KoinComponent` on a Worker class

**Comment by arnaudgiuliani** [comment]
Closing question issue - Please reopen it or post your next question on stackoverflow: https://stackoverflow.com/questions/tagged/koin
