### ISSUE TITLE
view model inject with koin dependencies from kotlin multiplatform error 

### ISSUE THREAD

**Issue by And-DS** [InsertKoinIO/koin#1908]
Hi, I am trying to set up the preview of the viewmodels. I am following the example from https://github.com/InsertKoinIO/koin/issues/1705.
```
@Preview
@Composable
fun MyScreenPreview() {
    ScreenPreview{
        MyScreen(navController = rememberNavController())
    }
}
@Composable
fun ScreenPreview(
    screen: @Composable () -> Unit
) {
    KoinApplication(application = {
        modules(appModule())
    }) { screen() }
}
```
I have the project set up with Kotlin Multiplatform. And I have koin dependecies in my kmp and in my Android project

In my kmp i have 
```
fun initKoin(enableNetworkLogs: Boolean = false, isPro: Boolean = true,  appDeclaration: KoinAppDeclaration = {}) =
    startKoin {
        appDeclaration()
        modules(
            platformModule(),
            commonModule(enableNetworkLogs = enableNetworkLogs, isPro = isPro)
        )
    }

fun commonModule(enableNetworkLogs: Boolean, pref: KMMPreference? = null, isPro: Boolean = true) = module {
    single { createJson() }
    single { createHttpClient(get(), get(), enableNetworkLogs = enableNetworkLogs) }
    single { CoroutineScope(Dispatchers.Default + SupervisorJob() ) }
    single <AlfranRepositoryInterface> { Repository(get()) }
    single { AlfranService(get(),get()) }
    single { KMMPreference(get()) }
    single { Validator() }
    single { HttpRoutes(isPro) }
}
```
In my Android project I have 
```
class MyApplication : Application() {
    companion object {
        var currentActivity: MainActivity? = null
    }
    override fun onCreate() {
        super.onCreate()
        initKoin(enableNetworkLogs = true, isPro = true) {
            // Log Koin into Android logger
            androidLogger()
            // Reference Android context
            androidContext(this@AlfranApplication)
            // Load modules
            modules(appModule )
        }   
    }
}
```
```
val appModule = module {
    viewModel { BaseViewModel(userRepository = get()) }
    viewModel { MainViewModel(userRepository = get(), preferences = get(), validator = get()) }
    viewModel { MainActivityViewModel(userRepository = get()) }
    viewModel { LoginViewModel(userRepository = get(), preferences = get(), validator = get()) }
    viewModel { SolutionViewModel(userRepository = get()) }
}
```

The problem I have when following the example above is that it says it cannot find the dependencies of the shared module, I think is normal because I dont reference Koin dependencies from KMP
```
@Composable
@Preview
fun MainViewPreview() {
    ScreenPreview{
        MainView(navController = rememberNavController())
    }
}
@Composable
fun ScreenPreview(
    screen: @Composable () -> Unit
) {
    KoinApplication(application = {
        modules(appModule)
    }) { screen() }
}

```
![image](https://github.com/InsertKoinIO/koin/assets/173818046/7c8567f3-9b1c-4edf-823b-a64f81d97bf5)

Then I try to add koin dependencies from KMP module to android project call initKoin....
```
@Composable
fun ScreenPreview(
    screen: @Composable () -> Unit
) {
    KoinApplication(application = {
        initKoin(enableNetworkLogs = true, isPro = true) {
            modules(appModule)
        }
    }) { screen() }
}
```
and I have this problem 
`org.koin.core.error.KoinAppAlreadyStartedException: A Koin Application has already been started   at org.koin.core.context.GlobalContext.register(GlobalContext.kt:44)   at org.koin.core.context.GlobalContext.startKoin(GlobalContext.kt:63)   at org.koin.core.context.DefaultContextExtKt.startKoin(DefaultContextExt.kt:40)   at com.alfran.di.KoinKt.initKoin(Koin.kt:22)   at com.alfran.android.main.MainScreenKt.ScreenPreview$lambda$8(MainScreen.kt:160)`

could you help me please?

**Koin module and version:**
```
koin = "3.5.3"
injection-koin = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koinAndroidxCompose" }
koin-androidx-navigation = { module = "io.insert-koin:koin-androidx-navigation", version.ref = "koinAndroidxCompose" }
koin-androidx-workmanager = { module = "io.insert-koin:koin-androidx-workmanager", version.ref = "koinAndroidxCompose" }
```

**Comment by vexijio** [comment]
Yeah if you use few of these previews in one file then you end up with such error. What i had to do was to check if the koin was already started like - 
```
    if (GlobalContext.getOrNull() == null) {
        startKoin {
            modules(modules.toList())
        }
    } else {
        GlobalContext.get()
    }
```

But it's not the best way to do it if previews use different modules.. @arnaudgiuliani do you guys have any example of how to do this in less cumbersome way when dealing with composable previews? When i updated koinBom to 4.0.0-RC2 with this new breaking change i now struggle with finding the best way to deal with it.

**Comment by arnaudgiuliani** [comment]
did you tried with `KoinApplication`? it should check presence of context
