### ISSUE TITLE
Exception in thread "main" java.lang.UnsatisfiedLinkError: 'long org.jetbrains.skia.paragraph.TypefaceFontProviderWithFallbackKt._nMakeAsFallbackProvider()'

### ISSUE THREAD

**Issue by TechMatrixDeveloper** [InsertKoinIO/koin#1936]
Here is my compose multiplatform project dependency

#Koin
koin = "4.0.0-RC1"
koin-compose = "1.2.0-Beta4"

#Koin
koin-bom = { group = "io.insert-koin", name = "koin-bom", version.ref = "koin" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin-compose" }
koin-composeVM = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koin-compose" }

Problem:
if i use koin "4.0.0-RC1" every dependency so it not work can you anybody tell why it happen. 

New code:
#Koin
koin-bom = { group = "io.insert-koin", name = "koin-bom", version.ref = "koin" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin" }
koin-composeVM = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koin" }

than i just run desktop version.

Error Looks like:

PS D:\Android Project\Kotlin Multiplatform - Projects\KtorDemo4> ./gradlew run
Type-safe project accessors is an incubating feature.

> Configure project :composeApp
w: The following Kotlin/Native targets cannot be built on this machine and are disabled:
iosArm64, iosSimulatorArm64, iosX64
To hide this message, add 'kotlin.native.ignoreDisabledTargets=true' to the Gradle properties.

> Task :composeApp:run
Exception in thread "main" java.lang.UnsatisfiedLinkError: 'long org.jetbrains.skia.paragraph.TypefaceFontProviderWithFallbackKt._nMakeAsFallbackProvider()'
        at org.jetbrains.skia.paragraph.TypefaceFontProviderWithFallbackKt._nMakeAsFallbackProvider(Native Method)
        at org.jetbrains.skia.paragraph.TypefaceFontProviderWithFallbackKt.access$_nMakeAsFallbackProvider(TypefaceFontProviderWithFallback.kt:1)
        at org.jetbrains.skia.paragraph.TypefaceFontProviderWithFallback.<init>(TypefaceFontProviderWithFallback.kt:16)
        at androidx.compose.ui.text.platform.FontCache.<init>(PlatformFont.skiko.kt:201)
        at androidx.compose.ui.text.platform.FontLoader.<init>(PlatformFont.skiko.kt:177)
        at androidx.compose.ui.node.RootNodeOwner$OwnerImpl.<init>(RootNodeOwner.skiko.kt:331)
        at androidx.compose.ui.node.RootNodeOwner.<init>(RootNodeOwner.skiko.kt:144)
        at androidx.compose.ui.node.RootNodeOwner.<init>(RootNodeOwner.skiko.kt)
        at androidx.compose.ui.scene.MultiLayerComposeSceneImpl.<init>(MultiLayerComposeScene.skiko.kt:112)
        at androidx.compose.ui.scene.MultiLayerComposeSceneImpl.<init>(MultiLayerComposeScene.skiko.kt)
        at androidx.compose.ui.scene.MultiLayerComposeScene_skikoKt.MultiLayerComposeScene-3tKcejY(MultiLayerComposeScene.skiko.kt:91)
        at androidx.compose.ui.scene.MultiLayerComposeScene_skikoKt.MultiLayerComposeScene-3tKcejY$default(MultiLayerComposeScene.skiko.kt:84)
        at androidx.compose.ui.scene.ComposeContainer.createComposeScene(ComposeContainer.desktop.kt:358)
        at androidx.compose.ui.scene.ComposeContainer.access$createComposeScene(ComposeContainer.desktop.kt:84)
        at androidx.compose.ui.scene.ComposeContainer$mediator$3.invoke(ComposeContainer.desktop.kt:142)
        at androidx.compose.ui.scene.ComposeContainer$mediator$3.invoke(ComposeContainer.desktop.kt:142)
        at androidx.compose.ui.scene.ComposeSceneMediator$scene$2.invoke(ComposeSceneMediator.desktop.kt:289)
        at androidx.compose.ui.scene.ComposeSceneMediator$scene$2.invoke(ComposeSceneMediator.desktop.kt:289)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at androidx.compose.ui.scene.ComposeSceneMediator.getScene(ComposeSceneMediator.desktop.kt:289)
        at androidx.compose.ui.scene.ComposeSceneMediator.setCompositionLocalContext(ComposeSceneMediator.desktop.kt:293)
        at androidx.compose.ui.scene.ComposeContainer.setCompositionLocalContext(ComposeContainer.desktop.kt:170)
        at androidx.compose.ui.awt.ComposeWindowPanel.setCompositionLocalContext(ComposeWindowPanel.desktop.kt:76)
        at androidx.compose.ui.awt.ComposeWindow.setCompositionLocalContext(ComposeWindow.desktop.kt:114)
        at androidx.compose.ui.window.Window_desktopKt$Window$10.invoke(Window.desktop.kt:411)
        at androidx.compose.ui.window.Window_desktopKt$Window$10.invoke(Window.desktop.kt:406)
        at androidx.compose.ui.window.AwtWindow_desktopKt$AwtWindow$2.invoke(AwtWindow.desktop.kt:70)
        at androidx.compose.ui.window.AwtWindow_desktopKt$AwtWindow$2.invoke(AwtWindow.desktop.kt:69)
        at androidx.compose.runtime.DisposableEffectImpl.onRemembered(Effects.kt:82)
        at androidx.compose.runtime.CompositionImpl$RememberEventDispatcher.dispatchRememberObservers(Composition.kt:1364)
        at androidx.compose.runtime.CompositionImpl.applyChangesInLocked(Composition.kt:992)
        at androidx.compose.runtime.CompositionImpl.applyChanges(Composition.kt:1013)
        at androidx.compose.runtime.Recomposer.composeInitial$runtime(Recomposer.kt:1142)
        at androidx.compose.runtime.CompositionImpl.composeInitial(Composition.kt:649)
        at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:635)
        at androidx.compose.ui.window.Application_desktopKt$awaitApplication$2$1$2.invokeSuspend(Application.desktop.kt:221)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

> Task :composeApp:run FAILED

**If anybody find solution please drop code so i can understand.**

**Comment by Shahriyar13** [comment]
Any update?

**Comment by methodus** [comment]
Please re-open the issue as it still persists.

**Comment by TomTruyen** [comment]
+1 I have this exact issue too on Desktop Windows

java.lang.UnsatisfiedLinkError: 'long org.jetbrains.skia.paragraph.TypefaceFontProviderWithFallbackKt._nMakeAsFallbackProvider()

**Comment by Shahriyar13** [comment]
@TomTruyen 
My problem fixed after I update all of the libraries to latest version, I think it was for one of the compose widget’s problem which used old version of skio,

update compose and compose compiler to latest version I think it is 1.7.0 or 1.7.0.-Beta or something.

**Comment by maulik22995** [comment]
@TomTruyen  is right I was using compose plugin version `1.6.11` and was having the same issue. I resolved it by updating it with latest alpha version `1.7.0-alpha03` .

**Comment by jacekgajek** [comment]
I get this error on  `1.7.3` and `1.7.0` as well.

**Comment by JPUF** [comment]
@jacekgajek I had the error on 1.7.3, but I've had success with 1.8.0-beta02
