### ISSUE TITLE
Cannot create nested scope

### ISSUE THREAD

**Issue by sswierczek** [InsertKoinIO/koin#200]
**Describe the bug**
Is there a way to create nested scopes? It's useful when you need object scoped to Activity shared across Fragments. Tried different approaches and couldn't find solution for it in documentation.

**To Reproduce**
1. Create module inside module:
```
val mainActivityModule = module(MainActivity.SCOPE) {
    single { SharedObject() }

    module(SomeFragment.SCOPE) {
        viewModel { SomeFragmentViewModel(get()) } // SharedObject used here or injected in SomeFragment
    }
}
```

2. Run app, open SomeFragment
3. Back
4. Error:

```
at org.koin.core.path.PathRegistry.getAllPathsFrom(PathRegistry.kt:84)
        at org.koin.core.path.PathRegistry.getAllPathsFrom(PathRegistry.kt:84)
        at org.koin.core.path.PathRegistry.getAllPathsFrom(PathRegistry.kt:84)
        at org.koin.core.path.PathRegistry.getAllPathsFrom(PathRegistry.kt:84)
        at org.koin.core.path.PathRegistry.getAllPathsFrom(PathRegistry.kt:84)
        at org.koin.core.path.PathRegistry.getAllPathsFrom(PathRegistry.kt:84)
        at org.koin.core.path.PathRegistry.getAllPathsFrom(PathRegistry.kt:84)
        at org.koin.core.path.PathRegistry.getAllPathsFrom(PathRegistry.kt:84)
        at org.koin.core.path.PathRegistry.getAllPathsFrom(PathRegistry.kt:84)
        at org.koin.core.path.PathRegistry.getAllPathsFrom(PathRegistry.kt:84)
        at org.koin.core.path.PathRegistry.getAllPathsFrom(PathRegistry.kt:84)
        at org.koin.core.path.PathRegistry.getAllPathsFrom(PathRegistry.kt:84)
        at org.koin.core.path.PathRegistry.getAllPathsFrom(PathRegistry.kt:84)
        at org.koin.core.path.PathRegistry.getAllPathsFrom(PathRegistry.kt:84)
        at org.koin.core.path.PathRegistry.getAllPathsFrom(PathRegistry.kt:84)
        at org.koin.core.path.PathRegistry.getAllPathsFrom(PathRegistry.kt:84)
        at org.koin.core.path.PathRegistry.getAllPathsFrom(PathRegistry.kt:84)
        at org.koin.core.path.PathRegistry.getAllPathsFrom(PathRegistry.kt:84)
        at org.koin.core.path.PathRegistry.getAllPathsFrom(PathRegistry.kt:84)
        at org.koin.core.path.PathRegistry.getAllPathsFrom(PathRegistry.kt:84)
        at org.koin.core.path.PathRegistry.getAllPathsFrom(PathRegistry.kt:84)
        at org.koin.core.path.PathRegistry.getAllPathsFrom(PathRegistry.kt:84)
        at org.koin.core.path.PathRegistry.getAllPathsFrom(PathRegistry.kt:84)
        at org.koin.core.path.PathRegistry.getAllPathsFrom(PathRegistry.kt:84)
        at org.koin.core.path.PathRegistry.getAllPathsFrom(PathRegistry.kt:84)
        at org.koin.core.path.PathRegistry.getAllPathsFrom(PathRegistry.kt:84)
        at org.koin.core.path.PathRegistry.getAllPathsFrom(PathRegistry.kt:84)
        at org.koin.core.path.PathRegistry.getAllPathsFrom(PathRegistry.kt:84)
        at org.koin.core.path.PathRegistry.getAllPathsFrom(PathRegistry.kt:84)
        at org.koin.core.path.PathRegistry.getAllPathsFrom(PathRegistry.kt:84)
        at org.koin.core.path.PathRegistry.getAllPathsFrom(PathRegistry.kt:84)
        at org.koin.core.path.PathRegistry.getAllPathsFrom(PathRegistry.kt:84)
        at org.koin.core.path.PathRegistry.getAllPathsFrom(PathRegistry.kt:84)
        at org.koin.core.path.PathRegistry.getAllPathsFrom(PathRegistry.kt:84)
        at org.koin.core.path.PathRegistry.getAllPathsFrom(PathRegistry.kt:84)
        at org.koin.core.path.PathRegistry.getAllPathsFrom(PathRegistry.kt:84)
        at org.koin.core.path.PathRegistry.getAllPathsFrom(PathRegistry.kt:84)
        at org.koin.core.path.PathRegistry.getAllPathsFrom(PathRegistry.kt:84)
        at org.koin.core.path.PathRegistry.getAllPathsFrom(PathRegistry.kt:84)
        at org.koin.core.path.PathRegistry.getAllPathsFrom(PathRegistry.kt:84)
        at org.koin.core.path.PathRegistry.getAllPathsFrom(PathRegistry.kt:84)
        at org.koin.core.path.PathRegistry.getAllPathsFrom(PathRegistry.kt:84)
        at org.koin.core.path.PathRegistry.getAllPathsFrom(PathRegistry.kt:84)
        at org.koin.core.path.PathRegistry.getAllPathsFrom(PathRegistry.kt:84)
        at org.koin.core.path.PathRegistry.getAllPathsFrom(PathRegistry.kt:84)
        at org.koin.core.path.PathRegistry.getAllPathsFrom(PathRegistry.kt:84)
        at org.koin.core.path.PathRegistry.getAllPathsFrom(PathRegistry.kt:84)
        at org.koin.core.path.PathRegistry.getAllPathsFrom(PathRegistry.kt:84)
        at org.koin.core.path.PathRegistry.getAllPathsFrom(PathRegistry.kt:84)
        at org.koin.core.path.PathRegistry.getAllPathsFrom(PathRegistry.kt:84)
        at org.koin.core.path.PathRegistry.getAllPathsFrom(PathRegistry.kt:84)
        at org.koin.core.path.PathRegistry.getAllPathsFrom(PathRegistry.kt:84)
        at org.koin.core.path.PathRegistry.getAllPathsFrom(PathRegistry.kt:84)
        at org.koin.core.path.PathRegistry.getAllPathsFrom(PathRegistry.kt:84)
        at org.koin.core.path.PathRegistry.getAllPathsFrom(PathRegistry.kt:84)
    
    read: unexpected EOF!
```

***Second option***
1. Create modules separately
```
val mainActivityModule = module(MainActivity.SCOPE) {
    single { SharedObject() }
}
val someModule = module(SomeFragment.SCOPE) {
    viewModel { SomeFragmentViewModel(get()) } // SharedObject cannot be injected
}
```
2. Run app
3. Cannot see instances from different scopes

**Expected behavior**
Nested scope is created. Objects are released depending on scopes.

**Koin project used and used version (please complete the following information):**
 `koin-android, koin-androidx-scope, koin-androidx-viewmodel version 1.0.0-beta-7`

**Comment by arnaudgiuliani** [comment]
What is `SCOPE` behind your class?

**Comment by sswierczek** [comment]
@arnaudgiuliani It is just string constant like "MainActivity.SCOPE"

**Comment by arnaudgiuliani** [comment]
1st question, why use a module for your ViewModel?

**Comment by sswierczek** [comment]
@arnaudgiuliani I have more objects provided with inject like adapter which I want to release on Fragment destroy. ViewModel is just one of dependencies in this scope. Should't i put viewmodel{} in scoped module?

To give some more background. This is Activity with multiple Fragments as content. Each Fragments has it's own VM and other objects that need to be scoped just to it's lifecycle. I need object (could be VM) that is scoped to Activity and all Fragments can us it. When I finish Activity it should be released. 

In my particular case this is ToolbarViewModel in Activity which binds to Toolbar and Fragments (or their VMs) can change title etc.

**Comment by arnaudgiuliani** [comment]
You can simply write it:

```kotlin
val mainActivityModule = module(MainActivity.SCOPE) {
    single { SharedObject() }

    viewModel { SomeFragmentViewModel(get()) }
}
```

and in your activity use: `scopedWith(MainActivity.SCOPE)`. It will drop `MainActivity.SCOPE` from any single instances.
Your VM will inject as normally.

**Comment by sswierczek** [comment]
@arnaudgiuliani ok maybe I could somehow manage to keep it like that + factories but what when I would need single for SomeFragment scope?

**Comment by arnaudgiuliani** [comment]
then make a module for such single definition, and use the `scopedWith`in your fragment with that module.

Such feature proposal could help us much more: https://github.com/InsertKoinIO/koin/issues/203
and avoid creating manually modules.

Scope is kinda manual and complex to plug and play :/

**Comment by arnaudgiuliani** [comment]
Also think about the `sharedViewModel` in fragments.

**Comment by Narayane** [comment]
@sswierczek  https://developer.android.com/topic/libraries/architecture/viewmodel#sharing ?

**Comment by sswierczek** [comment]
@arnaudgiuliani @Narayane I will try this. Where I should declare this shared view model? In Activity module?

**Comment by arnaudgiuliani** [comment]
just use `by sharedViewModel()` in your fragments, it will reuse the VM instance from Activity.

**Comment by sswierczek** [comment]
@arnaudgiuliani @Narayane thank you, shared view model solved my issue :relieved: Still would be good to have possibility of using nested scope for other objects if necessary.

**Comment by arnaudgiuliani** [comment]
Cool. Work will be on "shared" instances scope I think. Keep in touch.
