### ISSUE TITLE
Error - getCachedJsObject is not defined when using 4.0.0 with wasm.

### ISSUE THREAD

**Issue by NiteshMisra** [InsertKoinIO/koin#2005]
Stack trace

getCachedJsObject is not defined
ReferenceError: getCachedJsObject is not defined
    at kotlin.wasm.internal.getCachedJsObject_$external_fun (webpack-internal:///./kotlin/composeApp.uninstantiated.mjs:120:78)
    at <UI:composeApp>.kotlin.wasm.internal.getCachedJsObject_$external_fun__externalAdapter (http://localhost:8080/composeApp.wasm:wasm-function[13334]:0x42d258)
    at <UI:composeApp>.kotlin.wasm.internal.externRefToAny (http://localhost:8080/composeApp.wasm:wasm-function[13296]:0x42cfd1)
    at <UI:composeApp>.kotlin.wasm.internal.jsToKotlinAnyAdapter (http://localhost:8080/composeApp.wasm:wasm-function[13295]:0x42cfa4)
    at <UI:composeApp>.com.easygauta.sdui.main (http://localhost:8080/composeApp.wasm:wasm-function[71290]:0x9046ad)
    at <UI:composeApp>.kotlin.wasm.internal.mainCallsWrapper (http://localhost:8080/composeApp.wasm:wasm-function[71302]:0x90c4b3)
    at <UI:composeApp>._initialize (http://localhost:8080/composeApp.wasm:wasm-function[71303]:0x90c4bf)
    at instantiate (webpack-internal:///./kotlin/composeApp.uninstantiated.mjs:5841:21)
    at async eval (webpack-internal:///./kotlin/composeApp.mjs:18:18)

**Comment by muazkadan** [comment]
Can you provide more context about the problem and what other libraries you are using?

**Comment by NiteshMisra** [comment]
When I am running my wasm project after adding koin (v4.0.0) then it is showing this error, Project is working fine without koin library. 

I am using these libraries in my project.

agp = "8.2.2"
compose-plugin = "1.7.0-beta02"
junit = "4.13.2"
kotlin = "2.0.20"
precomposeVersion = "1.6.0"
precomposePermissionsVersion = "0.18.0"
kotlinxCoroutinesVersion = "1.8.1"
ktorVersion = "3.0.0-beta-2"

kotlinSeriazition = "1.7.1"
essentyLifecycleVersion = "2.0.0"
koin = "4.0.0"

jbViewmodel = "2.8.0"
jbNavigation = "2.8.0-alpha10"

napierVersion = "2.7.1"

**Comment by kmbisset89** [comment]
Getting same error here

**Comment by kmbisset89** [comment]
- Create project with KMP wizards
- Add Koin to libs toml
- Add Koin-core to either the shared module in commonMain or the composeApp folder in commonMain 
- Error is generated.

**Comment by kmbisset89** [comment]
@NiteshMisra

**Comment by arnaudgiuliani** [comment]
Currently unlocking uuid on wasm. But will take a look

**Comment by kmbisset89** [comment]
@arnaudgiuliani seems to be solved with updating libraries and specifying the kotlinx serialization version

**Comment by arnaudgiuliani** [comment]
ok. Let's keep this as "workaround" to help get here
