### ISSUE TITLE
Koin can't find the definitions even if they're defined

### ISSUE THREAD

**Issue by Rattlyy** [InsertKoinIO/koin#2028]
**Describe the bug**
I have defined the modules and setup everything correctly, but "no definition found" error is still thrown.
Log below.

```
2024-10-15 01:29:27.731  6791-6791  System.out              it.rattly.polibastudents             I  [DEBUG] [Koin] (+) index 'com.russhwolf.settings.Settings::_root_' -> '[Singleton: 'com.russhwolf.settings.Settings']'
2024-10-15 01:29:27.732  6791-6791  System.out              it.rattly.polibastudents             I  [DEBUG] [Koin] (+) index 'it.rattly.polibastudents.networking.ApiProvider::_root_' -> '[Singleton: 'it.rattly.polibastudents.networking.ApiProvider']'
2024-10-15 01:29:27.732  6791-6791  System.out              it.rattly.polibastudents             I  [DEBUG] [Koin] (+) index 'it.rattly.polibastudents.services.AuthService::_root_' -> '[Singleton: 'it.rattly.polibastudents.services.AuthService']'
2024-10-15 01:29:27.732  6791-6791  System.out              it.rattly.polibastudents             I  [DEBUG] [Koin] (+) index 'it.rattly.polibastudents.services.LibrettoService::_root_' -> '[Singleton: 'it.rattly.polibastudents.services.LibrettoService']'
2024-10-15 01:29:27.732  6791-6791  System.out              it.rattly.polibastudents             I  [DEBUG] [Koin] (+) index 'it.rattly.polibastudents.viewmodel.EsameViewModel::_root_' -> '[Factory: 'it.rattly.polibastudents.viewmodel.EsameViewModel']'
2024-10-15 01:29:27.735  6791-6791  System.out              it.rattly.polibastudents             I  [INFO] [Koin] Started 5 definitions in 1.445 ms
2024-10-15 01:29:27.735  6791-6791  System.out              it.rattly.polibastudents             I  [DEBUG] [Koin] Create eager instances ...
2024-10-15 01:29:27.735  6791-6791  System.out              it.rattly.polibastudents             I  [DEBUG] [Koin] Created eager instances in 0.15 ms
2024-10-15 01:29:27.765  6791-6791  AndroidRuntime          it.rattly.polibastudents             D  Shutting down VM
2024-10-15 01:29:27.770  6791-6791  AndroidRuntime          it.rattly.polibastudents             E  FATAL EXCEPTION: main (Ask Gemini)
                                                                                                    Process: it.rattly.polibastudents, PID: 6791
                                                                                                    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:590)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
                                                                                                    Caused by: java.lang.reflect.InvocationTargetException
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886) 
                                                                                                    Caused by: org.koin.core.error.NoDefinitionFoundException: No definition found for type 'com.russhwolf.settings.Settings'. Check your Modules configuration and add missing type and/or qualifier!
                                                                                                    	at org.koin.core.scope.Scope.resolveFromContext(Scope.kt:532)
                                                                                                    	at org.koin.core.scope.Scope.stackParametersCall(Scope.kt:281)
                                                                                                    	at org.koin.core.scope.Scope.resolveInstance(Scope.kt:259)
                                                                                                    	at org.koin.core.scope.Scope.resolveWithOptionalLogging(Scope.kt:232)
                                                                                                    	at org.koin.core.scope.Scope.get(Scope.kt:215)
                                                                                                    	at it.rattly.polibastudents.ComposableSingletons$AppKt$lambda-2$1.invoke(App.kt:86)
                                                                                                    	at it.rattly.polibastudents.ComposableSingletons$AppKt$lambda-2$1.invoke(App.kt:43)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:380)
                                                                                                    	at org.koin.compose.KoinApplicationKt.KoinApplication(KoinApplication.kt:114)
                                                                                                    	at it.rattly.polibastudents.AppKt.App(App.kt:43)
                                                                                                    	at it.rattly.polibastudents.ComposableSingletons$MainActivityKt$lambda-1$1.invoke(MainActivity.kt:14)
                                                                                                    	at it.rattly.polibastudents.ComposableSingletons$MainActivityKt$lambda-1$1.invoke(MainActivity.kt:13)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at androidx.compose.ui.platform.ComposeView.Content(ComposeView.android.kt:441)
                                                                                                    	at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke(ComposeView.android.kt:259)
                                                                                                    	at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke(ComposeView.android.kt:258)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:380)
                                                                                                    	at androidx.compose.ui.platform.CompositionLocalsKt.ProvideCommonCompositionLocals(CompositionLocals.kt:216)
                                                                                                    	at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$3.invoke(AndroidCompositionLocals.android.kt:132)
                                                                                                    	at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$3.invoke(AndroidCompositionLocals.android.kt:131)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:380)
                                                                                                    	at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt.ProvideAndroidCompositionLocals(AndroidCompositionLocals.android.kt:121)
                                                                                                    	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$3.invoke(Wrapper.android.kt:155)
                                                                                                    	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$3.invoke(Wrapper.android.kt:154)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:401)
                                                                                                    	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Wrapper.android.kt:154)
2024-10-15 01:29:27.774  6791-6791  AndroidRuntime          it.rattly.polibastudents             E  	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Wrapper.android.kt:133) (Ask Gemini)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at androidx.compose.runtime.ActualJvm_jvmKt.invokeComposable(ActualJvm.jvm.kt:97)
                                                                                                    	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3593)
                                                                                                    	at androidx.compose.runtime.ComposerImpl.composeContent$runtime_release(Composer.kt:3520)
                                                                                                    	at androidx.compose.runtime.CompositionImpl.composeContent(Composition.kt:743)
                                                                                                    	at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(Recomposer.kt:1114)
                                                                                                    	at androidx.compose.runtime.CompositionImpl.composeInitial(Composition.kt:649)
                                                                                                    	at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:635)
                                                                                                    	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:133)
                                                                                                    	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:124)
                                                                                                    	at androidx.compose.ui.platform.AndroidComposeView.setOnViewTreeOwnersAvailable(AndroidComposeView.android.kt:1625)
                                                                                                    	at androidx.compose.ui.platform.WrappedComposition.setContent(Wrapper.android.kt:124)
                                                                                                    	at androidx.compose.ui.platform.WrappedComposition.onStateChanged(Wrapper.android.kt:180)
                                                                                                    	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.jvm.kt:320)
                                                                                                    	at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.jvm.kt:198)
                                                                                                    	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:131)
                                                                                                    	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:124)
                                                                                                    	at androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow(AndroidComposeView.android.kt:1706)
                                                                                                    	at android.view.View.dispatchAttachedToWindow(View.java:22874)
                                                                                                    	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3496)
                                                                                                    	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3503)
                                                                                                    	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3503)
                                                                                                    	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3503)
                                                                                                    	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3503)
                                                                                                    	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3362)
                                                                                                    	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2836)
                                                                                                    	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10145)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1406)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1415)
                                                                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:1015)
                                                                                                    	at android.view.Choreographer.doFrame(Choreographer.java:945)
                                                                                                    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1389)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:959)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:100)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:232)
                                                                                                    	at android.os.Looper.loop(Looper.java:317)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8674)

```

**To Reproduce**
```
val koinConfiguration = koinApplication {
    printLogger(Level.DEBUG)

    modules(module {
        singleOf<Settings>(::Settings)
    })
}

@Composable
fun App() = KoinApplication({ koinConfiguration }) {
    val settings = koinInject<Settings>()
}
```

**Koin module and version:**
koin-bom = "4.0.0"
koin-core = { module = "io.insert-koin:koin-core" }
koin-compose = { module = "io.insert-koin:koin-compose" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel" }
koin-compose-viewmodel-navigation = { module = "io.insert-koin:koin-compose-viewmodel-navigation" }
koin-core-viewmodel = { module = "io.insert-koin:koin-core-viewmodel" }

**Comment by jasonctoms** [comment]
I have the same problem, haven't been able to fix it tonight yet.  The code in the [documentation](https://insert-koin.io/docs/reference/koin-compose/compose#starting-koin-in-a-compose-app-with-koinapplication) doesn't even compile...

This issue has a supposed workaround that doesn't actually work for me, it just leads to `KoinApplication has not been started`

**Comment by arnaudgiuliani** [comment]
yes outdated documentation. Sorry. Should be fixed
