### ISSUE TITLE
KoinInitializer can't start Koin configuration

### ISSUE THREAD

**Issue by uiiang** [InsertKoinIO/koin#2043]
![微信截图_20241101110636](https://github.com/user-attachments/assets/246e5af1-0e42-4f95-a95c-66a66ebd5c71)

koin-bom = "4.0.0"
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin-bom" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin-bom" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin-bom" }
koin-androidx-workmanager = { module = "io.insert-koin:koin-androidx-workmanager", version.ref = "koin-bom" }
koin-androidx-startup = { module = "io.insert-koin:koin-androidx-startup", version.ref = "koin-bom" }

java.lang.RuntimeException: Unable to get provider androidx.startup.InitializationProvider: androidx.startup.StartupException: java.lang.IllegalStateException: KoinInitializer can't start Koin configuration. Please use KoinStartup.onKoinStartup() function to register your Koin application.
                 	at android.app.ActivityThread.installProvider(ActivityThread.java:7633)
                 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7106)
                 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6977)
                 	at android.app.ActivityThread.access$1500(ActivityThread.java:258)
                 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1983)
                 	at android.os.Handler.dispatchMessage(Handler.java:106)
                 	at android.os.Looper.loop(Looper.java:236)
                 	at android.app.ActivityThread.main(ActivityThread.java:8060)
                 	at java.lang.reflect.Method.invoke(Native Method)
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
                 Caused by: androidx.startup.StartupException: java.lang.IllegalStateException: KoinInitializer can't start Koin configuration. Please use KoinStartup.onKoinStartup() function to register your Koin application.

**Comment by arnaudgiuliani** [comment]
you have added koin-androidx-startup, and you try normal startup. remove the koin-androidx-startup lib, or setup Koin with android startup.

Wait patch 4.0.1 - https://insert-koin.io/docs/reference/koin-android/start#start-koin-with-androidx-startup-401

**Comment by LloydBlv** [comment]
This is happening on my E2E tests on the emulator using Koin **4.0.3** , the app runs, my actions get executed, but test gets stuck and I get a crash in the logcat:

```
Process: com.flydroid.locatify.test, PID: 29928
java.lang.RuntimeException: Unable to get provider androidx.startup.InitializationProvider: 
	at android.app.ActivityThread.installProvider(ActivityThread.java:8266)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7776)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7465)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2399)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8674)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.startup.Initializat
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:637)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:573)
	at android.app.AppComponentFactory.instantiateProvider(AppComponentFactory.java:147)
	at android.app.ActivityThread.installProvider(ActivityThread.java:8250)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7776) 
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7465) 
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0) 
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2399) 
	at android.os.Handler.dispatchMessage(Handler.java:107) 
	at android.os.Looper.loopOnce(Looper.java:232) 
	at android.os.Looper.loop(Looper.java:317) 
	at android.app.ActivityThread.main(ActivityThread.java:8674) 
	at java.lang.reflect.Method.invoke(Native Method) 
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580) 
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886) 
```

tried to add:

`    androidTestImplementation("androidx.startup:startup-runtime:1.1.1")`

did not help.

This is how the plugin looks like:


```
class KoinConventionPlugin : Plugin<Project> {
    override fun apply(target: Project) {
        with(target) {
            pluginManager.withPlugin("org.jetbrains.kotlin.jvm") {
                dependencies {
                    "implementation"(libs.findLibrary("koin-core").get())
                }
            }

            pluginManager.withPlugin("com.android.base") {
                dependencies {
                    "implementation"(libs.findLibrary("koin-android").get())
                }
            }

            pluginManager.withPlugin("org.jetbrains.kotlin.multiplatform") {
                dependencies {
                    "commonMainImplementation"(libs.findLibrary("koin-core").get())
                }
            }
        }
    }
```
}
