### ISSUE TITLE
Better exception for check method

### ISSUE THREAD

**Issue by dpreussler** [InsertKoinIO/koin#205]
**Is your feature request related to a problem? Please describe.**
when check failed the exception itself should say something meaningful. Ideally the errors happened

Right now:
```
java.util.EmptyStackException
	at java.util.Stack.peek(Stack.java:102)
	at java.util.Stack.pop(Stack.java:84)
	at org.koin.core.stack.ResolutionStack.checkStackExit(ResolutionStack.kt:68)
	at org.koin.core.stack.ResolutionStack.resolve(ResolutionStack.kt:46)
	at org.koin.core.InstanceManager$proceedResolution$$inlined$synchronized$lambda$1.invoke(InstanceManager.kt:94)
	at org.koin.core.InstanceManager$proceedResolution$$inlined$synchronized$lambda$1.invoke(InstanceManager.kt:31)
	at org.koin.core.time.DurationKt.measureDuration(Duration.kt:8)
	at org.koin.core.InstanceManager.proceedResolution(InstanceManager.kt:77)
	at org.koin.core.InstanceManager.createInstances(InstanceManager.kt:139)
	at org.koin.core.InstanceManager.dryRun(InstanceManager.kt:151)
	at org.koin.test.ext.koin.KoinContextExtKt.dryRun(KoinContextExt.kt:41)
	at org.koin.test.core.StandAloneContextExtKt.check(StandAloneContextExt.kt:29)
	at org.koin.test.KoinTestKt.check(KoinTest.kt:57)
	at tv.sporttotal.android.bootstrap.KoinDryRunTest.should have all dependencies inje
 ...
```

The actual error can only be seen before the in the output:
```
2018-08-23 15:02:37:488 (KOIN)::[d] |	|	!-- [tv.sporttotal.android.navigation.BundleBuilder] resolved in 21.140864 ms
2018-08-23 15:02:37:490 (KOIN)::[e] Error while resolving instance for class 'android.content.Context' - error: org.koin.error.NoBeanDefFoundException: No compatible definition found for type 'android.content.Context'. Check your module definition 
2018-08-23 15:02:37:491 (KOIN)::[e] Error while resolving instance for class 'tv.sporttotal.android.tracking.Tracker' - error: org.koin.test.error.BrokenDefinitionException: Definition Factory [class='tv.sporttotal.android.tracking.Tracker'] is broken due to error : org.koin.error.NoBeanDefFoundException: No compatible definition found for type 'android.content.Context'. Check your module definition 
2018-08-23 15:02:37:492 (KOIN)::[e] sandbox ~ org.koin.test.error.BrokenDefinitionException: Definition Factory [class='tv.sporttotal.android.tracking.Tracker'] is broken due to error : org.koin.error.NoBeanDefFoundException: No compatible definition found for type 'android.content.Context'. Check your module definition
2018-08-23 15:02:37:515 (KOIN)::[e] Error while resolving instance for class 'tv.sporttotal.android.tracking.SearchTracker' - error: java.util.EmptyStackException 
2018-08-23 15:02:37:515 (KOIN)::[d] |-- Mock for SearchTracker, hashCode: 352378889
2018-08-23 15:02:37:515 (KOIN)::[i] \-- (*) Created
2018-08-23 15:02:37:520 (KOIN)::[i] [Close] Closing Koin context
2018-08-23 15:02:37:520 (KOIN)::[d] [Close] Closing instance resolver

```
but when just looking at JUnit results I see only:

```
 JUnit Jupiter:KoinDryRunTest:should have all dependencies injectable()
    MethodSource [className = 'tv.sporttotal.android.bootstrap.KoinDryRunTest', methodName = 'should have all dependencies injectable', methodParameterTypes = '']
    => java.util.EmptyStackException
```

**Target Koin project**
1.0.0-beta-8

**Comment by arnaudgiuliani** [comment]
Agree ... something more comprehensive.

**Comment by arnaudgiuliani** [comment]
fixed in `beta-9`
