### ISSUE TITLE
ANR when startingKoin with lazyModules

### ISSUE THREAD

**Issue by shabinder-singh** [InsertKoinIO/koin#2072]
**Describe the bug**
Encountering an ANR when starting koin with lazyModules.

**Expected behavior**
 - No ANR

**Koin module and version:**
 - `koin-core:4.0.0`

**Snippet or Sample project to help reproduce**
Add a snippet or even a small sample project to hel reproduce your case.
```
startKoin {
      androidLogger()
      androidContext(this@App)
      lazyModules(sharedModules, vmModule, localModule, dispatcher = ioDispatcher)
      modules(addOtherModule())
      fragmentFactory()
      workManagerFactory()
}
```

StackTrace:
```
main (runnable):tid=1 systid=19489 
       at kotlinx.coroutines.scheduling.DefaultIoScheduler.toString(Dispatcher.kt:94)
       at java.lang.String.valueOf(String.java:2924)
       at java.lang.StringBuilder.append(StringBuilder.java:132)
       at org.koin.core.coroutine.KoinCoroutinesEngine.onRegister(KoinCoroutinesEngine.java:47)
       at org.koin.core.extension.ExtensionManager.registerExtension(ExtensionManager.java:40)
       at org.koin.core.extension.KoinCoroutinesExtensionKt.coroutinesEngine(KoinCoroutinesExtension.kt:36)
       at org.koin.core.KoinApplicationLazyExtKt.lazyModules(KoinApplicationLazyExt.kt:39)
       at com.org.myapp.App.onCreate$lambda$0(App.java:53)
```

**Comment by arnaudgiuliani** [comment]
couldn't reproduce that on our sample apps. This is pointing to Dispatchers.IO string builder.

Activated with all 

```kotlin
StrictMode.setThreadPolicy(
            StrictMode.ThreadPolicy.Builder()
                .detectDiskReads()
                .detectDiskWrites()
                .detectAll() // or .detectAll() for all detectable problems
                .penaltyLog()
                .build()
        )
        StrictMode.setVmPolicy(
            StrictMode.VmPolicy.Builder()
                .detectLeakedSqlLiteObjects()
                .detectLeakedClosableObjects()
                .penaltyLog()
                .penaltyDeath()
                .build()
        )
```

**Comment by arnaudgiuliani** [comment]
let's reopen if you can reproduce
