### ISSUE TITLE
 No compatible definition found for type 'Context'. Check your module definition

### ISSUE THREAD

**Issue by arekz-mj** [InsertKoinIO/koin#232]
**Describe the bug**
When call androidContext() app crash with error message:

> Error while resolving instance for class 'android.content.Context' - error: org.koin.error.NoBeanDefFoundException: No compatible definition found for type 'Context'. Check your module definition 

**To Reproduce**
1. Setup new project from android studio.
2. Add dependencies:
```
    compile 'org.koin:koin-core:1.0.0'
    compile 'org.koin:koin-android:1.0.0'
```
3. Start Koin in App class:
```
import android.app.Application
import android.content.Context
import org.koin.android.ext.android.startKoin
import org.koin.android.ext.koin.androidApplication
import org.koin.dsl.module.module

class App : Application() {

    override fun onCreate() {
        super.onCreate()
        startKoin(this, listOf(M))
    }
}
```
4. Define module:
val M = module {
    val ctx = androidApplication()
}

5. app crash on start with:

```
W/System: ClassLoader referenced unknown path: /data/app/net.dummpyapp.testingkoin-2/lib/arm64
I/InstantRun: starting instant run server: is main process
V/InstantRun: Starting server socket listening for package net.dummpyapp.testingkoin on android.net.LocalSocketAddress@af74a1d
V/InstantRun: Started server for package net.dummpyapp.testingkoin
D/App: onCreate()
I/KOIN: [context] create
E/KOIN: [ERROR] - Error while resolving instance for class 'android.app.Application' - error: org.koin.error.NoBeanDefFoundException: No compatible definition found for type 'Application'. Check your module definition 
D/AndroidRuntime: Shutting down VM
    
    
    --------- beginning of crash
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: net.dummpyapp.testingkoin, PID: 28387
    java.lang.RuntimeException: Unable to create application net.dummpyapp.testingkoin.App: org.koin.error.NoBeanDefFoundException: No compatible definition found for type 'Application'. Check your module definition
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5584)
        at android.app.ActivityThread.-wrap2(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1596)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6316)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
     Caused by: org.koin.error.NoBeanDefFoundException: No compatible definition found for type 'Application'. Check your module definition
        at org.koin.core.bean.BeanRegistry.retrieveDefinition(BeanRegistry.kt:113)
        at org.koin.core.instance.InstanceRegistry$proceedResolution$$inlined$synchronized$lambda$1.invoke(InstanceRegistry.kt:87)
        at org.koin.core.instance.InstanceRegistry$proceedResolution$$inlined$synchronized$lambda$1.invoke(InstanceRegistry.kt:36)
        at org.koin.core.time.DurationKt.measureDuration(Duration.kt:8)
        at org.koin.core.instance.InstanceRegistry.proceedResolution(InstanceRegistry.kt:84)
        at org.koin.core.instance.InstanceRegistry.resolve(InstanceRegistry.kt:63)
        at org.koin.core.instance.InstanceRegistry.resolve$default(InstanceRegistry.kt:48)
        at org.koin.android.ext.koin.ContextExtKt.androidApplication(ContextExt.kt:56)
        at net.dummpyapp.testingkoin.AppKt$M$1.invoke(App.kt:27)
        at net.dummpyapp.testingkoin.AppKt$M$1.invoke(App.kt)
        at org.koin.dsl.module.ModuleKt$module$1.invoke(Module.kt:52)
        at org.koin.dsl.module.ModuleKt$module$1.invoke(Module.kt)
        at org.koin.core.Koin$build$duration$1.invoke(Koin.kt:82)
        at org.koin.core.Koin$build$duration$1.invoke(Koin.kt:34)
        at org.koin.core.time.DurationKt.measureDuration(Duration.kt:8)
        at org.koin.core.Koin.build(Koin.kt:80)
        at org.koin.standalone.StandAloneContext.loadKoinModules(StandAloneContext.kt:58)
        at org.koin.standalone.StandAloneContext.loadKoinModules(StandAloneContext.kt:67)
        at org.koin.android.ext.android.ComponentCallbacksExtKt.startKoin(ComponentCallbacksExt.kt:60)
        at org.koin.android.ext.android.ComponentCallbacksExtKt.startKoin$default(ComponentCallbacksExt.kt:56)
        at net.dummpyapp.testingkoin.App.onCreate(App.kt:15)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1025)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5581)
        at android.app.ActivityThread.-wrap2(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1596) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6316) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762) 

```

**Expected behavior**
App shouldn't crash and method androidContext() should provide android context

**Koin project used and used version (please complete the following information):**
 [e.g]: `koin-core version 1.0.0`

**Additional moduleDefinition**
No.

**Comment by luna-vulpo** [comment]
because of respond here: https://github.com/InsertKoinIO/koin/issues/190

**Comment by arnaudgiuliani** [comment]
you are not defining anything in your module?!

**Comment by luna-vulpo** [comment]
I have but at this point app crashes so I extract smallest crashing example.

**Comment by luna-vulpo** [comment]
I solve it by 

`val ctx by lazy{ androidApplication() }`

**Comment by scottkruse** [comment]
Im having a similar issue as this in version 1.0.2

**Comment by IgorGanapolsky** [comment]
Just to confirm, we can declare
`val ctx by lazy{ androidApplication() }` at the top of the **module**, and it will work?
