### ISSUE TITLE
Can't getByClass ViewModel 'viewmodel' on 'activity' Is not a FragmentActivity nor a Fragment neither a valid ViewModelStoreOwner

### ISSUE THREAD

**Issue by benjaminledet** [InsertKoinIO/koin#255]
**Describe the bug**
I just update from koin 0.9.3 to 1.0.1 and I'm getting 
```
Can't getByClass ViewModel 'class ui.viewmodels.SplashScreenViewModel' on ui.activities.SplashScreenActivity@b04039c - Is not a FragmentActivity nor a Fragment neither a valid ViewModelStoreOwner
        at org.koin.android.viewmodel.ext.android.LifecycleOwnerExtKt.getViewModelByClass(LifecycleOwnerExt.kt:98)
        at org.koin.android.viewmodel.ext.android.LifecycleOwnerExtKt$viewModelByClass$1.invoke(LifecycleOwnerExt.kt:64)
        at org.koin.android.viewmodel.ext.android.LifecycleOwnerExtKt$viewModelByClass$1.invoke(LifecycleOwnerExt.kt)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at .ui.activities.SplashScreenActivity.getViewModel(SplashScreenActivity.kt:0)
        at ui.activities.SplashScreenActivity.onCreate(SplashScreenActivity.kt:74)
```
**Koin project used and used version (please complete the following information):**
 ```
    koin_version = "1.0.1"
    implementation "org.koin:koin-android:$koin_version"
    implementation "org.koin:koin-androidx-scope:$koin_version"
    implementation "org.koin:koin-androidx-viewmodel:$koin_version"
```

**Additional moduleDefinition**

 ```
val viewModule = module {
    // SplashScreen
    viewModel { SplashScreenViewModel(androidApplication(), get(), get(), get(), get(), get()) }

    // MainActivity
    viewModel { MainActivityViewModel()}
}
 ```
 ```
class SplashScreenActivity : AppCompatActivity() {
    private val viewModel by viewModel<SplashScreenViewModel>()
}
 ```

**Comment by fredy-mederos** [comment]
Check if your ```AppCompatActivity``` parent implements ```androidx.lifecycle.ViewModelStoreOwner```. That is the one required to access the ```ViewModelProvider```

**Comment by benjaminledet** [comment]
Indeed, the class was not refactored with Androidx. I should have seen that...
Thank you!

**Comment by benjaminledet** [comment]
Oh sorry, I made a mistake in my post, I do not use androidx, I'm using : 
```
   koin_version = "1.0.1"
   implementation "org.koin:koin-android:$koin_version"
   implementation "org.koin:koin-android-scope:$koin_version"
   implementation "org.koin:koin-android-viewmodel:$koin_version"
```

So my AppCompatActivity comes from `android.support.v7.app`

**Comment by benjaminledet** [comment]
Ok I think I've figured out. The viewModelStore implementation was added in the 27.1.0 support version but we are using the 26.1.0 so obviously it can't work.
So we have to use this minimum version "27.1.0" to use Koin 1.0.1 ? Is it wrote somewhere in your documentation? Because I didn't saw it.

**Comment by fredy-mederos** [comment]
The problem isn't with koin, is with ViewModels so if you want to use ViewModels you need to set the support version from 27.1.0
Regards
