### ISSUE TITLE
startKoin reuse the previous context (Koin 2.0)

### ISSUE THREAD

**Issue by jcornaz** [InsertKoinIO/koin#327]
Please consider the following code:

```kotlin
val module = module {
    single { "hello" }
}

fun main() {
    startKoin {
        modules(module)
    }
    stopKoin()

    startKoin {
        modules(module)
    }
    stopKoin()
}
```

The second `koinStart` fails with:
```
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.intellij.rt.execution.CommandLineWrapper.main(CommandLineWrapper.java:67)
Caused by: org.koin.core.error.DefinitionOverrideException: Already existing definition or try to override an existing one: [type:Single,class:'java.lang.String']
	at org.koin.core.registry.BeanRegistry.addDefinition(BeanRegistry.kt:91)
	at org.koin.core.registry.BeanRegistry.saveDefinition(BeanRegistry.kt:73)
	at org.koin.core.registry.BeanRegistry.saveDefinitions(BeanRegistry.kt:58)
	at org.koin.core.registry.BeanRegistry.loadModules(BeanRegistry.kt:49)
	at org.koin.core.KoinApplication$modules$duration$1.invoke(KoinApplication.kt:52)
	at org.koin.core.KoinApplication$modules$duration$1.invoke(KoinApplication.kt:33)
	at org.koin.core.time.MeasureKt.measureDurationOnly(Measure.kt:28)
	at org.koin.core.KoinApplication.modules(KoinApplication.kt:50)
	at org.koin.core.KoinApplication.modules(KoinApplication.kt:42)
```

**To Reproduce**
1. Use Koin 2.0.0-alpha-5
2. Write the code snippet above
3. Run the `main` function

**Expected behavior**
If `startKoin` is called after `stopKoin` should start a completly isolated context, agnostic of previous usages of Koin. Therefore the code snippet above should not throw any exception.

It is very important in automated tests, were we should be able to start new conext before each test function.

**Koin project used and used version (please complete the following information):**
`koin-core` version `2.0.0-alpha-5`

**Comment by arnaudgiuliani** [comment]
check `2.0.0-alpha6` for last fix 👍

**Comment by arnaudgiuliani** [comment]
hope to release it during January. Doc is in progress 👍

**Comment by jcornaz** [comment]
>hope to release it during January. Doc is in progress 👍

Great.

But you are talking about `2.0.0` right? My question was about `2.0.0-alpha6` which you said would fix this problem. But it is not yet released: https://jcenter.bintray.com/org/koin/koin-logger-slf4j/

**Comment by arnaudgiuliani** [comment]
yeah ... sorry :/

**Comment by arnaudgiuliani** [comment]
will release it :)
