### ISSUE TITLE
StrictMode violation by startKoin() on Android with Koin 1.0.2

### ISSUE THREAD

**Issue by AlbertVilaCalvo** [InsertKoinIO/koin#350]
**Describe the bug**
StrictMode violation happens on Android with Koin 1.0.2. due to read from disk.

**To Reproduce**
Add this to `Application#onCreate()`:
```
StrictMode.setThreadPolicy(
    StrictMode.ThreadPolicy.Builder()
        .detectAll()
        .penaltyLog()
        .penaltyDeath()
        .build()
)

startKoin(this,
    modules = listOf(appModule, networkModule, mainModule, loginModule),
    logger = if (BuildConfig.DEBUG) AndroidLogger() else EmptyLogger())
```

Note: I've already tried to set `loadPropertiesFromFile = false` (as explained in #96) but `false` is the default value now and hence it does fix the violation.

**Expected behavior**
Ideally it shouldn't block the main thread.

**Koin project used and used version (please complete the following information)**
`koin-android version 1.0.2 `

**Stacktrace**
```
java.lang.RuntimeException: StrictMode ThreadPolicy violation
    at android.os.StrictMode$AndroidBlockGuardPolicy.onThreadPolicyViolation(StrictMode.java:1705)
    at android.os.StrictMode$AndroidBlockGuardPolicy.lambda$handleViolationWithTimingAttempt$0(StrictMode.java:1619)
    at android.os.-$$Lambda$StrictMode$AndroidBlockGuardPolicy$9nBulCQKaMajrWr41SB7f7YRT1I.run(Unknown Source:6)
    at android.os.Handler.handleCallback(Handler.java:873)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:193)
    at android.app.ActivityThread.main(ActivityThread.java:6863)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
  Caused by: android.os.strictmode.DiskReadViolation
    at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1504)
    at java.io.UnixFileSystem.getBooleanAttributes(UnixFileSystem.java:241)
    at java.io.File.isDirectory(File.java:1198)
    at dalvik.system.DexPathList$Element.toString(DexPathList.java:695)
    at java.lang.String.valueOf(String.java:2896)
    at java.util.Arrays.toString(Arrays.java:4511)
    at dalvik.system.DexPathList.toString(DexPathList.java:201)
    at java.lang.String.valueOf(String.java:2896)
    at java.lang.StringBuilder.append(StringBuilder.java:132)
    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:169)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
    at java.lang.Class.classForName(Native Method)
    at java.lang.Class.forName(Class.java:453)
    at java.lang.Class.forName(Class.java:378)
    at kotlin.jvm.internal.Reflection.<clinit>(Reflection.java:22)
    at kotlin.jvm.internal.Reflection.getOrCreateKotlinClass(Reflection.java:50)
    at com.example.AppModuleKt$appModule$1.invoke(AppModule.kt:74)
    at com.example.AppModuleKt$appModule$1.invoke(Unknown Source:2)
    at org.koin.dsl.module.ModuleKt$module$1.invoke(Module.kt:53)
    at org.koin.dsl.module.ModuleKt$module$1.invoke(Unknown Source:2)
    at org.koin.core.Koin$loadModules$duration$1.invoke(Koin.kt:112)
    at org.koin.core.Koin$loadModules$duration$1.invoke(Koin.kt:41)
    at org.koin.core.time.DurationKt.measureDuration(Duration.kt:19)
    at org.koin.core.Koin.loadModules(Koin.kt:110)
    at org.koin.standalone.StandAloneContext.getOrCreateMinimalKoin(StandAloneContext.kt:130)
    at org.koin.standalone.StandAloneContext.loadKoinModules(StandAloneContext.kt:112)
    at org.koin.standalone.StandAloneContext.loadKoinModules(StandAloneContext.kt:121)
    at org.koin.android.ext.android.ComponentCallbacksExtKt.startKoin(ComponentCallbacksExt.kt:58)
    at org.koin.android.ext.android.ComponentCallbacksExtKt.startKoin$default(ComponentCallbacksExt.kt:54)
    at com.example.App.onCreate(App.kt:55)
    at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1165)
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6039)
    at android.app.ActivityThread.access$1300(ActivityThread.java:207)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1748)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:193) 
    at android.app.ActivityThread.main(ActivityThread.java:6863) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
```

**Comment by arnaudgiuliani** [comment]
let me take a look 👍

**Comment by arnaudgiuliani** [comment]
Kotlin reified type trigger this 'disk read violation'. I have to understand better the situation:

```
at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:169)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
    at java.lang.Class.classForName(Native Method)
    at java.lang.Class.forName(Class.java:453)
    at java.lang.Class.forName(Class.java:378)
    at kotlin.jvm.internal.Reflection.<clinit>(Reflection.java:22)
    at kotlin.jvm.internal.Reflection.getOrCreateKotlinClass(Reflection.java:50)
```
