### ISSUE TITLE
Get “org.koin.error.BeanOverrideException” error on reopen the app

### ISSUE THREAD

**Issue by AlirezaMH** [InsertKoinIO/koin#360]
I'm using Koin on a [modular application][1] by following [documentation][2] of that.
I call `startKoin` on my `BaseApplication` on the Core-Module:

***Application***

    val myModule = module {
        factory { MyClass(androidContext()) }
    }

    override fun onCreate() {
        super.onCreate()
        startKoin(this, listOf(myModule))
    }

And load some other modules in other modules by `loadKoinModules`:

    loadKoinModules(otherModules)

All things are ok on first run, but when I reopen the application, I'm getting this error:

    com.example.app E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.app, PID: 8252
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.app/com.example.app.MainActivity}: org.koin.error.BeanOverrideException: Try to override definition with Factory [name='MyClass',class='com.example.module.MyClass'], but override is not allowed. Use 'override' option in your definition or module.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2957)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

  [1]: https://medium.com/google-developer-experts/modularizing-android-applications-9e2d18f244a0
  [2]: https://insert-koin.io/docs/1.0/getting-started/android/

Is there any way to destroy Koin or any other way to solving this problem?

**Koin project used and used version:**
`koin-core version 1.0.2`
`koin-android-viewmodel version 1.0.2`

**Comment by arnaudgiuliani** [comment]
`stopKoin()` to stop everything, or allow override things if needed.
