### ISSUE TITLE
Try starting Koin again, even though it's already started.

### ISSUE THREAD

**Issue by AhmadSamhan0** [InsertKoinIO/koin#385]
**Describe the bug**
When using StartKoin and exit from my app or kill, after that open the app again, this crash as the following : 
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: app.beamuae.pyshicalstoreapp, PID: 16629
    java.lang.RuntimeException: Unable to start activity ComponentInfo{app.beamuae.pyshicalstoreapp/app.beamuae.pyshicalstoreapp.MainActivity}: org.koin.error.AlreadyStartedException: **Koin is already started. Run startKoin only once or use loadKoinModules**
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2927)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2988)
        at android.app.ActivityThread.-wrap14(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1631)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6682)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
     Caused by: org.koin.error.AlreadyStartedException: Koin is already started. Run startKoin only once or use loadKoinModules
        at org.koin.standalone.StandAloneContext.startKoin(StandAloneContext.kt:55)
        at org.koin.standalone.StandAloneContext.startKoin$default(StandAloneContext.kt:52)
        at app.beamuae.physicalstore.internal.PSSdkImpl.initialize(PSSdkImpl.kt:53)
        at app.beamuae.pyshicalstoreapp.MainActivity.onCreate(MainActivity.kt:39)
        at android.app.Activity.performCreate(Activity.java:6942)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2880)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2988) 
        at android.app.ActivityThread.-wrap14(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1631) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6682) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410) 

I use startKoin(........) and it is import from import org.koin.standalone.StandAloneContext.**startKoin** 

**Koin project used and used version:**
  `org.koin:koin-android:1.0.2`

**Comment by AhmadSamhan0** [comment]
@arnaudgiuliani  please can you check this issue?

**Comment by erickok** [comment]
It's not very friendly to push people just because you have a question. Having said that, your description is not very complete. Where do you call startKoin? I think the error is quite clear; you try to start Koin again, even though you already started it.

**Comment by AhmadSamhan0** [comment]
> It's not very friendly to push people just because you have a question. Having said that, your description is not very complete. Where do you call start Koin? I think the error is quite clear; you try to start Koin again, even though you already started it.

@erickok Thanks for your note, I update this ticket again with my error text, 
so yes when I try to start koin again, already started, how can fix it?

**Comment by erickok** [comment]
You are starting from `MainActivity.onCreate()`. I suggest you start Koin in your Application instance instead.

You may see the Koin exmple projects for multiple examples of this. such as https://github.com/InsertKoinIO/koin/blob/master/koin-projects/examples/android-mvp/src/main/kotlin/fr/ekito/myweatherapp/MainApplication.kt (for Koin 2.x) or https://github.com/InsertKoinIO/koin/blob/1.0.2/koin-projects/examples/android-mvp/src/main/kotlin/fr/ekito/myweatherapp/MainApplication.kt (Koin 1.x).

**Comment by AhmadSamhan0** [comment]
@erickok ok, It should be inside Application class. Because the application can lose state and start over the Activities. But application class never lose its state. right ??

and koin 2 still on beta version ??

**Comment by erickok** [comment]
Yes, Koin 2 is in beta.

This is Android-specific and not Koin-specific but yes, there is only one instance of you Application class as long as your app process is alive. But your Activity would be recreated every time.

**Comment by AhmadSamhan0** [comment]
Perfect, Do you recommend using a Beta version of my SDK or still on version 1.0.2?


And if this issue on Android ,  how can I implement my application class on my local SDK? please advice.

**Comment by erickok** [comment]
If you are building an SDK, then typiclal you create a single init function that you ask the developer to call once (who will do so in his/her Application class). Also, in an SDK/library you don't want to use the SingletonScope as that would interfere with the implementing app who already uses Koin. 

Personally I (we) use the 2.0 beta but that's a decision for everyone to make themselves.
