### ISSUE TITLE
NoBeanDefFoundException when using multiple KoinApplication & global scope

### ISSUE THREAD

**Issue by kingori** [InsertKoinIO/koin#410]
**Describe the bug**
If I create multiple KoinApplication, koin module failed to inject constructor agruments and throws NoBeanDefFoundException.

**To Reproduce**
Test case below failed. I've run it with koin 2.0.0-beta-4

```kotlin
  @Test
    fun `create multiple context without named qualifier`() {
        val koinA = koinApplication {
            modules(module {
                single { ModelA() }
            }, module {
                single { ModelB(get()) }
            })
        }

        val koinB = koinApplication {
            modules(module {
                single { ModelC() }
            })
        }


        koinA.koin.get<ModelA>().let {
            Assert.assertNotNull(it)
        }

        koinA.koin.get<ModelB>().let {
            Assert.assertNotNull(it)
        }
    }

    class ModelA

    class ModelB(a: ModelA)

    class ModelC
```

If I run this test, I got exception like below.
```
org.koin.core.error.InstanceCreationException: Could not create instance for [type:Single,class:'com.KoinTest.ModelB']

	at org.koin.core.instance.DefinitionInstance.create(DefinitionInstance.kt:63)
	at org.koin.core.instance.SingleDefinitionInstance.get(SingleDefinitionInstance.kt:40)
	at org.koin.core.definition.BeanDefinition.resolveInstance(BeanDefinition.kt:74)
	at org.koin.core.Koin.resolve(Koin.kt:110)
	at org.koin.core.Koin.get(Koin.kt:98)
	at com.KoinTest.create multiple context without named qualifier(KoinTest.kt:146)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: org.koin.core.error.NoBeanDefFoundException: No definition found for 'com.KoinTest.ModelA' has been found. Check your module definitions.
	at org.koin.core.Koin.prepareResolution(Koin.kt:119)
	at org.koin.core.Koin.resolve(Koin.kt:108)
	at org.koin.core.Koin.get(Koin.kt:98)
	at com.KoinTest$create multiple context without named qualifier$koinA$1$2$1.invoke(KoinTest.kt:122)
	at com.KoinTest$create multiple context without named qualifier$koinA$1$2$1.invoke(KoinTest.kt:9)
	at org.koin.core.instance.DefinitionInstance.create(DefinitionInstance.kt:56)
	... 27 more
```

**Expected behavior**
Test should run successfully.

**Koin project used and used version (please complete the following information):**
'koin 2.0.0-beta-4'

I think `Scope.GLOBAL` causes this problem. When I create second KoinApplication, 
`KoinApplication.loadDefaults()` register itself to koin of `Scope.GLOBAL`.

When `get()` called inside module, `InstanceContext.getDefinitionContext()` is called. So last created KoinApplication is returned, and bean definition is not found. In my test case, InstanceContext search ModelA definition from koinB, not koinA.

I think Scope.GLOBAL should be created and managed by each KoinApplication, not global companion object field.

**Comment by arnaudgiuliani** [comment]
yeah crazy bug O.o

let me check that

**Comment by arnaudgiuliani** [comment]
fixed in `rc-2`

Reopen it if any problem 👍
