### ISSUE TITLE
Crash --- No virtual method getRootScope() Received in Android Tests

### ISSUE THREAD

**Issue by CristianMG** [InsertKoinIO/koin#457]
I´m trying to write Android instrumentation tests with Koin and I received the next exception.
In application works correctly but it isn't working correctly in tests

```
java.lang.NoSuchMethodError: No virtual method getRootScope()Lorg/koin/core/scope/Scope; in class Lorg/koin/core/Koin; or its super classes (declaration of 'org.koin.core.Koin' appears in /data/app/com.cristianmg.sqldelight-ycLIafoSs9vE9bGirFutfA==/base.apk)
at com.cristianmg.sqldelight.data.cache.CharacterCacheTest$$special$$inlined$inject$1.invoke(KoinTest.kt:50)
at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
at com.cristianmg.sqldelight.data.cache.CharacterCacheTest.getCache(Unknown Source:7)
at com.cristianmg.sqldelight.data.cache.CharacterCacheTest.testTest(CharacterCacheTest.kt:40)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at androidx.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:80)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at androidx.test.ext.junit.runners.AndroidJUnit4.run(AndroidJUnit4.java:104)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:388)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2082)
Tests ran to completion.
```

My dependencies install
```
    implementation "org.koin:koin-androidx-scope:2.0.0-GA6"
    implementation "org.koin:koin-androidx-viewmodel:2.0.0-GA6"
    testImplementation "org.koin:koin-test:2.0.0-GA6"
    androidTestImplementation "org.koin:koin-test:2.0.0-GA6"

```

My Application config

``` startKoin {
            // declare used Android context
            androidLogger()
            androidContext(this@App)
            modules(AppKoinModules.getModules())
        }
```
My test
```
@RunWith(AndroidJUnit4::class)
class CharacterCacheTest : KoinTest {
    val cache: CharacterCache by inject()
    @Before
    fun before() {
        //loadKoinModules(cacheModule)
    }
    @Test
    fun testTest() {
        cache.characters().test().assertComplete()
    }
}
```

Any idea for putting me on the way?

Greetings

**Comment by CristianMG** [comment]
I add the core library and work correctly

**Comment by HosoShak** [comment]
Hi. I have same problem and can't fix, can you help me??

**Comment by Maendrad** [comment]
Hello @HosoShak, I had this issue, I was my koin-android-viewmodel library who was not updated.
If you use the "3.0.1-alpha-3" version for koin-android and koin-core, you need to update the koin-android-viewmodel to "2.2.2" (the 2.1.0 version make this error with 3.0.1-alpha-3 for the rest).
I hope my solution can help you.
