### ISSUE TITLE
Proguard obfuscation and Koin's viewmodel injection doesn't work

### ISSUE THREAD

**Issue by leventepal** [InsertKoinIO/koin#499]
**Describe the bug**
Proguard obfuscation and koin exception is being thrown:

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.school/com.school.splash.SplashActivity}: h.c.c.c.c: Could not create instance for [type:Factory,primary_type:'i.a.a.t.e']
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2927)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2988)
        at android.app.ActivityThread.-wrap14(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1631)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6682)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
```

**To Reproduce**
1. Create the activity and View Model
```
import org.koin.androidx.viewmodel.ext.android.viewModel

class SplashActivity : BaseActivity<SplashViewModel>() {

    override val viewModel: SplashViewModel by viewModel()
```

2. Declare module in Koin
```
val splashModule = module {
    viewModel { SplashViewModel() }
}

startKoin {
            androidLogger()
            androidContext(instance)
            modules(listOf(splashModule))
        }
```

3. Run the signed app with proguard activated and note that the exception above will be thrown

**Expected behavior**
The app shouldn't crash and the obfuscation should work.

**Koin project used and used version (please complete the following information):**
implementation "org.koin:koin-android:2.0.1"
implementation "org.koin:koin-androidx-scope:2.0.1"
implementation "org.koin:koin-androidx-viewmodel:2.0.1"

**Additional moduleDefinition**
If I add the following proguard rule `-keep class com.school.splash.SplashViewModel { *; }` the app won't crash, but the class won't be obfuscated.
The really interesting part is, I have other 20+ ViewModels and without adding the proguard rule they are all working with Koin. Only the `SplashViewModel` class can't be instantiated.

```
class SplashViewModel : BaseActivityViewModel() {
}
```

```
class SplashActivity : BaseActivity<SplashViewModel>() {

    override val viewModel: SplashViewModel by viewModel()
}
```

Why only the "SplashViewModel" can't be instantiated, and the other 20+ ViewModels can?

**Comment by Sowmya-Flickr** [comment]
@leventepal, I am facing a similar issue. Request you to share how the issue was resolved.
