### ISSUE TITLE
In Android instrumented tests a call to checkModules cause successive injections to fail

### ISSUE THREAD

**Issue by kklorenzotesta** [InsertKoinIO/koin#541]
**Describe the bug**
If I call `checkModules()` on a `koinApplication { ... }` reusing the same modules of the global `startKoin { ... }` then any successive injection from the global instance will throw `java.lang.IllegalStateException: Definition without any InstanceContext`. This prevents me from testing the modules on android while running the instrumented test.

Full stacktrace:
```

java.lang.IllegalStateException: Definition without any InstanceContext - [type:Single,primary_type:'com.example.koinbug.A']
at org.koin.core.definition.BeanDefinition.resolveInstance(BeanDefinition.kt:71)
at org.koin.core.scope.Scope.resolveInstance(Scope.kt:165)
at org.koin.core.scope.Scope.get(Scope.kt:128)
at com.example.koinbug.MainActivity$$special$$inlined$inject$1.invoke(ComponentCallbackExt.kt:51)
at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
at com.example.koinbug.MainActivity.getA(Unknown Source:7)
at com.example.koinbug.MainActivity.onCreate(MainActivity.kt:13)
at android.app.Activity.performCreate(Activity.java:7136)
at android.app.Activity.performCreate(Activity.java:7127)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
at androidx.test.runner.MonitoringInstrumentation.callActivityOnCreate(MonitoringInstrumentation.java:674)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2908)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3063)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1823)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loop(Looper.java:198)
at android.app.ActivityThread.main(ActivityThread.java:6729)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**To Reproduce**
*Minimal reproduction of the bug:*
in this example [repository](https://github.com/kklorenzotesta/KoinBug):
Koin is started in the Application, so is started before running the instrumented tests. In a test the same module is checked with
```
koinApplication {
    androidContext(context)
    modules(modules)
}.checkModules()
```
the following test tries to start an activity which inject a bean from the module, but fails with an exception.
*Steps to reproduce the behavior:*
1. Run the instrumented tests all togheter

**Expected behavior**
Modules should be shareable between koin instances, otherwise I think is impossible to call `checkModules`  in instrumented tests

**Koin project used and used version (please complete the following information):**
  `koin-core version 2.0.1`
  `koin-android version 2.0.1`

**Comment by erickok** [comment]
I would also recommend running the `checkModules` test as JVM test instead of instrumented test. Not only is this much, much faster, you also prevent some issues like this. What happens is that with an instrumented test your Application might get started and with that probably you are starting Koin already.

**Comment by arnaudgiuliani** [comment]
Hello, `checkModules` is just here for verification purpose. To exclude from any test case then, other than the one to run module verification.
