### ISSUE TITLE
Can't get defenition for manually added one

### ISSUE THREAD

**Issue by niihelium** [InsertKoinIO/koin#555]
I have declared modules and started Koin in Application class. Then launched my root activity and trying to add another definition manually. When comes time to inject this object - app crashes. How can I perform action like this?
```kotlin
//MainActivity.onCreate()
val newObject = createNewObject(this)
GlobalContext.get().register(newObject)
```

```kotlin
fun KoinApplication.register(newObject: SomeClass) {
    koin.beanRegistry.saveDefinition(DefinitionFactory.createSingle { newObject })
}
```
Then in ViewModel:
```kotlin
class MainViewModel(private val newObject: SomeClass)
```
```kotlin
val appModule = module {
            viewModel { MainViewModel(get()) }
        }
```

```
Caused by: org.koin.core.error.NoBeanDefFoundException: No definition found for 'com.company.app.SomeClass' has been found. Check your module definitions.
        at org.koin.core.Koin.prepareResolution(Koin.kt:117)
        at org.koin.core.Koin.resolve(Koin.kt:107)
        at org.koin.core.Koin.access$resolve(Koin.kt:41)
        at org.koin.core.Koin$get$$inlined$synchronized$lambda$1.invoke(Koin.kt:92)
        at org.koin.core.time.MeasureKt.measureDuration(Measure.kt:37)
        at org.koin.core.Koin.get(Koin.kt:91)
        at com.company.app.AppModuleKt$appmodules$1$2.invoke(AppModule.kt:79)
        at com.company.app.AppModuleKt$appmodules$1$2.invoke(Unknown Source:4)
        at org.koin.core.instance.DefinitionInstance.create(DefinitionInstance.kt:54)
```

So question is - how can I perform this action correctly?

**Comment by arnaudgiuliani** [comment]
The declare function of your `Koin` instance is doing it for you:

```
/**
     * Declare a component definition from the given instance
     * This result of declaring a single definition of type T, returning the given instance
     *
     * @param instance The instance you're declaring.
     * @param qualifier Qualifier for this declaration
     * @param secondaryTypes List of secondary bound types
     * @param override Allows to override a previous declaration of the same type (default to false).
     */
    inline fun <reified T> declare(
            instance: T,
            qualifier: Qualifier? = null,
            secondaryTypes: List<KClass<*>>? = null,
            override: Boolean = false
    ) {
        rootScope.declare(instance, qualifier, secondaryTypes, override)
    }
```
