### ISSUE TITLE
Clearing scope 

### ISSUE THREAD

**Issue by pollux-** [InsertKoinIO/koin#609]
**Describe the bug**
The scope is not getting cleared after calling 

val scope = getKoin().getScope("sessionID")
        scope.close()

**Modules and dependencies**

implementation 'org.koin:koin-android-scope:2.0.1'
 implementation "org.koin:koin-core:2.0.1"

```
val appModule = module {
    scope(named("session")){
        scoped { Session() }
    }

    single { SessionRepositoryImpl(getScope("sessionID").get()) as SessionRepository }
    single { SessionPresenter(get()) }
}

```

```
class SessionPresenter(val repo: SessionRepository) : KoinComponent {

    fun getSession() = repo.getSession()

    fun clearSession(){
        val scope = getKoin().getScope("sessionID")
        scope.close()
        getKoin().deleteScope("sessionID")
    }

}
```

```
class SessionRepositoryImpl(private val session: Session) : SessionRepository {
    override fun getSession() = session.getToken()
}

```

```
class Session {
    fun getToken(): String {
        return "My Token  $this"
    }
}

```

```
class MainActivity : AppCompatActivity() {

    private val sessionPresenter: SessionPresenter by inject()

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        getKoin().createScope("sessionID", named("session"))
        sessionPresenter.getSession()
        Log.d("TEST", "Token " + sessionPresenter.getSession())
        sessionPresenter.clearSession()
        sessionPresenter.getSession()
        Log.d("TEST", "Token " + sessionPresenter.getSession())


        clickMe.setOnClickListener {
            startActivity(Intent(baseContext, TestActivity::class.java))
        }
    }
}
```

Session instance remains the same even after calling clear? What is missing here. 

Can someone help me with this? 

2019-10-12 14:12:27.646 17700-17700/? D/TEST: Token My Token  com.koin.sample.Session@**377f1bd**
2019-10-12 14:12:27.646 17700-17700/? D/TEST: Token My Token  com.koin.sample.Session@**377f1bd**

**Comment by aschattney** [comment]
You have to retrieve the instance of the session lazily:
```kotlin
val appModule = module {
    ...
    single<SessionRepository> {
        val sessionProvider = { getScope("sessionID").get<Session>() }
        SessionRepositoryImpl(sessionProvider)
    }
    ...
}
```
And adjust the repository class accordingly. Each time getSession() is called, the sessionProvider will resolve the scope based on the id "sessionID" and resolves the session object:
```kotlin
class SessionRepositoryImpl(private val sessionProvider: () -> Session) : SessionRepository {
    override fun getSession() = sessionProvider().getToken()
}
```

**Comment by pollux-** [comment]
@aschattney  Thanks for sharing your thoughts. 

I end up having another issue:

I do have **getKoin().createScope("sessionID", named("session"))** in **MainActivity**



```
val appModule = module {
    scope(named("session")) {
        scoped { Session() }
    }

    single<SessionRepository> {
        val sessionProvider = { getScope("sessionID").get<Session>() }
        SessionRepositoryImpl(sessionProvider)
    }
    single { SessionPresenter(get()) }
}


```

2019-10-13 12:25:17.037 26456-26456/com.koin.sample E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.koin.sample, PID: 26456
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.koin.sample/com.koin.sample.MainActivity}: org.koin.core.error.ScopeNotCreatedException: ScopeInstance with id 'sessionID' not found. Create a scope instance with id 'sessionID'
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
     Caused by: org.koin.core.error.ScopeNotCreatedException: ScopeInstance with id 'sessionID' not found. Create a scope instance with id 'sessionID'
        at org.koin.core.registry.ScopeRegistry.getScopeInstance(ScopeRegistry.kt:130)
        at org.koin.core.Koin.getScope(Koin.kt:181)
        at org.koin.core.scope.Scope.getScope(Scope.kt:219)
        at com.koin.sample.AppmoduleKt$appModule$1$2$sessionProvider$1.invoke(appmodule.kt:13)
        at com.koin.sample.AppmoduleKt$appModule$1$2$sessionProvider$1.invoke(appmodule.kt)
        at com.koin.sample.SessionRepositoryImpl.getSession(SessionRepository.kt:8)
        at com.koin.sample.SessionPresenter.getSession(SessionPresenter.kt:7)
        at com.koin.sample.MainActivity.onCreate(MainActivity.kt:24)
        at android.app.Activity.performCreate(Activity.java:6679)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)

**Comment by olsisaqe** [comment]
Why not to do it like this: 

```
val appModule = module {
    scope(named("session")) {
        scoped { Session() }
    }

    single<SessionRepository> {
        val sessionProvider = { getKoin().getOrCreateScope("sessionID").get<Session>() }
        SessionRepositoryImpl(sessionProvider)
    }
    single { SessionPresenter(get()) }
}
```
