### ISSUE TITLE
Android Proguard No definition found

### ISSUE THREAD

**Issue by moeppe-sp** [InsertKoinIO/koin#632]
I´m using 2.0.1 version of Koin and in the debug version of the app everything works fine. However when using Proguard for a release build the app crashes with the following error:
```
org.koin.core.error.NoBeanDefFoundException: No definition found for 'io.reactivex.subjects.PublishSubject' has been found. Check your module definitions.
        at org.koin.core.scope.Scope.findDefinition(Scope.kt:3)
        at org.koin.core.scope.Scope.get(Scope.kt:7)
        at de.moeppe.uniplaner.ui.addEntry.AddEntryFragment$$special$$inlined$inject$1.invoke(ComponentCallbackExt.kt:4)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:6)
        at de.moeppe.uniplaner.ui.addEntry.AddEntryFragment$onViewCreated$8.onChanged(AddEntryFragment.kt:3)
        at androidx.lifecycle.LiveData.considerNotify(LiveData.java:6)
        at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:8)
        at androidx.lifecycle.LiveData.setValue(LiveData.java:4)
        at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:1)
        at de.moeppe.uniplaner.ui.addEntry.AddEntryViewModel$launchAddEvent$1.invokeSuspend(AddEntryViewModel.kt:9)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:13)
        at android.os.Handler.handleCallback(Handler.java:907)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
```

The module looks like this:
```android
val appModule = module {
    single(named("eventAddedSubject")) { PublishSubject.create<EventInformation>() }
    single(named("doneStateChangedSubject")) { PublishSubject.create<Event>() }
    viewModel { (weekdayId: Int) -> OverviewViewModel(weekdayId, get(named("eventAddedSubject")), get(named("doneStateChangedSubject"))) }
    viewModel { AddEntryViewModel() }
    viewModel { (eventId: Long) -> ToDoOverviewViewModel(eventId, get(named("doneStateChangedSubject"))) }
}
```

In the ProGuard-Rules I´ve explicitly declared to keep PublishSubject, however the same issue prevails. Are there any further steps needed when using the `named()` function?

**Comment by moeppe-sp** [comment]
After invalidating caches and clean rebuild everything worked fine again. Seems to be some caching error after changing the name of a `named()` function.
