### ISSUE TITLE
Attempt to invoke virtual method 'java.util.ArrayList org.koin.core.module.Module.getDefinitions$koin_core()' on a null object reference

### ISSUE THREAD

**Issue by byjaka** [InsertKoinIO/koin#668]
Hello I'm learning koin
AppModule.kt
```
object AppModule {
    val koinApp = koinApplication {
        printLogger(Level.DEBUG)
        modules(appModule)
    }
    val appModule = module(override = true) {


        viewModel { LoginViewModel() }
        viewModel { RegisterViewModel(get()) }
        single { PreferencesHelper.getInstance(androidApplication()) }

        single { createNetworkClient(BASE_URL, get()) }

        single { (get() as Retrofit).create(xxx::class.java) as xxx}

    }

    interface CustomKoinComponent : KoinComponent {
        override fun getKoin(): Koin = AppModule.koinApp.koin
    }

    class CustomService : CustomKoinComponent {
        val service: Service by inject()
    }
```

error message:
I encountered such an error
`java.lang.ExceptionInInitializerError
        at com.ttagrup.tta.AppModule$CustomKoinComponent$DefaultImpls.getKoin(AppModule.kt:38)
        at com.ttagrup.tta.ui.register.RegisterActivity.getKoin(RegisterActivity.kt:9)
        at org.koin.android.ext.android.ComponentCallbackExtKt.getKoin(ComponentCallbackExt.kt:14)
        at org.koin.android.viewmodel.ext.android.LifecycleOwnerExtKt.getKoin(LifecycleOwnerExt.kt:71)
        at org.koin.android.viewmodel.ext.android.LifecycleOwnerExtKt.getViewModel(LifecycleOwnerExt.kt:85)
        at com.ttagrup.tta.ui.register.RegisterActivity$$special$$inlined$viewModel$1.invoke(LifecycleOwnerExt.kt:95)
        at com.ttagrup.tta.ui.register.RegisterActivity$$special$$inlined$viewModel$1.invoke(Unknown Source:0)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at com.ttagrup.tta.ui.register.RegisterActivity.getRegisterViewModel(Unknown Source:7)
        at com.ttagrup.tta.ui.register.RegisterActivity.onCreate(RegisterActivity.kt:28)
        at android.app.Activity.performCreate(Activity.java:7802)
        at android.app.Activity.performCreate(Activity.java:7791)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.ArrayList org.koin.core.module.Module.getDefinitions$koin_core()' on a null object reference
        at org.koin.core.registry.BeanRegistry.saveDefinitions(BeanRegistry.kt:70)
        at org.koin.core.registry.BeanRegistry.loadModules(BeanRegistry.kt:49)
        at org.koin.core.KoinApplication.loadModulesAndScopes(KoinApplication.kt:66)
        at org.koin.core.KoinApplication.access$loadModulesAndScopes(KoinApplication.kt:31)
        at org.koin.core.KoinApplication$modules$duration$1.invoke(KoinApplication.kt:54)
        at org.koin.core.KoinApplication$modules$duration$1.invoke(KoinApplication.kt:31)
        at org.koin.core.time.MeasureKt.measureDurationOnly(Measure.kt:28)
        at org.koin.core.KoinApplication.modules(KoinApplication.kt:53)
        at org.koin.core.KoinApplication.modules(KoinApplication.kt:44)
        at com.ttagrup.tta.AppModule$koinApp$1.invoke(AppModule.kt:22)
        at com.ttagrup.tta.AppModule$koinApp$1.invoke(AppModule.kt:19)
        at org.koin.dsl.KoinApplicationKt.koinApplication(KoinApplication.kt:28)`

**Comment by jeziellago** [comment]
How the `startKoin` declared is? 
I recommend checking the documentation for more details that may help you. 
https://doc.insert-koin.io/#/koin-android/start.

**Comment by byjaka** [comment]
the link you provided solves my problem. he wanted appmodule in list in startcoin. solved my problem solved.
looking at koin's own documentation was more useful. There is a lot of information pollution on the Internet
thanks.
