### ISSUE TITLE
Using fragmentFactory with Navigation Component

### ISSUE THREAD

**Issue by seanwu1105** [InsertKoinIO/koin#691]
**Describe the bug**
App crashes when I try to inject dependencies via the fragment constructor with Koin `fragmentFactory` and JetPack navigation component.

**To Reproduce**
1. Use JetPack navigation component to create a "single-activity" app.
2. Create a fragment inside the navigation graph.
3. Inject any dependency into the fragment's constructor with Koin `fragmentFactory`.
4. App crashes when the navigation component tries to inflate the fragment. The following is the error log.

```
2020-01-08 15:02:30.459 27978-27978/com.example.koinfragmentfactoryissue E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.koinfragmentfactoryissue, PID: 27978
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.koinfragmentfactoryissue/com.example.koinfragmentfactoryissue.BaseActivity}: android.view.InflateException: Binary XML file line #22: Binary XML file line #22: Error inflating class fragment
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2781)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2859)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1592)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6518)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: android.view.InflateException: Binary XML file line #22: Binary XML file line #22: Error inflating class fragment
     Caused by: android.view.InflateException: Binary XML file line #22: Error inflating class fragment
     Caused by: org.koin.core.error.NoBeanDefFoundException: No definition found for class:'androidx.navigation.fragment.NavHostFragment'. Check your definitions!
        at org.koin.core.scope.Scope.throwDefinitionNotFound(Scope.kt:245)
        at org.koin.core.scope.Scope.resolveInstance(Scope.kt:219)
        at org.koin.core.scope.Scope.get(Scope.kt:176)
        at org.koin.core.Koin.get(Koin.kt:113)
        at org.koin.core.Koin.get$default(Koin.kt:112)
        at org.koin.androidx.fragment.android.KoinFragmentFactory.instantiate(KoinFragmentFactory.kt:16)
        at androidx.fragment.app.FragmentLayoutInflaterFactory.onCreateView(FragmentLayoutInflaterFactory.java:97)
        at androidx.fragment.app.FragmentController.onCreateView(FragmentController.java:135)
        at androidx.fragment.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java:356)
        at androidx.fragment.app.FragmentActivity.onCreateView(FragmentActivity.java:335)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:780)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:555)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:161)
        at com.example.koinfragmentfactoryissue.BaseActivity.onCreate(BaseActivity.kt:16)
        at android.app.Activity.performCreate(Activity.java:7023)
        at android.app.Activity.performCreate(Activity.java:7014)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1215)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2734)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2859)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1592)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6518)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

The following are some example codes.

``` kotlin
// BaseApplication.kt
class BaseApplication : Application() {
    val appModule = module {
        single { MyApi() }
        fragment { MainFragment(get()) }
    }
    override fun onCreate() {
        super.onCreate()
        startKoin {
            androidLogger()
            androidContext(this@BaseApplication)
            fragmentFactory()
            modules(appModule)
        }
    }
}
```

``` kotlin
// BaseActivity.kt
class BaseActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setupKoinFragmentFactory()
        setContentView(R.layout.activity_base)
        setSupportActionBar(toolbar)
        val navController = findNavController(R.id.nav_host_fragment)
        val appBarConfiguration = AppBarConfiguration(navController.graph)
        toolbar.setupWithNavController(navController, appBarConfiguration)
    }
}
```

``` kotlin
// MainFragment.kt
class MainFragment(private val myApi: MyApi) : Fragment() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        myApi.hello()
    }
    override fun onCreateView(
        inflater: LayoutInflater,
        container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? {
        return inflater.inflate(R.layout.fragment_main, container, false)
    }
}
```

``` kotlin
// MyApi.kt
private const val TAG = "MyApi"
class MyApi {
    fun hello() {
        Log.i(TAG, "hello")
    }
}
```

**Expected behavior**
The fragment should be successfully inflated with `MyApi` injected.

**Koin project used and used version (please complete the following information):**
`org.koin:koin-android:2.1.0-alpha-10`
`org.koin:koin-androidx-fragment:2.1.0-alpha-10`

**Comment by arnaudgiuliani** [comment]
Koin is looking for `NavHostFragment`:

```
Caused by: org.koin.core.error.NoBeanDefFoundException: No definition found for class:'androidx.navigation.fragment.NavHostFragment'
```

**Comment by seanwu1105** [comment]
Thanks for fast reply. Is there a clean way to get the NavHostFragment instance? I only find [this solution on StackOverflow](https://stackoverflow.com/questions/50884215/how-to-get-navhostfragment) but it seems to be a bit ugly.

**Comment by arnaudgiuliani** [comment]
nope, not really Koin related :)

**Comment by abjorck** [comment]
adding a `fragment { NavHostFragment() }` seems to help. is that not what it complains about?

**Comment by nikhil-thakkar** [comment]
@seanwu1105 Could you try calling ` setupKoinFragmentFactory()` before `super.onCreate(saveInstance)`?
And the same holds true if you don't use `Koin`. You have to set the `FragmentFactory` to `SupportFragmentManager` before calling `super.onCreate(saveInstance)`.

**Comment by seanwu1105** [comment]
@abjorck Yes, the building process is successful by adding `fragment { NavHostFragment() }` to the `appModule`. However, I am not sure how to get the instance of a specific navigation graph if an app contains multiple `NavHostFragment`s.

@nikhil-thakkar After adding `fragment { NavHostFragment() }` to the `appModule`, the app works fine no matter the order of `setupKoinFragmentFactory()` and `super.onCreate(saveInstance)` on my testing devices.
