### ISSUE TITLE
[FragmentFactory] Crash on restoreSaveState

### ISSUE THREAD

**Issue by shivanshs9** [InsertKoinIO/koin#695]
**Describe the bug**
App crashes when activity is reopened from recent tasks, calling onCreate of activity and restoring saved state of fragments.

**To Reproduce**
See error
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.checkin.app.checkin/com.checkin.app.checkin.restaurant.activities.PublicRestaurantProfileActivity}: org.koin.core.error.NoBeanDefFoundException: No definition found for class:'com.checkin.app.checkin.misc.fragments.NetworkBlockingFragment'. Check your definitions!
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5279)
        at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5187)
        at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: **org.koin.core.error.NoBeanDefFoundException: No definition found for class:'com.checkin.app.checkin.misc.fragments.NetworkBlockingFragment'. Check your definitions!**
        at org.koin.core.scope.Scope.throwDefinitionNotFound(Scope.kt:220)
        at org.koin.core.scope.Scope.resolveInstance(Scope.kt:194)
        at org.koin.core.scope.Scope.get(Scope.kt:178)
        at org.koin.core.scope.Scope.get$default(Scope.kt:167)
        at org.koin.androidx.fragment.android.KoinFragmentFactory.instantiate(KoinFragmentFactory.kt:15)
        at androidx.fragment.app.FragmentStateManager.<init>(FragmentStateManager.java:72)
        at androidx.fragment.app.FragmentManager.restoreSaveState(FragmentManager.java:2666)
        at androidx.fragment.app.FragmentController.restoreSaveState(FragmentController.java:196)
        at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:287)
        at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:106)
        at com.checkin.app.checkin.restaurant.activities.PublicRestaurantProfileActivity.onCreate(PublicRestaurantProfileActivity.kt:139)
        at android.app.Activity.performCreate(Activity.java:7803)
        at android.app.Activity.performCreate(Activity.java:7792)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409) 
        at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5279) 
        at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5187) 
        at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
```

**Expected behavior**
Working activity.

**Koin project used and used version (please complete the following information):**
 `koin version 2.1.0-alpha-8`

**Additional moduleDefinition**
```
val menuCartModule = module {
    scope<PublicRestaurantProfileActivity> {
        scoped { UserMenuGroupsFragment(ScheduledCartViewModel::class) }
    }
}

class PublicRestaurantProfileActivity: AppCompatActivity() {
	override fun onCreate(savedInstanceState: Bundle?) {
        setupKoinFragmentFactory(lifecycleScope)
        super.onCreate(savedInstanceState)
		setContentView(R.layout.activity_public_restaurant_profile)
		// ...
}
```

I also loaded KotlinFragmentFactory module in Application class. Only **UserMenuGroupsFragment** has a with-args constructor, but the crash happens when restoring state tries to  get fragments from koin fragment factory, even if they are no-arg constructors and aren't setup.

**Comment by arnaudgiuliani** [comment]
You need to declare the right component:

`NoBeanDefFoundException: No definition found for class:'com.checkin.app.checkin.misc.fragments.NetworkBlockingFragment'`

**Comment by shivanshs9** [comment]
NetworkBlockingFragment is a fragment with a no-arg constructor and I expected it to automatically be loaded directly by Android rather than koin. I explicitly declared the fragments which need to be provided by koin, since I hoped the others will be handled by android.

**Comment by arnaudgiuliani** [comment]
The fragment factory deals with Koin resolution, then all has to be declared

**Comment by shivanshs9** [comment]
I see... I thought if it's working initially when the activity is opened, the crash is a bug, not a mistake on my part.

**Comment by arnaudgiuliani** [comment]
no-arg constructor should be ok in 2.1.5
