### ISSUE TITLE
Crash when Activity that contains injected Fragments with parameters is being recreated

### ISSUE THREAD

**Issue by Sammekl** [InsertKoinIO/koin#705]
**Describe the bug**
When the Activity is being recreated which uses the Koin fragmentFactory and a Fragment which has constructor parameters, it crashes.

I've created a demo implementation of this crash here: 
https://github.com/Sammekl/koin-fragment-crash

**To Reproduce**
1. Enable 'Don't keep activities' in Android phones Developer options
2. Start app and click 'Go to next activity'
3. Press device back button or 'go back' button

**Expected behavior**
First Activtiy is rebuild and shown, but instead the application crashes

```
Caused by: org.koin.core.error.InstanceCreationException: Could not create instance for [Factory:'com.sammekleijn.koinfragmentcrash.main.MainFragment',scope:'com.sammekleijn.koinfragmentcrash.main.MainActivity']
        at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:59)
        at org.koin.core.instance.FactoryInstanceFactory.get(FactoryInstanceFactory.kt:36)
        at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:87)
        at org.koin.core.scope.Scope.resolveInstance(Scope.kt:217)
        at org.koin.core.scope.Scope.get(Scope.kt:203)
        at org.koin.core.scope.Scope.get$default(Scope.kt:192)
        at org.koin.androidx.fragment.android.KoinFragmentFactory.instantiate(KoinFragmentFactory.kt:15)
        at androidx.fragment.app.FragmentStateManager.<init>(FragmentStateManager.java:72)
        at androidx.fragment.app.FragmentManager.restoreSaveState(FragmentManager.java:2666)
        at androidx.fragment.app.FragmentController.restoreSaveState(FragmentController.java:196)
        at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:287)
        at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:106)
        at com.sammekleijn.koinfragmentcrash.main.MainActivity.onCreate(MainActivity.kt:17)
        at android.app.Activity.performCreate(Activity.java:7802)
        at android.app.Activity.performCreate(Activity.java:7791)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
     Caused by: org.koin.core.error.NoParameterFoundException: Can't get parameter value #0 from org.koin.core.parameter.DefinitionParameters@5117089
        at org.koin.core.parameter.DefinitionParameters.elementAt(DefinitionParameters.kt:31)
        at org.koin.core.parameter.DefinitionParameters.component1(DefinitionParameters.kt:33)
        at com.sammekleijn.koinfragmentcrash.koin.ModulesKt$fragmentModule$1$1$1.invoke(Unknown Source:11)
        at com.sammekleijn.koinfragmentcrash.koin.ModulesKt$fragmentModule$1$1$1.invoke(Unknown Source:4)
```

**Koin project used and used version (please complete the following information):**
2.1.0-alpha-10

**Temporary fix**
Add `savedInstanceState?.remove("android:support:fragments")` before `super.onCreate(savedInstanceState)` so that the fragment state is not maintained in the bundle

**Comment by arnaudgiuliani** [comment]
is it still here in 2.1.5?

**Comment by Sammekl** [comment]
Sorry, didn't see your message. Yes this is still an issue in 2.1.6. 

Haven't been able to upgrade to 2.2.0 yet

**Comment by KryptKode** [comment]
Has this been fixed now? On what version?

**Comment by arnaudgiuliani** [comment]
Can be a limitation, for now, recreating the Fragment from the factory can be tedious :/ I believe the activity is not sending parameters again.
