### ISSUE TITLE
[Gradle] Koin Gradle Plugin - check your modules 

### ISSUE THREAD

**Issue by arnaudgiuliani** [InsertKoinIO/koin#712]
Hi all,

while I'm looking at Arrow Meta to help leverage some tooling, what do you think of having a Gradle plugin to allow you to verify your Koin configuration via Gradle?

I would imagine something like this, in your gradle: 
```gradle
koin {
    modules = ["com.myapp.myModule1","com.myapp.myModule2"]
}
```

and having a task like `./gradlew checkKoinModules`

**Comment by kirich1409** [comment]
Why do you need to set modules in Gradle? I think to made checker using Android Lint that collect all dependencies from modules and then verify injections

**Comment by arnaudgiuliani** [comment]
It's not to set modules via Gradle, but more to describe what modules we are using in order to run a checkModules on it.

This is a to be agnostic as much as possible (not only Android then :) )

**Comment by kirich1409** [comment]
I meant that. It’s bad solution because most part of developer will forget to add new one, add refactored or anything else and analyze will be unuseful. The Gradle plugin during code analyse can found all declaration of Koin modules without explicit declaration

**Comment by arnaudgiuliani** [comment]
> The Gradle plugin during code analyse can found all declaration of Koin modules without explicit declaration

good idea!

**Comment by mqueiroz1995** [comment]
I totally agree with @kirich1409!

Also, I'm curious about how this would work? If the execution is similar to the one found in `checkModules()` it wouldn't be as straightforward as we are thinking because we would need to tell gradle how to create all the parameters of definitions with parameters.

I'm pretty sure it's out of the scope of this issue, but IMHO it would be better to improve `checkModules` making it search for all the required dependencies in it's graph and this would be enough to validate if the graph has all dependencies required for this creating the object, without actually having to instantiate it.

**Comment by erickok** [comment]
The original checkModules implementation did something like that but it gave false positives. A problem with most solutions is that you need to compile the code itself in order to check it, which is (from performance standpoint) a no-go. A linter could work but writing one that transitively checks all modules, with parameters and qualifiers, is going to be a challenge.

**Comment by arnaudgiuliani** [comment]
> A linter could work but writing one that transitively checks all modules, with parameters and qualifiers, is going to be a challenge.

that's why for now ... I don't have a real Gradle based solution

**Comment by arnaudgiuliani** [comment]
A good alternative is to use the JUnit Categories. I can have a `@Category(CheckModuleTest::class)` tag on a check module test:

```kotlin
@Category(CheckModuleTest::class)
class CheckCoffeeModuleTest {

    @Test
    fun checkCoffeeModule() =
        checkModules {
            modules(coffeeAppModule)
        }
}
```

this gradle task can then do the job:

```gradle
task checkModules(type: Test) {
    testLogging {
        showStandardStreams = true
    }
    useJUnit {
        includeCategories 'org.koin.test.category.CheckModuleTest'
    }
}
```

with just a command line:
```
gradlew checkModules
```

or even

```
gradlew checkModules --continuous
```

I just need now to give away this task 👍

**Comment by iRYO400** [comment]
Tried your solution with that class:

```
@RunWith(AndroidJUnit4::class)
@Config(sdk = [Build.VERSION_CODES.P])
@Category(CheckModuleTest::class)
class KoinInjectorTest : KoinTest {

    @Test
    fun `check all modules`() = checkModules {
        printLogger(Level.DEBUG)
        androidContext(ApplicationProvider.getApplicationContext())

        modules(
            listOf(
                networkModule,
                apiModule,
                persistenceModule,
                repositoryModule,
                useCaseModule,
                viewModelModule
            )
        )
    }
}
```

And get NPE when call `checkModules`
Here is the stacktrace:

```
FAILURE: Build failed with an exception.
* What went wrong:
Could not determine the dependencies of task ':checkModules'.
> java.lang.NullPointerException (no error message)
* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Exception is:
org.gradle.api.internal.tasks.TaskDependencyResolveException: Could not determine the dependencies of task ':checkModules'.
	at org.gradle.api.internal.tasks.CachingTaskDependencyResolveContext.getDependencies(CachingTaskDependencyResolveContext.java:68)
	at org.gradle.execution.plan.TaskDependencyResolver.resolveDependenciesFor(TaskDependencyResolver.java:46)
	at org.gradle.execution.plan.LocalTaskNode.getDependencies(LocalTaskNode.java:111)
	at org.gradle.execution.plan.LocalTaskNode.resolveDependencies(LocalTaskNode.java:79)
	at org.gradle.execution.plan.DefaultExecutionPlan.addEntryTasks(DefaultExecutionPlan.java:177)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph.addEntryTasks(DefaultTaskExecutionGraph.java:139)
...
```


```
Caused by: java.lang.NullPointerException
	at org.gradle.api.tasks.testing.Test.getCandidateClassFiles(Test.java:1043)
	at org.gradle.api.tasks.testing.Test_Decorated.getCandidateClassFiles(Unknown Source)
	at org.gradle.api.internal.tasks.properties.bean.AbstractNestedRuntimeBeanNode$BeanPropertyValue$1$1.create(AbstractNestedRuntimeBeanNode.java:75)
	at org.gradle.util.SingleMessageLogger.whileDisabled(SingleMessageLogger.java:341)
	at org.gradle.api.internal.tasks.properties.bean.AbstractNestedRuntimeBeanNode$BeanPropertyValue$1.get(AbstractNestedRuntimeBeanNode.java:72)
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:167)
	at org.gradle.api.internal.tasks.properties.bean.AbstractNestedRuntimeBeanNode$BeanPropertyValue.call(AbstractNestedRuntimeBeanNode.java:119)
	at org.gradle.util.GUtil.uncheckedCall(GUtil.java:459)
	at org.gradle.api.internal.file.collections.BuildDependenciesOnlyFileCollectionResolveContext.add(BuildDependenciesOnlyFileCollectionResolveContext.java:64)
	at org.gradle.api.internal.file.collections.BuildDependenciesOnlyFileCollectionResolveContext.add(BuildDependenciesOnlyFileCollectionResolveContext.java:72)
	at org.gradle.api.internal.file.DefaultFileCollectionFactory$ResolvingFileCollection.visitContents(DefaultFileCollectionFactory.java:209)
	at org.gradle.api.internal.file.CompositeFileCollection.visitDependencies(CompositeFileCollection.java:186)
	at org.gradle.api.internal.tasks.CachingTaskDependencyResolveContext$TaskGraphImpl.getNodeValues(CachingTaskDependencyResolveContext.java:106)
	at org.gradle.internal.graph.CachingDirectedGraphWalker$GraphWithEmptyEdges.getNodeValues(CachingDirectedGraphWalker.java:211)
	at org.gradle.internal.graph.CachingDirectedGraphWalker.doSearch(CachingDirectedGraphWalker.java:121)
	at org.gradle.internal.graph.CachingDirectedGraphWalker.findValues(CachingDirectedGraphWalker.java:73)
	at org.gradle.api.internal.tasks.CachingTaskDependencyResolveContext.getDependencies(CachingTaskDependencyResolveContext.java:66)
	... 106 more
```

**Comment by arnaudgiuliani** [comment]
can you remove this?

```kotlin
@RunWith(AndroidJUnit4::class)
@Config(sdk = [Build.VERSION_CODES.P])
```
