### ISSUE TITLE
How to inject generic ViewModel class in Koin?

### ISSUE THREAD

**Issue by yektasarioglu** [InsertKoinIO/koin#729]
I'm getting **java.lang.RuntimeException: Unable to create application com.menlo.staroke.DuetApp: org.koin.core.error.DefinitionOverrideException: Already existing definition or try to override an existing one** error. I try to inject a generic view model. Is there any way to achieve that in Koin? Any help would be appreciated. Thanks.

**Modules.kt**
```
    viewModel { ProfileCategoryViewModel<Record>(get(), get()) }
    viewModel { ProfileCategoryViewModel<OpenDuet>(get(), get()) }
```

```
       Process: com.menlo.staroke, PID: 24882
    java.lang.RuntimeException: Unable to create application com.menlo.staroke.DuetApp: org.koin.core.error.DefinitionOverrideException: Already existing definition or try to override an existing one: [type:Factory,primary_type:'com.menlo.staroke.ui.profile.viewmodel.ProfileCategoryViewModel']
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5890)
        at android.app.ActivityThread.access$1100(ActivityThread.java:200)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1651)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6692)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: org.koin.core.error.DefinitionOverrideException: Already existing definition or try to override an existing one: [type:Factory,primary_type:'com.menlo.staroke.ui.profile.viewmodel.ProfileCategoryViewModel']
        at org.koin.core.registry.BeanRegistry.addDefinition(BeanRegistry.kt:144)
        at org.koin.core.registry.BeanRegistry.saveDefinition(BeanRegistry.kt:101)
        at org.koin.core.registry.BeanRegistry.saveDefinitions(BeanRegistry.kt:71)
        at org.koin.core.registry.BeanRegistry.loadModules(BeanRegistry.kt:49)
        at org.koin.core.KoinApplication.loadModulesAndScopes(KoinApplication.kt:66)
        at org.koin.core.KoinApplication.access$loadModulesAndScopes(KoinApplication.kt:31)
        at org.koin.core.KoinApplication$modules$duration$1.invoke(KoinApplication.kt:54)
        at org.koin.core.KoinApplication$modules$duration$1.invoke(KoinApplication.kt:31)
        at org.koin.core.time.MeasureKt.measureDurationOnly(Measure.kt:28)
        at org.koin.core.KoinApplication.modules(KoinApplication.kt:53)
        at com.menlo.staroke.DuetApp$onCreate$1.invoke(DuetApp.kt:104)
        at com.menlo.staroke.DuetApp$onCreate$1.invoke(DuetApp.kt:54)
        at org.koin.core.context.GlobalContextKt.startKoin(GlobalContext.kt:72)
        at com.menlo.staroke.DuetApp.onCreate(DuetApp.kt:101)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1155)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5885)
```

**Comment by krasavello13** [comment]
Hi, as i understand you have problem with ViewModel, because it can`t understand why have to create two the same instance of an object (in your case ProfileCategoryViewModel) 

Try to add  "Qualifier" for distinctive feature of your ViewModels

To get more info please check this link: https://doc.insert-koin.io/#/koin-core/definitions?id=definition-naming-amp-default-bindings

**Comment by yektasarioglu** [comment]
Thank you @krasavello13. It worked like a charm.
