### ISSUE TITLE
Android library project - A Koin Application has already been started

### ISSUE THREAD

**Issue by jakubgruber** [InsertKoinIO/koin#737]
# Koin project used and used version:

- project: koin-android
- version: `2.0.1`
- platform: Android

## Bug Description

I am developing android-library project that uses Koin. The library should be used as a singleton and provides `initialize` method consuming Andorid **Context** in which Koin is initialized.

The library is initialized by user (let's call it **final app**) in Application's `onCreate` method.

It works as charm unless the **final app** uses Koin as well. In such case, the `startKoin` in android-library throws exception:

```
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694) 
     Caused by: org.koin.core.error.InstanceCreationException: Could not create instance for [type:Single,primary_type:'my.example.project.core.LibraryInstance']
        at org.koin.core.instance.DefinitionInstance.create(DefinitionInstance.kt:61)
        at org.koin.core.instance.SingleDefinitionInstance.get(SingleDefinitionInstance.kt:40)
        at org.koin.core.definition.BeanDefinition.resolveInstance(BeanDefinition.kt:70)
        ... 
     Caused by: org.koin.core.error.KoinAppAlreadyStartedException: A Koin Application has already been started
        at org.koin.core.context.GlobalContext.start(GlobalContext.kt:51)
        at org.koin.core.context.GlobalContextKt.startKoin(GlobalContext.kt:71)
        at my.example.project.core.di.KoinContextProvider$koin$2.invoke(KoinContextProvider.kt:15)
        at my.example.project.core.di.KoinContextProvider$koin$2.invoke(KoinContextProvider.kt:10)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at my.example.project.core.di.KoinContextProvider.getKoin(KoinContextProvider.kt)
        at my.example.project.core.di.MyKoinComponent$DefaultImpls.getKoin(MyKoinComponent.kt:7)
        at my.example.project.core.LibraryInstanceImpl.getKoin(LibraryInstanceImpl.kt:14)
        at my.example.project.core.LibraryInstanceImpl.<init>(LibraryInstanceImpl.kt:74)
        at my.example.project.ExampleKoinApp$onCreate$1$1$1.invoke(ExampleKoinApp.kt:20)
        at my.example.project.ExampleKoinApp$onCreate$1$1$1.invoke(ExampleKoinApp.kt:11)
```

For sake of simplicity, the exception is a little shortened. I can provide full exception if necessary, but it seems like it is not allowed to call `startKoin` twice in an Android project?

## Expected behavior

As basically any android-library can be using Koin in its internal implementation, shouldn't it be independent and KoinApplication should be scoped?

## To reproduce

1. Create an Android project with two modules - app and library
2. Configure **koin-android** dependency for both
3. Add `implementation project(':library')` in app's build.gradle
4. In library project, create an object Library with method `initialize` consuming Android Context
5. In app project, extend Application class and in its `onCreate` method, startKoin and then call `Library.initialize`
6. The app should crash now

### Support codes

```
class ExampleKoinApp : Application() {

    override fun onCreate() {
        super.onCreate()

        startKoin {
            androidContext(this@ExampleKoinApp)
            modules(...)
        }

        Library.initialize(this@ExampleKoinApp)
    }
}

object Library {

    private lateinit var appContext: Context

    val koin: Koin by lazy {
        startKoin {
            modules(...)
        }.koin
    }

    @Synchronized
    fun initialize(context: Context) {
        if (::appContext.isInitialized) return

        appContext = context.applicationContext
    }
```

**Comment by Sar777** [comment]
The main reason of the exception is that Koin uses GlobalContext and the context must be initialized once. We should create own context for your library and then will work fine.

**Comment by jakubgruber** [comment]
> The main reason of the exception is that Koin uses GlobalContext and the context must be initialized once. We should create own context for your library and then will work fine.

Could you please explain it a little bit more in detail? Is it a wrong usage of Koin on my side or it's a feature request missing in Koin?

Thank you

**Comment by anupam-sapre** [comment]
https://github.com/InsertKoinIO/koin/issues/682#issuecomment-574544994 you could check this

**Comment by jakubgruber** [comment]
I am not sure it solves my issue. If an owner of an app using my library would be using my Koin as well, I do not want to register my bindings and dependencies into scope of his `KoinApplication`. 

It could potentionally overwrite his dependencies or introduce a conflict.

**Comment by nikhil-thakkar** [comment]
You can't call `startKoin` twice in the `GlobalContext`. You have two options:

1. Either use `loadKoinModules`
2. Use a `KoinApplication` to isolate your lib scope.

Both the approaches are documented well [here](https://doc.insert-koin.io/#/koin-core/start-koin?id=behind-the-start-koin-instance-under-the-hood).

**Comment by jakubgruber** [comment]
@nikhil-thakkar I forgot to implement my own `KoinComponent`. Now it works like charm.

Thank you for excellent support guys!

**Comment by hannesa2** [comment]
> 

Sorry, the doc link has an issue

<img width="829" alt="image" src="https://user-images.githubusercontent.com/3314607/143246336-691890c6-0f0f-4e98-a616-8a8b812df2b7.png">

**Comment by chrisnkrueger** [comment]
@hannesa2 Here is the new doc link:
https://insert-koin.io/docs/3.1/reference/koin-core/context-isolation/

**Comment by hannesa2** [comment]
> @hannesa2 Here is the new doc link: https://insert-koin.io/docs/3.1/reference/koin-core/context-isolation/

Maybe it worked in the meantime. No clue.
If yes, stable url are an property too.

<img width="922" alt="image" src="https://github.com/InsertKoinIO/koin/assets/3314607/30366d65-e880-4761-9b1a-a86bfbdd8a69">
