### ISSUE TITLE
ExceptionInInitializerError

### ISSUE THREAD

**Issue by Elswah** [InsertKoinIO/koin#759]
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.tatweer.busqueueapp.dev, PID: 5202
    java.lang.**### 

- ExceptionInInitializerError

**
        at okhttp3.internal.platform.Platform$Companion.findPlatform(Platform.kt:211)
        at okhttp3.internal.platform.Platform$Companion.access$findPlatform(Platform.kt:179)
        at okhttp3.internal.platform.Platform.<clinit>(Platform.kt:180)
        at okhttp3.OkHttpClient.<init>(OkHttpClient.kt:219)
        at okhttp3.OkHttpClient$Builder.build(OkHttpClient.kt:955)
        at com.microsoft.signalr.DefaultHttpClient.<init>(DefaultHttpClient.java:90)
        at com.microsoft.signalr.DefaultHttpClient.<init>(DefaultHttpClient.java:23)
        at com.microsoft.signalr.HubConnection.<init>(HubConnection.java:144)
        at com.microsoft.signalr.HttpHubConnectionBuilder.build(HttpHubConnectionBuilder.java:122)
        at com.tatweer.busqueueapp.common.infrastructure.signalr.SdtSignalR.<init>(SdtSignalR.kt:20)
        at com.tatweer.busqueueapp.common.infrastructure.signalr.SdtSignalR.<init>(SdtSignalR.kt:18)
        at com.tatweer.busqueueapp.common.infrastructure.signalr.SignalRModuleKt$signalRModule$1$1.invoke(SignalRModule.kt:9)
        at com.tatweer.busqueueapp.common.infrastructure.signalr.SignalRModuleKt$signalRModule$1$1.invoke(SignalRModule.kt)
        at org.koin.core.instance.DefinitionInstance.create(DefinitionInstance.kt:54)
        at org.koin.core.instance.SingleDefinitionInstance.get(SingleDefinitionInstance.kt:40)
        at org.koin.core.definition.BeanDefinition.resolveInstance(BeanDefinition.kt:70)
        at org.koin.core.scope.Scope.resolveInstance(Scope.kt:165)
        at org.koin.core.scope.Scope.access$resolveInstance(Scope.kt:33)
        at org.koin.core.scope.Scope$get$$inlined$synchronized$lambda$1.invoke(Scope.kt:123)
        at org.koin.core.time.MeasureKt.measureDuration(Measure.kt:37)
        at org.koin.core.scope.Scope.get(Scope.kt:122)
        at com.tatweer.busqueueapp.common.infrastructure.arch.ViewModelModuleKt$viewModelModule$1$1.invoke(ViewModelModule.kt:17)
        at com.tatweer.busqueueapp.common.infrastructure.arch.ViewModelModuleKt$viewModelModule$1$1.invoke(ViewModelModule.kt)
        at org.koin.core.instance.DefinitionInstance.create(DefinitionInstance.kt:54)
        at org.koin.core.instance.FactoryDefinitionInstance.get(FactoryDefinitionInstance.kt:37)
        at org.koin.core.definition.BeanDefinition.resolveInstance(BeanDefinition.kt:70)
        at org.koin.core.scope.Scope.resolveInstance(Scope.kt:165)
        at org.koin.core.scope.Scope.access$resolveInstance(Scope.kt:33)
        at org.koin.core.scope.Scope$get$$inlined$synchronized$lambda$1.invoke(Scope.kt:123)
        at org.koin.core.time.MeasureKt.measureDuration(Measure.kt:37)
        at org.koin.core.scope.Scope.get(Scope.kt:122)
        at org.koin.androidx.viewmodel.ViewModelResolutionKt$createViewModelProvider$1.create(ViewModelResolution.kt:66)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:187)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:150)
        at org.koin.androidx.viewmodel.ViewModelResolutionKt$getInstance$1.invoke(ViewModelResolution.kt:34)
        at org.koin.androidx.viewmodel.ViewModelResolutionKt$getInstance$1.invoke(ViewModelResolution.kt)
        at org.koin.core.time.MeasureKt.measureDuration(Measure.kt:37)
        at org.koin.androidx.viewmodel.ViewModelResolutionKt.getInstance(ViewModelResolution.kt:30)
        at org.koin.androidx.viewmodel.ViewModelResolutionKt.getViewModel(ViewModelResolution.kt:23)
        at org.koin.androidx.viewmodel.ext.android.FragmentExtKt.getSharedViewModel(FragmentExt.kt:92)
        at com.tatweer.busqueueapp.features.students.StudentsListFragment$$special$$inlined$sharedViewModel$2.invoke(FragmentExt.kt:102)
        at com.tatweer.busqueueapp.features.students.StudentsListFragment$$special$$inlined$sharedViewModel$2.invoke(FragmentExt.kt)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at com.tatweer.busqueueapp.features.students.StudentsListFragment.getStudentsViewModel(StudentsListFragment.kt)
        at com.tatweer.busqueueapp.features.students.StudentsListFragment.getViewModel(StudentsListFragment.kt:57)
        at com.tatweer.busqueueapp.features.students.StudentsListFragment.getViewModel(StudentsListFragment.kt:33)
    	at com.tatweer.busqueuea

**Comment by Elswah** [comment]
multidex added this happen in api 19 kitkat

**Comment by arnaudgiuliani** [comment]
not remated to Koin?

**Comment by GauvainSeigneur** [comment]
Hi, I also this issue. I have a multi module(app, presentation, dataAdapter, UseCase) project which has minTargetSDK 19. When I launch the app on a mobile phone with Android Lollipop, it works fine. But under, I have the same issue for all my Koin modules (which are present in presentation, dataAdapter and useCase) with a mobile phone under API 21. Even when I set up Multidex.

**Comment by GauvainSeigneur** [comment]
Ok, I ended up set up all my module files into app module. The problem remains. So it is not related to Koin. In my project, it was the version of okhttp actually
