### ISSUE TITLE
How to correctly create a app-wise ViewModel with SavedStateHandle as parameter?

### ISSUE THREAD

**Issue by cyberrob** [InsertKoinIO/koin#793]
**Describe the bug**
I’m declaring a ViewModel with SavedStateHandle as parameter in koin modules

**To Reproduce**
1. in koin modules
```kotlin
viewModel { (handle: SavedStateHandle) -> CacheProvider(handle) }
```
2. And initiate it in Activity
```kotlin
// Not sure what the correct way of doing this. Different ways mentioned in other issues
private val cacheProvider: CacheProvider by stateViewModel(bundle = Bundle()) {
        parametersOf(
            SavedStateHandle()
        )
    }
```
3. And try to access that very same ViewModel in fragments and pass it to other ViewModels if needed. 
```kotlin
private val cacheProvider: CacheProvider by sharedViewModel()
```
4. Accessing that shared ViewModel in fragment, app crashed like this:
```kotlin
createButton.setOnClick {
            cacheProvider.DepositData?.apply {
                name = viewModel.pocketNameInput
                viewModel.pocketIcon?.run {
                    icon = this
                }
            }
            toNextPage()
        }
```
5. App crash:
```
2020-04-30 18:37:07.305 23018-23018/com.ncbportal.sit W/System.err: Caused by: org.koin.core.error.NoParameterFoundException: Can't get parameter value #0 from org.koin.core.parameter.DefinitionParameters@cb8e21b
2020-04-30 18:37:07.305 23018-23018/com.ncbportal.sit W/System.err:     at org.koin.core.parameter.DefinitionParameters.elementAt(DefinitionParameters.kt:32)
2020-04-30 18:37:07.305 23018-23018/com.ncbportal.sit W/System.err:     at org.koin.core.parameter.DefinitionParameters.component1(DefinitionParameters.kt:34)
2020-04-30 18:37:07.305 23018-23018/com.ncbportal.sit W/System.err:     at com.nextbank.ncbportal.di.ViewModelModuleKt$viewModelModule$1$77.invoke(Unknown Source:11)
2020-04-30 18:37:07.305 23018-23018/com.ncbportal.sit W/System.err:     at com.nextbank.ncbportal.di.ViewModelModuleKt$viewModelModule$1$77.invoke(Unknown Source:4)
2020-04-30 18:37:07.305 23018-23018/com.ncbportal.sit W/System.err:     at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:50)
2020-04-30 18:37:07.305 23018-23018/com.ncbportal.sit W/System.err: 	... 38 more
```
**Expected behavior**
A initialized and same CacheProvider should be accessible.

**Koin project used and used version (please complete the following information):**

```gradle
koin_version = '2.1.5'
implementation "org.koin:koin-androidx-scope:$koin_version"
implementation "org.koin:koin-androidx-viewmodel:$koin_version"
implementation "org.koin:koin-androidx-ext:$koin_version"
```

**Additional moduleDefinition**
I'm try to create a app-wise ViewModel associated with Activity to provide data for child fragments and its ViewModel. Not sure if what is the right to do.

**Comment by Tommy-Geenexus** [comment]
@cyberrob 
https://github.com/InsertKoinIO/koin/pull/768 introduces a shared state viewmodel, which fixes the above issue and will presumably be included in the next minor release.

As a workaround you can add the extensions introduced by https://github.com/InsertKoinIO/koin/pull/768 to your project and replace `by sharedViewModel()`  with `by stateSharedViewModel()` in the respective fragments.

**Comment by cyberrob** [comment]
@Tommy-Geenexus Thanks! It looks great! and I found the issue is mostly about me trying to put `stateSharedViewModel` as parameter in fragment's ViewModel to cause crash. Once the parameter removed it works fine.

One more thing, naming of extension functions in koin almost looks identical like ActivityExt in Android. It causes some trouble while debugging...
