### ISSUE TITLE
 java.lang.RuntimeException: java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by miladsalimiiii** [InsertKoinIO/koin#805]
**I used koin in another app that i have one server and one API client but in new i have two server and two API client , when i want to call APIs i faced with below error in the end of the issue i wrote that.**

This is my APImodule :

```
val apiModule= module {

    single {
        ApiClientDolphin.getService(okHttpClient = get(named("dolphin")),
            baseUrl = get(named("DolphinServer")),sharedPreferencesJwtPersistor = get())
    }
    single(named("DolphinServer")) { "https://milestone-maestro.carrene.com/apiv1/" }
    factory (named("dolphin")){ OkHttpClient().newBuilder().cookieJar(get())}
    factory (named("panda")) { OkHttpClient().newBuilder()}

    single <CookieJar> {
        (PersistentCookieJar(SetCookieCache(), SharedPrefsCookiePersistor(androidApplication())))
    }
    single { SharedPrefsCookiePersistor(androidApplication()) }

    single { SharedPreferencesJwtPersistor(androidApplication()) }

    single { ApiClientPanda.getService(okHttpClient = get(named("panda")),baseUrl = get(named("PandaServer"))) }

    single(named("PandaServer")) { "https://milestone-cas.carrene.com/apiv1/" }

}
```

This is my repository module : 

```
val repositoryModule= module {

    single { TokenRepository(get(),get()) }
}
```

This is my viewModel module : 

```
val viewModelModule= module {

    viewModel { LoginViewModel(get(),get()) }

}
```

And i start koin in MyApplicaiton as this : 

```
    override fun onCreate() {
        super.onCreate()
        AppCompatDelegate.setCompatVectorFromResourcesEnabled(true)
        startKoin {
            androidLogger()
            androidContext(this@MyApplication)
            modules(
                listOf(
                    apiModule,
                    repositoryModule,
                    utilModule,
                    viewModelModule
                )
            )
        }
    }
```

But i faced with this error : 

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: de.netalic.stork, PID: 12301
    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
     Caused by: org.koin.core.error.InstanceCreationException: Could not create instance for [type:Factory,primary_type:'de.netalic.stork.ui.login.LoginViewModel']
        at org.koin.core.instance.DefinitionInstance.create(DefinitionInstance.kt:61)
        at org.koin.core.instance.FactoryDefinitionInstance.get(FactoryDefinitionInstance.kt:37)
        at org.koin.core.definition.BeanDefinition.resolveInstance(BeanDefinition.kt:70)
        at org.koin.core.scope.Scope.resolveInstance(Scope.kt:165)
        at org.koin.core.scope.Scope.get(Scope.kt:128)
        at de.netalic.stork.ui.login.LoginActivity$$special$$inlined$inject$1.invoke(ComponentCallbackExt.kt:51)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at de.netalic.stork.ui.login.LoginActivity.getMLoginViewModel(LoginActivity.kt)
        at de.netalic.stork.ui.login.LoginActivity.access$getMLoginViewModel$p(LoginActivity.kt:13)
        at de.netalic.stork.ui.login.LoginActivity$initUiListeners$3.onClick(LoginActivity.kt:51)
        at android.view.View.performClick(View.java:5637)
        at android.view.View$PerformClick.run(View.java:22429)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
     Caused by: org.koin.core.error.InstanceCreationException: Could not create instance for [type:Single,primary_type:'de.netalic.stork.data.Repository.TokenRepository']
        at org.koin.core.instance.DefinitionInstance.create(DefinitionInstance.kt:61)
        at org.koin.core.instance.SingleDefinitionInstance.get(SingleDefinitionInstance.kt:40)
        at org.koin.core.definition.BeanDefinition.resolveInstance(BeanDefinition.kt:70)
        at org.koin.core.scope.Scope.resolveInstance(Scope.kt:165)
        at org.koin.core.scope.Scope.get(Scope.kt:128)
        at de.netalic.stork.di.ViewModelModuleKt$viewModelModule$1$1.invoke(ViewModelModule.kt:15)
        at de.netalic.stork.di.ViewModelModuleKt$viewModelModule$1$1.invoke(ViewModelModule.kt)
        at org.koin.core.instance.DefinitionInstance.create(DefinitionInstance.kt:54)
        at org.koin.core.instance.FactoryDefinitionInstance.get(FactoryDefinitionInstance.kt:37) 
        at org.koin.core.definition.BeanDefinition.resolveInstance(BeanDefinition.kt:70) 
        at org.koin.core.scope.Scope.resolveInstance(Scope.kt:165) 
        at org.koin.core.scope.Scope.get(Scope.kt:128) 
        at de.netalic.stork.ui.login.LoginActivity$$special$$inlined$inject$1.invoke(ComponentCallbackExt.kt:51) 
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74) 
        at de.netalic.stork.ui.login.LoginActivity.getMLoginViewModel(LoginActivity.kt) 
        at de.netalic.stork.ui.login.LoginActivity.access$getMLoginViewModel$p(LoginActivity.kt:13) 
        at de.netalic.stork.ui.login.LoginActivity$initUiListeners$3.onClick(LoginActivity.kt:51) 
        at android.view.View.performClick(View.java:5637) 
        at android.view.View$PerformClick.run(View.java:22429) 
        at android.os.Handler.handleCallback(Handler.java:751) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6119) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
     Caused by: org.koin.core.error.InstanceCreationException: Could not create instance for [type:Single,primary_type:'de.netalic.stork.data.webservice.ApiInterfacePanda']
        at org.koin.core.instance.DefinitionInstance.create(DefinitionInstance.kt:61)
        at org.koin.core.instance.SingleDefinitionInstance.get(SingleDefinitionInstance.kt:40)
        at org.koin.core.definition.BeanDefinition.resolveInstance(BeanDefinition.kt:70)
        at org.koin.core.scope.Scope.resolveInstance(Scope.kt:165)
        at org.koin.core.scope.Scope.get(Scope.kt:128)
        at de.netalic.stork.di.RepositoryModuleKt$repositoryModule$1$1.invoke(RepositoryModule.kt:13)
        at de.netalic.stork.di.RepositoryModuleKt$repositoryModule$1$1.invoke(RepositoryModule.kt)
        at org.koin.core.instance.DefinitionInstance.create(DefinitionInstance.kt:54)
        at org.koin.core.instance.SingleDefinitionInstance.get(SingleDefinitionInstance.kt:40) 
        at org.koin.core.definition.BeanDefinition.resolveInstance(BeanDefinition.kt:70) 
        at org.koin.core.scope.Scope.resolveInstance(Scope.kt:165) 
        at org.koin.core.scope.Scope.get(Scope.kt:128) 
        at de.netalic.stork.di.ViewModelModuleKt$viewModelModule$1$1.invoke(ViewModelModule.kt:15) 
        at de.netalic.stork.di.ViewModelModuleKt$viewModelModule$1$1.invoke(ViewModelModule.kt) 
        at org.koin.core.instance.DefinitionInstance.create(DefinitionInstance.kt:54) 
        at org.koin.core.instance.FactoryDefinitionInstance.get(FactoryDefinitionInstance.kt:37) 
        at org.koin.core.definition.BeanDefinition.resolveInstance(BeanDefinition.kt:70) 
        at org.koin.core.scope.Scope.resolveInstance(Scope.kt:165) 
        at org.koin.core.scope.Scope.get(Scope.kt:128) 
        at de.netalic.stork.ui.login.LoginActivity$$special$$inlined$inject$1.invoke(ComponentCallbackExt.kt:51) 
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74) 
        at de.netalic.stork.ui.login.LoginActivity.getMLoginViewModel(LoginActivity.kt) 
        at de.netalic.stork.ui.login.LoginActivity.access$getMLoginViewModel$p(LoginActivity.kt:13) 
        at de.netalic.stork.ui.login.LoginActivity$initUiListeners$3.onClick(LoginActivity.kt:51) 
        at android.view.View.performClick(View.java:5637) 
        at android.view.View$PerformClick.run(View.java:22429) 
        at android.os.Handler.handleCallback(Handler.java:751) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6119) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
     Caused by: kotlin.KotlinNullPointerException
        at de.netalic.stork.data.webservice.ApiClientPanda$Companion.getService(ApiClientPanda.kt:33)
        at de.netalic.stork.di.ApiModuleKt$apiModule$1$8.invoke(ApiModule.kt:33)
        at de.netalic.stork.di.ApiModuleKt$apiModule$1$8.invoke(ApiModule.kt)
        at org.koin.core.instance.DefinitionInstance.create(DefinitionInstance.kt:54)
        at org.koin.core.instance.SingleDefinitionInstance.get(SingleDefinitionInstance.kt:40) 
        at org.koin.core.definition.BeanDefinition.resolveInstance(BeanDefinition.kt:70) 
        at org.koin.core.scope.Scope.resolveInstance(Scope.kt:165) 
        at org.koin.core.scope.Scope.get(Scope.kt:128) 
        at de.netalic.stork.di.RepositoryModuleKt$repositoryModule$1$1.invoke(RepositoryModule.kt:13) 
        at de.netalic.stork.di.RepositoryModuleKt$repositoryModule$1$1.invoke(RepositoryModule.kt) 
        at org.koin.core.instance.DefinitionInstance.create(DefinitionInstance.kt:54) 
        at org.koin.core.instance.SingleDefinitionInstance.get(SingleDefinitionInstance.kt:40) 
        at org.koin.core.definition.BeanDefinition.resolveInstance(BeanDefinition.kt:70) 
        at org.koin.core.scope.Scope.resolveInstance(Scope.kt:165) 
        at org.koin.core.scope.Scope.get(Scope.kt:128) 
        at de.netalic.stork.di.ViewModelModuleKt$viewModelModule$1$1.invoke(ViewModelModule.kt:15) 
        at de.netalic.stork.di.ViewModelModuleKt$viewModelModule$1$1.invoke(ViewModelModule.kt) 
        at org.koin.core.instance.DefinitionInstance.create(DefinitionInstance.kt:54) 
        at org.koin.core.instance.FactoryDefinitionInstance.get(FactoryDefinitionInstance.kt:37) 
        at org.koin.core.definition.BeanDefinition.resolveInstance(BeanDefinition.kt:70) 
        at org.koin.core.scope.Scope.resolveInstance(Scope.kt:165) 
        at org.koin.core.scope.Scope.get(Scope.kt:128) 
        at de.netalic.stork.ui.login.LoginActivity$$special$$inlined$inject$1.invoke(ComponentCallbackExt.kt:51) 
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74) 
        at de.netalic.stork.ui.login.LoginActivity.getMLoginViewModel(LoginActivity.kt) 
        at de.netalic.stork.ui.login.LoginActivity.access$getMLoginViewModel$p(LoginActivity.kt:13) 
        at de.netalic.stork.ui.login.LoginActivity$initUiListeners$3.onClick(LoginActivity.kt:51) 
        at android.view.View.performClick(View.java:5637) 
        at android.view.View$PerformClick.run(View.java:22429) 
        at android.os.Handler.handleCallback(Handler.java:751) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6119) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
```

**Comment by miladsalimiiii** [comment]
@arnaudgiuliani

**Comment by etman55** [comment]
i am facing the same problem but with making a multiple mapper interface implementation so did you find it out?
