### ISSUE TITLE
Single Activity recreation causes FragmentFactory to crash with NoBeanDefFoundException

### ISSUE THREAD

**Issue by leungandrew** [InsertKoinIO/koin#838]
**Describe the bug**
When using a single activity app, KoinFragmentFactory, and an InjectingNavHostFragment (that is, a NavHostFragment where it's FragmentFactory has been replaced with the KoinFragmentFactory), whenever the activity get's recreated for whatever reason (for example, Android deciding the Activity needs to be destroyed, and therefore, upon return to the app, the activity is recreated), then FragmentFactory will crash.

**To Reproduce**
A really simple way to reproduce the issue is simply to turn on `Don't keep activities` setting in Developer options to simulate Android OS causing the activity to be recreated.  Another way is to start your app, background for a long time, and then return to the app (but the developer option is basically the same behaviour)

In your Application:
```
    override fun onCreate() {
        super.onCreate()
        startKoin {
            androidLogger()
            androidContext(this@MyApplication)
            fragmentFactory()
            modules(appModules)
        }
```

In your MainActivity (your single activity):
```
override fun onCreate(savedInstanceState: Bundle?) {
        setupKoinFragmentFactory()
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
}
```

In your activity_main layout:
```
        <fragment
                android:id="@+id/nav_host_fragment"
                android:name="com.example.InjectingNavHostFragment"
                android:layout_width="0dp"
                android:layout_height="0dp"
                app:defaultNavHost="true"
                app:layout_constraintBottom_toTopOf="@+id/bottom_navigation"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintStart_toStartOf="parent"
                app:layout_constraintTop_toTopOf="parent"
                app:navGraph="@navigation/nav_graph" />
```

InjectingNavHostFragment:
```
class InjectingNavHostFragment(private val fragmentFactory: FragmentFactory) : NavHostFragment() {

    override fun onCreate(savedInstanceState: Bundle?) {
        childFragmentManager.fragmentFactory = fragmentFactory
        super.onCreate(savedInstanceState)
    }
}
```

And in your Koin module, you would define all your beans for your FragmentFactory.
```
val fragmentModule: Module = module {
    fragment { InjectingNavHostFragment(get()) }
   // all your other fragments
  fragment { MyCrashingFragment() }
}
```

Upon activity being recreated, the following stack trace is produced:
```
     Caused by: android.view.InflateException: Binary XML file line #30 in com.example:layout/activity_main: Error inflating class fragment
     Caused by: org.koin.core.error.NoBeanDefFoundException: No definition found for class:'com.example.MyCrashingFragment'. Check your definitions!
        at org.koin.core.scope.Scope.throwDefinitionNotFound(Scope.kt:237)
        at org.koin.core.scope.Scope.resolveInstance(Scope.kt:211)
        at org.koin.core.scope.Scope.get(Scope.kt:177)
        at org.koin.core.Koin.get(Koin.kt:113)
        at org.koin.core.Koin.get$default(Koin.kt:112)
        at org.koin.androidx.fragment.android.KoinFragmentFactory.instantiate(KoinFragmentFactory.kt:16)
        at androidx.fragment.app.FragmentStateManager.<init>(FragmentStateManager.java:74)
        at androidx.fragment.app.FragmentManager.restoreSaveState(FragmentManager.java:2454)
        at androidx.fragment.app.Fragment.restoreChildFragmentState(Fragment.java:1706)
        at androidx.fragment.app.Fragment.onCreate(Fragment.java:1683)
        at com.example.BaseFragment.onCreate(BaseFragment.kt:18)
        at androidx.fragment.app.Fragment.performCreate(Fragment.java:2684)
        at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:280)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1175)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1497)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2625)
        at androidx.fragment.app.FragmentManager.dispatchCreate(FragmentManager.java:2571)
        at androidx.fragment.app.Fragment.restoreChildFragmentState(Fragment.java:1707)
        at androidx.fragment.app.Fragment.onCreate(Fragment.java:1683)
        at androidx.navigation.fragment.NavHostFragment.onCreate(NavHostFragment.java:206)
        at com.example.InjectingNavHostFragment.onCreate(InjectingNavHostFragment.kt:11)
        at androidx.fragment.app.Fragment.performCreate(Fragment.java:2684)
        at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:280)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1175)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
E/AndroidRuntime:     at androidx.fragment.app.FragmentLayoutInflaterFactory.onCreateView(FragmentLayoutInflaterFactory.java:135)
        at androidx.fragment.app.FragmentController.onCreateView(FragmentController.java:135)
        at androidx.fragment.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java:356)
        at androidx.fragment.app.FragmentActivity.onCreateView(FragmentActivity.java:335)
        at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1069)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:997)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1126)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:682)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:481)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:555)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:161)
        at com.example.MainActivity.onCreate(MainActivity.kt:37)
        at android.app.Activity.performCreate(Activity.java:7825)
        at android.app.Activity.performCreate(Activity.java:7814)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Expected behavior**

When the activity is recreated, the fragment factory should have the definitions to restore the previous state of the app.  I don't expect the app to crash.

**Koin project used and used version (please complete the following information):**
```
    def koin_version = "2.1.3"
    implementation "org.koin:koin-android:$koin_version"
    implementation "org.koin:koin-core:$koin_version"
    implementation "org.koin:koin-android-scope:$koin_version"
    implementation "org.koin:koin-android-viewmodel:$koin_version"
    implementation "org.koin:koin-androidx-fragment:$koin_version"
```
**Additional moduleDefinition**
Add any other moduleDefinition about the problem here.

**Comment by timrijckaert** [comment]
This is a big problem.
We face it too

**Comment by darek607** [comment]
I had similar issue when used sharedViewModel that got parameters. The solution was to use `androidx.fragment.app.FragmentContainerView` instead of `fragment` as a nav host (as suggested by the lint in xml).

**Comment by krasavello13** [comment]
If you want to use `NavHostFragment()`, you don't need to do setup Koin `FragmentFactory()` in your `Activity`
