### ISSUE TITLE
[Crash] Koin Logger Measure and Kotlin EAP 1.4-M3

### ISSUE THREAD

**Issue by ParaskP7** [InsertKoinIO/koin#847]
**Describe the bug**
This is just a heads up on `Koin` and `Kotlin EAP 1.4-M3`.

After upgrading to `Kotlin EAP 1.4-M3` (from previous `Kotlin EAP 1.4-M2`) when launching the app a `NoSuchMethodException` exception is thrown due to the `elapseNow()` experimental method.

Full exception below:
```
    java.lang.NoSuchMethodError: No virtual method elapsedNow()D in class Lkotlin/time/TimeMark; or its super classes (declaration of 'kotlin.time.TimeMark' appears in /data/app/io.petros.movies-u-dzv9wkMPKfx19uLVQWyg==/base.apk)
        at org.koin.core.time.MeasureKt.measureDuration(Measure.kt:36)
        at org.koin.core.KoinApplication.modules(KoinApplication.kt:60)
        at io.petros.movies.app.App$initKoin$1.invoke(App.kt:45)
        at io.petros.movies.app.App$initKoin$1.invoke(App.kt:23)
        at org.koin.core.context.ContextFunctionsKt.startKoin(ContextFunctions.kt:39)
        at org.koin.core.context.ContextFunctionsKt.startKoin$default(ContextFunctions.kt:35)
        at io.petros.movies.app.App.initKoin(App.kt:42)
        at io.petros.movies.app.App.onCreate(App.kt:34)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1189)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6460)
        at android.app.ActivityThread.access$1300(ActivityThread.java:219)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

This is due to the fact that my app is using `androidLogger()`, which default to a Koin log level of `Level.INFO` and as such when modules are build the duration is measured, which crashes the app. To overcome this I disabled logging for now, but it will be good if that get fixed so that I can enable it again.

**To Reproduce**
1. Use `Kotlin EAP 1.4-M3` as a dependency in your app (or project)
2. During `Koin` init start with default logging enabled (`Level.INFO`)
3. Launch your app (or project)

**Expected behavior**
I except the app to not crash.

**Koin project used and used version (please complete the following information):**
org.jetbrains.kotlin:kotlin-stdlib:1.4-M3
org.koin:koin-core:2.1.6
org.koin:koin-android:2.1.6
org.koin:koin-androidx-viewmodel:2.1.6

**Additional moduleDefinition**
No additional moduleDefinition.

**Comment by stevenzeck** [comment]
I'm still using Kotlin 1.3.72 and received this error.

**Comment by dummyco** [comment]
I'm facing the same issue with `1.4.0-rc` too.

**Comment by upachecog** [comment]
> I'm facing the same issue with `1.4.0-rc` too.
> ❗ **Temporary workaround:**
> Migrate from `androidLogger()` to `androidLogger(Level.ERROR)`

I am facing the same issue with **koinVersion = '2.1.6'.** 

This workaround is working btw.

**Comment by hoc081098** [comment]
Kotlin 1.4 becomes stable, waiting new release  🌸

**Comment by mannodermaus** [comment]
FWIW the encapsulated functionality of `modules()` is public, so you'd also be able to work around this by inlining the work of that method in your own setup. This way, there is no need to lose all info-level logging going forward.

```kt
// Before:
startKoin {
    androidLogger()
    androidContext(this@MyApplication)

    modules(koinModules)
}

// After:
startKoin {
    androidLogger()
    androidContext(this@MyApplication)

    // TODO Await fix for Koin and replace the explicit invocations
    //  of loadModules() and createRootScope() with a single call to modules()
    //  (https://github.com/InsertKoinIO/koin/issues/847)
    koin.loadModules(koinModules)
    koin.createRootScope()
}
```

**Comment by arnaudgiuliani** [comment]
I have to check & help migration to Kotlin 1.4 for Koin 2.2.0. From what I see here, is the time measurement stuff that are still having problems :/

**Comment by roschlau** [comment]
Same problem here, updating to Kotlin 1.4 bricks loading the modules because the still experimental time API seems to have changed something under the hood, I'm using a modified copy of `modules` now that doesn't use the time API to fix this.

@arnaudgiuliani Would have been nice to know upfront that Koin is using unstable experimental API under the hood, and in such a core code path - silently opting in to the `ExperimentalTime` annotation seems like a questionable choice for a popular library

**Comment by ArthurNagy** [comment]
Besides the exception mentioned above, I'm also getting another `kotlin.time.*` related crash: 
```
java.lang.NoSuchMethodError: No virtual method getINFINITE()D in class Lkotlin/time/Duration$Companion; or its super classes (declaration of 'kotlin.time.Duration$Companion' appears in /data/app/~~1N2V-aVGzuRDhWGsSJSB0A==/com.urbantz.mobile-H0TBPP5b5ClCl2kxZnfo8Q==/base.apk!classes3.dex)
        at com.dropbox.android.external.store4.MemoryPolicy.<clinit>(MemoryPolicy.kt:70)
        at com.dropbox.android.external.store4.StoreDefaults.<clinit>(StoreDefaults.kt:24)
        at com.dropbox.android.external.store4.RealStoreBuilder.<init>(StoreBuilder.kt:90)
        at com.dropbox.android.external.store4.StoreBuilder$Companion.from(StoreBuilder.kt:75)
```
Happens when I'm trying to lazily the first `ViewModel` instance of the app.
```
E/AndroidRuntime:     at org.koin.core.instance.InstanceContext.<init>(InstanceContext.kt:19)
        at org.koin.core.registry.InstanceRegistry.defaultInstanceContext(InstanceRegistry.kt:91)
        at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:87)
        at org.koin.core.scope.Scope.resolveInstance(Scope.kt:214)
        at org.koin.core.scope.Scope.get(Scope.kt:181)
        at org.koin.androidx.viewmodel.ViewModelFactoryKt$defaultViewModelFactory$1.create(ViewModelFactory.kt:50)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:187)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:150)
        at org.koin.androidx.viewmodel.ViewModelResolutionKt.get(ViewModelResolution.kt:21)
        at org.koin.androidx.viewmodel.ViewModelResolutionKt.resolveInstance(ViewModelResolution.kt:10)
        at org.koin.androidx.viewmodel.scope.ScopeExtKt.getViewModel(ScopeExt.kt:70)
        at org.koin.androidx.viewmodel.scope.ScopeExtKt.getViewModel(ScopeExt.kt:56)
        at org.koin.androidx.viewmodel.koin.KoinExtKt.getViewModel(KoinExt.kt:34)
        at org.koin.androidx.viewmodel.ext.android.ViewModelStoreOwnerExtKt.getViewModel(ViewModelStoreOwnerExt.kt:60)
        at com.urbantz.mobile.feature.authentication.signin.SignInFragment$$special$$inlined$viewModel$1.invoke(ViewModelStoreOwnerExt.kt:45)
        at com.urbantz.mobile.feature.authentication.signin.SignInFragment$$special$$inlined$viewModel$1.invoke(Unknown Source:0)
        at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81)
```

**Comment by arnaudgiuliani** [comment]
yep could clearly remove this experimental API that keep moving from release to release

👍

**Comment by stevyhacker** [comment]
I got this crash after updating to stable Kotlin 1.4.0 while everything worked fine before on 1.3.72 Kotlin and 2.1.6 Koin.

**Comment by BuryYa** [comment]
Kotlin 1.3.72 + Koin 2.1.5 - OK
Kotlin 1.4 + Koin 2.1.5 - Error

**Comment by irgaly** [comment]
Kotlin 1.4 + [2.2.0-alpha-1](https://bintray.com/ekito/koin/koin-core/2.2.0-alpha-1) works well.

**Comment by DDihanov** [comment]
> Kotlin 1.4 + [2.2.0-alpha-1](https://bintray.com/ekito/koin/koin-core/2.2.0-alpha-1) works well.

Can confirm - this works for me.

**Comment by lucasls** [comment]
Release Candidate version `2.2.0-rc-3` has this issue fixed

**Comment by erikhuizinga** [comment]
This issue has been around since July and has been fixed since August, but hasn't been released yet in November. I know there have been alpha, beta and rc versions that include this fix, but there is no stable release yet. What is standing in the way of this release?

**Comment by raxander67** [comment]
Kotlin 1.4.10 + Koin 2.2.1 - this works for me.

**Comment by jukov** [comment]
Kotlin 1.4.20 + Koin 2.2.1:
`java.lang.NoSuchMethodError: No virtual method getLogger()Lorg/koin/core/logger/Logger; in class Lorg/koin/core/Koin; or its super classes (declaration of 'org.koin.core.Koin' appears in /data/app/...../base.apk!classes4.dex)
        at org.koin.android.ext.koin.KoinExtKt.androidContext(KoinExt.kt:52)`

**Comment by kldMohammed** [comment]
I have the propblem when i adding kotlin datetime lib

**Comment by AzraelWarrior** [comment]
same issue
kotlin 1.5.0 + koin 3.0.1

**Comment by collinsmao** [comment]
same issue
kotlin 1.5.0 + koin 3.0.1

androidLogger(Level.INFO) crashed

**Comment by mansoorexpert** [comment]
Kotlin 1.4.32 + Koin 2.2.2 - worked for me.

**Comment by prefectAtEarth** [comment]
same issue
kotlin 1.5.20 + koin 3.0.1
@arnaudgiuliani could you please reopen this issue as it semms not to be fixed / to reappear in koin 3.0.1

**Comment by JajaComp** [comment]
> same issue
> kotlin 1.5.20 + koin 3.0.1
> @arnaudgiuliani could you please reopen this issue as it semms not to be fixed / to reappear in koin 3.0.1

Try join 3.1.1

**Comment by arnaudgiuliani** [comment]
Yes Koin 3.1.x is upgrading Kotlin compat

**Comment by EarthDragon88** [comment]
I'm having the same issue
kotlin 1.6.10
koin 3.1.5

**Comment by yusufgltc** [comment]
Add where you configure your koin

 slf4jLogger(level = Level.ERROR)
