### ISSUE TITLE
java.lang.IllegalStateException: No Koin Context configured. Please use startKoin or koinApplication DSL

### ISSUE THREAD

**Issue by Armen101** [InsertKoinIO/koin#890]
**No Koin Context configured. Please use startKoin or koinApplication **DSL****

- test class extends **AutoCloseKoinTest**
- in the **setUp** function (with Before anotation) I have **startKoin** called
- all modules included in startKoin
- my **all test clases extends from AutoCloaseKoinTest**, so I didn't forget about any stopKoin

**Dependencies and versions:**

  `testImplementation 'org.koin:koin-test:2.1.3'`
  `implementation 'org.koin:koin-android:2.1.5'`

  `testImplementation 'junit:junit:4.13'`
  `testImplementation 'android.arch.core:core-testing:1.1.1'`
  `androidTestImplementation 'androidx.test.ext:junit:1.1.2'`
  `androidTestImplementation 'androidx.test:core:1.3.0'`

**Stacktrace**

java.lang.IllegalStateException: No Koin Context configured. Please use startKoin or koinApplication DSL. 

	at org.koin.core.context.KoinContextHandler.getContext(KoinContextHandler.kt:29)
	at org.koin.core.context.KoinContextHandler.get(KoinContextHandler.kt:35)
	at org.koin.core.KoinComponent$DefaultImpls.getKoin(KoinComponent.kt:32)
	at org.koin.test.KoinTest$DefaultImpls.getKoin(KoinTest.kt)
	at org.koin.test.AutoCloseKoinTest.getKoin(AutoCloseKoinTest.kt:26)
	at ...MyTestClass.setUp(MyTestClass.kt:64)

**Comment by arnaudgiuliani** [comment]
last 2.2.0 is fixing startup process. Check that

**Comment by aahspringaa4** [comment]
make BaseApplication
