### ISSUE TITLE
Koin Crashing with latest Kotlin Version

### ISSUE THREAD

**Issue by rahulr4** [InsertKoinIO/koin#896]
**Describe the bug**
Koin is crashing on app start when updating kotlin version

**To Reproduce**
1. Set kotlin version to 1.4.0
2. Run the app

**Expected behavior**
App should run normally.
App works fine if i downgrade kotlin version to 1.3.76

**Current Behavior**
App is crashing
`java.lang.NoSuchMethodError: No virtual method elapsedNow()D in class Lkotlin/time/TimeMark; or its super classes (declaration of 'kotlin.time.TimeMark' appears in /data/app/com.clg.clg.dev-lO0v1761FAG8HfFbmL2bIQ==/base.apk)
        at org.koin.core.time.MeasureKt.measureDuration(Measure.kt:36)
        at org.koin.core.KoinApplication.modules(KoinApplication.kt:60)
        at com.clg.clg.app.KoinInit$Companion$initialize$1$1.invoke(KoinInit.kt:16)
        at com.clg.clg.app.KoinInit$Companion$initialize$1$1.invoke(KoinInit.kt:9)
        at org.koin.core.context.ContextFunctionsKt.startKoin(ContextFunctions.kt:39)
        at org.koin.core.context.ContextFunctionsKt.startKoin$default(ContextFunctions.kt:35)
        at com.clg.clg.app.KoinInit$Companion.initialize(KoinInit.kt:13)
        at com.clg.clg.app.KoinInit.initialize(Unknown Source:2)
        at com.clg.clg.app.CLGApp.onCreate(CLGApp.java:43)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1182)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6460)
        at android.app.ActivityThread.access$1300(ActivityThread.java:219)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)`

**Koin project used and used version (please complete the following information):**
`koin-core version 2.1.6`

**Comment by egorikftp** [comment]
Please try to find information in closed issues before submitting a new one)

https://github.com/InsertKoinIO/koin/issues/871

**Comment by rahulr4** [comment]
@egorikftp  Yes i checked that but was unable to find a definitive solution.
Can you provide a definite solution ?
