### ISSUE TITLE
p.a.b.i.b: Could not create instance for [Single:'i.b.a.l.f.a']

### ISSUE THREAD

**Issue by FrancescoBonizzi** [InsertKoinIO/koin#915]
**Describe the bug**

Sometimes while resuming an activity (on Android 7), I get this error:
```
Fatal Exception: java.lang.RuntimeException: Unable to resume activity {com.francescobonizzi.invoiceEstimateReceiptMaker/com.francescobonizzi.invoiceEstimateReceiptMaker.pages.MainActivity}: p.a.b.i.b: Could not create instance for [Single:'i.b.a.l.f.a']
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3421)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3461)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2730)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6123)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
```
What is Single:'i.b.a.l.f.a'?

**To Reproduce**
I cannot reproduce it when I want, because It happens often with Google Play automatic emulator tests.

My `MainActivity `declarations are:

```
class MainActivity : AppCompatActivity()
{
    private lateinit var _navigationHost: NavController
    private val _logger: ILogger by inject()

    private var _alreadyCheckedForPurchases: Boolean = false
    private lateinit var _billingHandler: BillingHandler
...
```

**Koin project used and used version (please complete the following information):**
org.koin:koin-android:2.1.6

**Comment by rpavliuk** [comment]
Got the same issue on my build, but for me, it occurs only with obfuscation ON.
The faulty instance which cannot be created has a constructor with two parameters: Application and String. The Application parameter is the only difference between other instances which are created successfully.

**Comment by OsinniyApps** [comment]
Try to off proguard

**Comment by james04gr** [comment]
I was having the same issue. My problem was that i had a single that returned null.

**Comment by rpavliuk** [comment]
Agree with @james04gr . I got an exception while creating instance. That's why Koin couldn't create it.
@OsinniyApps sorry, but this is not the case when you need a proguard)
