### ISSUE TITLE
Koin noSuchMethodError exception

### ISSUE THREAD

**Issue by rahulr4** [InsertKoinIO/koin#917]
**Describe the bug**
After updating koin, i am getting noSuchMethodError.

**To Reproduce**
1. Update Koin to 2.1.6
2. Kotlin verion : 1.4.10
3. Test case fails
4. `java.lang.NoSuchMethodError: kotlin.time.TimeMark.elapsedNow()D

	at org.koin.core.time.MeasureKt.measureDuration(Measure.kt:36)
	at org.koin.core.KoinApplication.modules(KoinApplication.kt:60)
	at com.dmi.artbasel.app.KoinInit$Companion$initialize$1$1.invoke(KoinInit.kt:16)
	at com.dmi.artbasel.app.KoinInit$Companion$initialize$1$1.invoke(KoinInit.kt:9)
	at org.koin.core.context.ContextFunctionsKt.startKoin(ContextFunctions.kt:39)
	at org.koin.core.context.ContextFunctionsKt.startKoin$default(ContextFunctions.kt:35)
	at com.dmi.artbasel.app.KoinInit$Companion.initialize(KoinInit.kt:13)
	at com.dmi.artbasel.app.KoinInit.initialize(KoinInit.kt)
	at com.dmi.artbasel.app.ArtBaselApplication.onCreate(ArtBaselApplication.java:104)
	at com.dmi.artbasel.test.ArtBaselTestApplication.onCreate(ArtBaselTestApplication.java:16)
	at org.robolectric.android.internal.AndroidEnvironment.lambda$installAndCreateApplication$0(AndroidEnvironment.java:253)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:75)
	at org.robolectric.android.internal.AndroidEnvironment.installAndCreateApplication(AndroidEnvironment.java:253)
	at org.robolectric.android.internal.AndroidEnvironment.setUpApplicationState(AndroidEnvironment.java:149)
	at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:298)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:247)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

**Expected behavior**
Test cases should pass like before

**Comment by OsinniyApps** [comment]
This method should be in kotlin stdlib _1.4.10_

**Comment by jeziellago** [comment]
Hi @rahulr4 
Duplicated #871 
You can update to Release Candidate version `2.2.0-rc-3`, it was fixed here: https://github.com/InsertKoinIO/koin/blob/master/CHANGELOG.md#user-content-220-beta-1:~:text=fixed%20time%20API%20%2D%20Kotlin%201.4
