### ISSUE TITLE
no root scoped initilaised

### ISSUE THREAD

**Issue by jonneymendoza** [InsertKoinIO/koin#941]
**Describe the bug**
HI i am getting a no root scoped initialised error when trying to use get() to retrieve the dpednency paramter of my object,

**To Reproduce**

```class MainViewModel constructor(private val getFootballTeamUseCase: GetFootballTeamUseCase)  : ViewModel(){

    fun getFootballTeams(): List<String> {
        return getFootballTeamUseCase.getFootballTeams()
    }
}
```

```

object DependencyGraph : IocContract, KoinComponent {

    override fun createUiDependency() {
        IOCModule.addViewModelModule(MainViewModel(get()))
    }

    fun getAllModules(): List<Module> {
        createUiDependency()
        createUseCaseDependency()
        createMainAppDependency()
        createRepoDependency()
        createNetworkDependency()

        return IOCModule.iocModuleList.toList()
    }
}```


```object IOCModule {
    val iocModuleList = mutableListOf<Module>()
    inline fun <reified T> addFactoryModule(t: T) {
        iocModuleList.add(module { factory { t } })
    }

    inline fun <reified T> addSingleModule(t: T) {
        iocModuleList.add(module { single { t } })
    }

    inline fun <reified T : ViewModel> addViewModelModule(viewModel: T) {
        iocModuleList.add(module { viewModel { viewModel } })
    }
}
```
**Expected behavior**
compile and laod the dependency

**Koin project used and used version (please complete the following information):**
 [e.g]: `koin-core version 2.1.6`

Error below

``` java.lang.RuntimeException: Unable to create application com.jonathan.MainApplication: java.lang.IllegalStateException: No root scoped initialized
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5876)
        at android.app.ActivityThread.access$1100(ActivityThread.java:199)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.IllegalStateException: No root scoped initialized
        at org.koin.core.registry.ScopeRegistry.getRootScope(ScopeRegistry.kt:48)
        at com.jonathan.DependencyGraph.createUiDependency(DependencyGraph.kt:46)```

**Comment by maikotrindade** [comment]
Is that still happening? @jonneymendoza
