### ISSUE TITLE
LoadKoin not working for unit tests

### ISSUE THREAD

**Issue by jonneymendoza** [InsertKoinIO/koin#947]
**Describe the bug**

```java.lang.IllegalStateException: No Koin Context configured. Please use startKoin or koinApplication DSL. 

	at org.koin.core.context.KoinContextHandler.getContext(KoinContextHandler.kt:29)
	at org.koin.core.context.KoinContextHandler.get(KoinContextHandler.kt:35)
	at org.koin.core.context.ContextFunctionsKt.loadKoinModules(ContextFunctions.kt:60)
```

**To Reproduce**
1. Run a simple junit test

**Expected behavior**
load my koin dependencies before running a test

**Koin project used and used version (please complete the following information):**
`    testImplementation 'org.koin:koin-test:2.1.5'` 

```
   def koin_version = "2.1.6"
    // Koin AndroidX Scope features
    implementation "org.koin:koin-androidx-scope:$koin_version"
    // Koin AndroidX ViewModel features
    implementation "org.koin:koin-androidx-viewmodel:$koin_version"
    // Koin AndroidX Fragment features
    implementation "org.koin:koin-androidx-fragment:$koin_version"
    // Koin AndroidX Experimental features
    implementation "org.koin:koin-androidx-ext:$koin_version"
```

**Additional moduleDefinition**
test code:

```
  val networkHelper: NetworkHelperContract by inject()
    val showTopRatingUseCase: ShowTopRatingUseCase by inject()

    @get:Rule
    var rule: TestRule = InstantTaskExecutorRule()

    @Before
    fun setUp() {
         loadKoinModules(listOf(TestModule.getTestModules()))
    }

    @After
    fun tearDown() {
    }

    @Test
    fun getTopRatedMovies() {`
/////
```

```
object TestModule {
    fun getTestModules() = module {
        factory<MovieRepositoryContract> { MovieRepository(get()) }
        single<NetworkHelperContract> { NetworkTestHelper() }
        single<MovieNetworkControllerContract> { MovieNetworkController(get()) }
        factory { ShowTopRatingUseCase(get()) }
    }
}
```

**Comment by arnaudgiuliani** [comment]
why not statr Koin completly?
