### ISSUE TITLE
Scoped injecting issue.

### ISSUE THREAD

**Issue by m1chal-z** [InsertKoinIO/koin#948]
Koin version 2.2.0
```
 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.osn.go.debug/com.osn.go.ui.mainactivity.MainActivity}: java.lang.IllegalStateException: Your activity is not yet attached to the Application instance. You can't request ViewModel before onCreate call.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3449)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.IllegalStateException: Your activity is not yet attached to the Application instance. You can't request ViewModel before onCreate call.
```

MainActivity code:
```
class MainActivity : ScopeActivity() {
    private val mainActivityConfigurator: MainActivityConfigurator by inject()
[...]
    override fun applyOverrideConfiguration(overrideConfiguration: Configuration) {
        super.applyOverrideConfiguration(getUpdatedConfig(overrideConfiguration))
    }

    private fun getUpdatedConfig(config: Configuration): Configuration {
        if (!config.locales.isEmpty) {
            return config
        }

        val locale = Locale(mainActivityConfigurator.getDisplayLanguage())
        config.setLocale(locale)
        return config
    }
```

module object:
```
val mainActivityModule = module {
    scope(named<MainActivity>()) {
        scoped { MainActivityConfigurator(get(), get(), get(), get(), get()) }
    }
}
```

Problem not occurs in 2.2.0-rc2 version

**Comment by arnaudgiuliani** [comment]
Yes, the scope is based on ViewModel backer. As your data need to be injected earlier, you can have a "standard" scope:

```kotlin
class MainActivity : KoinScopeComponent {

override val scope by lazy { newScope() }

```

Be sure to inject with the `KoinScopeComponent` extension.
