### ISSUE TITLE
Can't reproduce the getting start junit setup

### ISSUE THREAD

**Issue by ermoca** [InsertKoinIO/koin#957]
**Describe the bug**
When trying to reproduce the test example the result I get is : 

```
"java.lang.IllegalStateException: KoinApplication has not been started
	at org.koin.core.context.GlobalContext.get(GlobalContext.kt:35)
	at org.koin.core.component.KoinComponent$DefaultImpls.getKoin(KoinComponent.kt:39)
	at org.koin.test.KoinTest$DefaultImpls.getKoin(KoinTest.kt)"
```

and indeed the startKoin is never called during the test process but the documentation says : 

`We use the Koin KoinTestRule rule to start/stop our Koin context`
 
**To Reproduce**

here is the code of my test : 
```
class PersonDaoTest : KoinTest {

    val personDao by inject<IPersonDao>()

    @get:Rule
    val koinTestRule = KoinTestRule.create {
        printLogger()
        modules(app_module, dbAccessTest_module)
    }

    @Test fun testInsertTwoIdenticalPerson() {
        val person1 = Person("anna", "ahahahahah", "anna@mail.eu")
        val storedPerson = personDao.insert(person1)
        assertEquals(person1.id, storedPerson?.id)
    }
}
```

The dependencies injection is working for the main app so I figured the problem must be in this class and not in the setup of the modules.

**Expected behavior**
I would like for the test to pass. 

I found a workaround with the following code : 

```
class PersonDaoTest : KoinTest {

    val personDao by inject<IPersonDao>()

    @BeforeEach fun injectDependencies(){
        startKoin{
            printLogger()
            modules(dbAccessTest_module, app_module)
        }
    }

    @Test fun testInsertTwoIdenticalPerson() {
        val person1 = Person("anna", "ahahahahah", "anna@mail.eu")
        val storedPerson = personDao.insert(person1)
        assertEquals(person1.id, storedPerson?.id)
    }
}
```

but I would prefer to do it the "right way" if you can see what I did wrong when using the @get:Rule
Thanks for you work with Koin and by advance for your answer.
Have a nive day 

**Koin project used and used version (please complete the following information):**
 `koin-core version 2.2.1`

**Comment by arnaudgiuliani** [comment]
weird, is it from the getting stared?

**Comment by ermoca** [comment]
This is my code but yes I basically just followed the getting started.

**Comment by arnaudgiuliani** [comment]
could be outdated somehow 🤔

**Comment by lucasctd** [comment]
@ermoca were u able to get this working?
I tried to follow the documentation but it doesn't work.

Tried the example for [JUnit 5 ](https://insert-koin.io/docs/reference/koin-test/testing/#writing-tests) and the [first example of the page](https://insert-koin.io/docs/reference/koin-test/testing/#writing-tests)

I am getting `java.lang.IllegalStateException: KoinApplication has not been started` with both;
