### ISSUE TITLE
ViewModel has no zero argument constructor

### ISSUE THREAD

**Issue by alorma** [InsertKoinIO/koin#959]
**Describe the bug**
Somehow the creation of VIewModel is not working, as it produces a `java.lang.Class<com.alorma.gitskarios.screen.notifications.NotificationsViewModel> has no zero argument constructor`

**To Reproduce**

My module:

```kotlin
class NotificationsViewModel(private val restApi: RestApi): ViewModel()
```

```kotlin
object ViewModelModule {

    operator fun invoke() = module {
        viewModel {
            NotificationsViewModel(restApi = get())
        }
    }
}
```

**Expected behavior**

**Koin project used and used version (please complete the following information):**
Koin version 2.2.1

**Demo repository**

https://github.com/gitskarios/Android-Compose

**Comment by arnaudgiuliani** [comment]
can we you provide the whole stack call, and code that is using that. thanks

**Comment by alorma** [comment]
Stacktrace:

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.alorma.gitskarios, PID: 14165
    java.lang.RuntimeException: Cannot create an instance of class com.alorma.gitskarios.screen.notifications.NotificationsViewModel
        at androidx.lifecycle.ViewModelProvider$NewInstanceFactory.create(ViewModelProvider.java:221)
        at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.java:278)
        at androidx.lifecycle.SavedStateViewModelFactory.create(SavedStateViewModelFactory.java:112)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:185)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:150)
        at androidx.compose.ui.viewinterop.ViewModelKt.get(ViewModel.kt:75)
        at androidx.compose.ui.viewinterop.ViewModelKt.viewModel(ViewModel.kt:60)
        at com.alorma.gitskarios.screen.notifications.NotificationsScreenKt.NotificationsScreen(NotificationsScreen.kt:114)
        at com.alorma.gitskarios.MainActivity$onCreate$1$1.invoke(MainActivity.kt:15)
        at com.alorma.gitskarios.MainActivity$onCreate$1$1.invoke(Unknown Source:10)
        at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:144)
        at androidx.compose.runtime.internal.ComposableLambda.invoke(Unknown Source:10)
        at androidx.compose.runtime.AmbientKt.Providers(Ambient.kt:175)
        at androidx.compose.foundation.TextKt.ProvideTextStyle(Text.kt:247)
        at androidx.compose.material.MaterialThemeKt$MaterialTheme$1.invoke(MaterialTheme.kt:72)
        at androidx.compose.material.MaterialThemeKt$MaterialTheme$1.invoke(Unknown Source:10)
        at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:144)
        at androidx.compose.runtime.internal.ComposableLambda.invoke(Unknown Source:10)
        at androidx.compose.runtime.AmbientKt.Providers(Ambient.kt:175)
        at androidx.compose.material.MaterialThemeKt.MaterialTheme(MaterialTheme.kt:66)
        at com.alorma.gitskarios.ui.ThemeKt.GitskariosTheme(Theme.kt:30)
        at com.alorma.gitskarios.MainActivity$onCreate$1.invoke(MainActivity.kt:14)
        at com.alorma.gitskarios.MainActivity$onCreate$1.invoke(Unknown Source:10)
        at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:144)
        at androidx.compose.runtime.internal.ComposableLambda.invoke(Unknown Source:10)
        at androidx.compose.runtime.AmbientKt.Providers(Ambient.kt:175)
        at androidx.compose.ui.platform.AmbientsKt.ProvideCommonAmbients(Ambients.kt:113)
        at androidx.compose.ui.platform.AndroidAmbientsKt$ProvideAndroidAmbients$3.invoke(AndroidAmbients.kt:105)
        at androidx.compose.ui.platform.AndroidAmbientsKt$ProvideAndroidAmbients$3.invoke(Unknown Source:10)
        at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:144)
        at androidx.compose.runtime.internal.ComposableLambda.invoke(Unknown Source:10)
        at androidx.compose.runtime.AmbientKt.Providers(Ambient.kt:175)
        at androidx.compose.ui.platform.AndroidAmbientsKt.ProvideAndroidAmbients(AndroidAmbients.kt:97)
        at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$1.invoke(Wrapper.kt:240)
        at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$1.invoke(Unknown Source:10)
        at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:144)
        at androidx.compose.runtime.internal.ComposableLambda.invoke(Unknown Source:10)
        at androidx.compose.runtime.AmbientKt.Providers(Ambient.kt:175)
        at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Wrapper.kt:239)
        at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Unknown Source:10)
        at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:144)
        at androidx.compose.runtime.internal.ComposableLambda.invoke(Unknown Source:10)
        at androidx.compose.runtime.ComposerKt.invokeComposable(Composer.kt:2720)
        at androidx.compose.runtime.Composer.composeInitial(Composer.kt:1880)
        at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(Recomposer.kt:231)
        at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:110)
E/AndroidRuntime:     at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.kt:233)
        at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Unknown Source:3)
        at androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow(AndroidComposeView.kt:614)
        at android.view.View.dispatchAttachedToWindow(View.java:19553)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3430)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2028)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1721)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7598)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:966)
        at android.view.Choreographer.doCallbacks(Choreographer.java:790)
        at android.view.Choreographer.doFrame(Choreographer.java:725)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:951)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.InstantiationException: java.lang.Class<com.alorma.gitskarios.screen.notifications.NotificationsViewModel> has no zero argument constructor
        at java.lang.Class.newInstance(Native Method)
        at androidx.lifecycle.ViewModelProvider$NewInstanceFactory.create(ViewModelProvider.java:219)
        	... 69 more
```

Code:

```kotlin
object ViewModelModule {

    operator fun invoke() = module {
        viewModel {
            NotificationsViewModel(get())
        }
    }
}
```

```kotlin
class NotificationsViewModel(
    private val obtainUserNotificationsUseCase: ObtainUserNotificationsUseCase,
) : ViewModel()
```

```kotlin
@Composable
fun NotificationsScreen(
    notificationsViewModel: NotificationsViewModel = ViewModel(),
) { ... }
```

**Comment by makaronis** [comment]
i have a same issue

**Comment by musotec** [comment]
I am getting this as well (not using android compose), in version 2.2.0-rc1
It is working fine for ViewModels instantiated via delegate `viewModels()` from an Activity, but fails for the same delegate from a Fragment. 

Additional info: The dependency I am injecting is a Singleton that has the androidApplication scope provided to it.

**Comment by arnaudgiuliani** [comment]
you need to use `getViewModel()` and not any lazy expression here

**Comment by arnaudgiuliani** [comment]
Injected parameters & StateViewModel API has been restored in 3.0.1, with consistent factory resolution.  Please try with this version. Else wait for 2.3.0

**Comment by akshat-sahijpal** [comment]
Same issue

**Comment by karvinok** [comment]
> Injected parameters & StateViewModel API has been restored in 3.0.1, with consistent factory resolution. Please try with this version. Else wait for 2.3.0

Still not working for me on 3.0.1

**Comment by mwshubham** [comment]
This happens with Dagger as well.

**Comment by CodyEddings** [comment]
Is the solution to make a ViewModelFactory?

**Comment by CodyEddings** [comment]
For anyone reading this: there is a solution with Koin to get over the `no zero arg constructor` exception without needing to make your own ViewModelFactory class.

Using `private val yourViewModel: YourViewModel by sharedViewModel()` does the trick. Solution taken from [here](https://stackoverflow.com/questions/60223209/get-the-same-instance-of-viewmodel-in-fragment-which-is-defined-in-activity-with).
