### ISSUE TITLE
Random NoBeanDefFoundException

### ISSUE THREAD

**Issue by soygabimoreno** [InsertKoinIO/koin#970]
**Describe the bug**
Some `NoBeanDefFoundException` are triggered "randomly".

It usually works OK, but sometimes it fails.

Example of stacktrace:
```
Caused by org.koin.core.error.NoBeanDefFoundException: No definition found for class:'com.jeff.feature.turndetail.presentation.detail.TurnDetailRenderer'. Check your definitions!
       at org.koin.core.scope.Scope.throwDefinitionNotFound(Scope.kt:246)
       at org.koin.core.scope.Scope.resolveInstance(Scope.kt:216)
       at org.koin.core.scope.Scope.get(Scope.kt:181)
       at com.jeff.feature.turndetail.presentation.detail.TurnDetailFragment$$special$$inlined$inject$1.invoke(Scope.kt:396)
       at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81)
       at com.jeff.feature.turndetail.presentation.detail.TurnDetailFragment.getRenderer(:2)
       at com.jeff.feature.turndetail.presentation.detail.TurnDetailFragment.access$getRenderer$p(TurnDetailFragment.kt:34)
       at com.jeff.feature.turndetail.presentation.detail.TurnDetailFragment$turnResId$2.invoke(TurnDetailFragment.kt:75)
       at com.jeff.feature.turndetail.presentation.detail.TurnDetailFragment$turnResId$2.invoke(TurnDetailFragment.kt:34)
       at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
       at com.jeff.feature.turndetail.presentation.detail.TurnDetailFragment.getTurnResId(:2)
       at com.jeff.feature.turndetail.presentation.detail.TurnDetailFragment.setupUI(TurnDetailFragment.kt:103)
       at com.jeff.library.base.presentation.fragment.StatelessJeffViewModelExtFragment.onViewCreated(StatelessJeffViewModelExtFragment.kt:50)
       at com.jeff.library.base.presentation.fragment.JeffViewModelExtFragment.onViewCreated(JeffViewModelExtFragment.kt:19)
       at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:2974)
       at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:550)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:277)
       at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1636)
       at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3112)
       at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3056)
       at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:251)
       at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:473)
       at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:210)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1433)
       at android.app.Activity.performStart(Activity.java:7986)
       at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3677)
       at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
       at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:8167)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

**To Reproduce**
I have not been able to reproduce the error.
I just see the crashes tracked on Crashlytics.

**Expected behavior**
Provide the class all times if it is possible.

**Koin project used and used version (please complete the following information):**
`org.koin:koin-core:2.1.6`
`org.koin:koin-core-ext:2.1.6`
`org.koin:koin-androidx-fragment:2.1.6`
`org.koin:koin-androidx-scope:2.1.6`
`org.koin:koin-androidx-viewmodel:2.1.6`

**Comment by valeriyo** [comment]
This just happened to me as well, also with Koin 2.1.6

The crash occurred only once on Android 6.0.1 (Galaxy J3 Emerge) - and from the log before the crash, I can tell that the same resolution previously worked. So, it looks like it randomly failed. The crash occurred on main thread.

**Comment by rewgoes** [comment]
I have also experienced that with **Koin 2.2.1**.

By the looks of it, it happened right after the app was opened after being in the background for a long time. Probably the process was killed or something.

All I can say is that the module of the bean that was not found, `SearchRequestJsonAdapter`, has nothing to do with `androidx.camera.core.CameraControl`.

So I don't have any idea of what was going on here

```
Start Date: 2021-01-28T04:16:25.194Z
Date: 2021-01-28T08:27:45.183Z

java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:523)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
  Caused by: java.lang.reflect.InvocationTargetException
    at java.lang.reflect.Method.invoke(Method.java:-2)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
    Caused by: androidx.camera.core.CameraControl$OperationCanceledException: Could not create instance for [Factory:'o.cA']
      at org.koin.core.instance.InstanceFactory.create$14a74443(InstanceFactory.java:62)
      at org.koin.core.instance.FactoryInstanceFactory.get$14a74443(FactoryInstanceFactory.java:36)
      at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.java:103)
      at org.koin.core.scope.Scope.resolveInstance(Scope.java:236)
      at org.koin.core.scope.Scope.get(Scope.java:204)
      at org.koin.androidx.viewmodel.factory.StateViewModelFactory.create(StateViewModelFactory.java:21)
      at androidx.lifecycle.AbstractSavedStateViewModelFactory.create(AbstractSavedStateViewModelFactory.java:69)
      at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:185)
      at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:150)
      at org.koin.androidx.viewmodel.ViewModelResolverKt.get(ViewModelResolverKt.java:23)
      at org.koin.androidx.viewmodel.ViewModelResolverKt.resolveInstance(ViewModelResolverKt.java:12)
      at org.koin.androidx.viewmodel.scope.ScopeExtKt.getViewModel(ScopeExtKt.java:86)
      at org.koin.androidx.viewmodel.scope.ScopeExtKt.getViewModel(ScopeExtKt.java:604)
      at org.koin.androidx.viewmodel.koin.KoinExtKt.getViewModel(KoinExtKt.java:41)
      at org.koin.androidx.viewmodel.ext.android.FragmentExtKt.getViewModel(FragmentExtKt.java:71)
      at {my.package}.mobile.ui.dialog.{Class}$$special$$inlined$viewModel$2.invoke({Class}.java:1073)
      at {my.package}.mobile.ui.dialog.{Class}$$special$$inlined$viewModel$2.invoke({Class}.java:73)
      at {my.package}.mobile.ui.dialog.{Class}$$special$$inlined$viewModel$2.invoke({Class}.java)
      at kotlin.UnsafeLazyImpl.getValue(UnsafeLazyImpl.java:81)
      at {my.package}.mobile.ui.dialog.{Class}.getViewModel({Class}.java)
      at {my.package}.mobile.ui.dialog.{Class}.onCreateView({Class}.java:36)
      at androidx.fragment.app.Fragment.onHiddenChanged(Fragment.java:2699)
      at androidx.fragment.app.Fragment.onPrepareOptionsMenu(Fragment.java:2699)
      at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2699)
      at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:320)
      at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1199)
      at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1368)
      at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1446)
      at androidx.fragment.app.FragmentManager.reverseTransit(FragmentManager.java:1509)
      at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1509)
      at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
      at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2181)
      at androidx.fragment.app.FragmentManager.reverseTransit(FragmentManager.java:2181)
      at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2004)
      at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1959)
      at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1861)
      at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413)
      at android.os.Handler.handleCallback(Handler.java:900)
      at android.os.Handler.dispatchMessage(Handler.java:103)
      at android.os.Looper.loop(Looper.java:219)
      at android.app.ActivityThread.main(ActivityThread.java:8347)
      at java.lang.reflect.Method.invoke(Method.java:-2)
      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
      Caused by: org.koin.core.error.NoBeanDefFoundException: No definition found for class:'o.SearchRequestJsonAdapter'. Check your definitions!
        at org.koin.core.scope.Scope.throwDefinitionNotFound(Scope.java:282)
        at org.koin.core.scope.Scope.resolveInstance(Scope.java:251)
        at org.koin.core.scope.Scope.get(Scope.java:204)
        at {my.package}.mobile.di.features.ViewModelModuleKt$viewModelModule$1$14.invoke(ViewModelModuleKt.java:1260)
        at {my.package}.mobile.di.features.ViewModelModuleKt$viewModelModule$1$14.invoke(ViewModelModuleKt.java:260)
        at {my.package}.mobile.di.features.ViewModelModuleKt$viewModelModule$1$14.invoke(ViewModelModuleKt.java)
        at org.koin.core.instance.InstanceFactory.create$14a74443(InstanceFactory.java:53)
        at org.koin.core.instance.FactoryInstanceFactory.get$14a74443(FactoryInstanceFactory.java:36)
        at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.java:103)
        at org.koin.core.scope.Scope.resolveInstance(Scope.java:236)
        at org.koin.core.scope.Scope.get(Scope.java:204)
        at org.koin.androidx.viewmodel.factory.StateViewModelFactory.create(StateViewModelFactory.java:21)
        at androidx.lifecycle.AbstractSavedStateViewModelFactory.create(AbstractSavedStateViewModelFactory.java:69)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:185)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:150)
        at org.koin.androidx.viewmodel.ViewModelResolverKt.get(ViewModelResolverKt.java:23)
        at org.koin.androidx.viewmodel.ViewModelResolverKt.resolveInstance(ViewModelResolverKt.java:12)
        at org.koin.androidx.viewmodel.scope.ScopeExtKt.getViewModel(ScopeExtKt.java:86)
        at org.koin.androidx.viewmodel.scope.ScopeExtKt.getViewModel(ScopeExtKt.java:604)
        at org.koin.androidx.viewmodel.koin.KoinExtKt.getViewModel(KoinExtKt.java:41)
        at org.koin.androidx.viewmodel.ext.android.FragmentExtKt.getViewModel(FragmentExtKt.java:71)
        at {my.package}.mobile.ui.dialog.{Class}$$special$$inlined$viewModel$2.invoke({Class}.java:1073)
        at {my.package}.mobile.ui.dialog.{Class}$$special$$inlined$viewModel$2.invoke({Class}.java:73)
        at {my.package}.mobile.ui.dialog.{Class}$$special$$inlined$viewModel$2.invoke({Class}.java)
        at kotlin.UnsafeLazyImpl.getValue(UnsafeLazyImpl.java:81)
        at {my.package}.mobile.ui.dialog.{Class}.getViewModel({Class}.java)
        at {my.package}.mobile.ui.dialog.{Class}.onCreateView({Class}.java:36)
        at androidx.fragment.app.Fragment.onHiddenChanged(Fragment.java:2699)
        at androidx.fragment.app.Fragment.onPrepareOptionsMenu(Fragment.java:2699)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2699)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:320)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1199)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1368)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1446)
        at androidx.fragment.app.FragmentManager.reverseTransit(FragmentManager.java:1509)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1509)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
        at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2181)
        at androidx.fragment.app.FragmentManager.reverseTransit(FragmentManager.java:2181)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2004)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1959)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1861)
        at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413)
        at android.os.Handler.handleCallback(Handler.java:900)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8347)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
```

**Comment by batadamnjanovic** [comment]
@rewgoes, Same here.

This is probably happening because the system kills the app (process death).

Steps to reproduce:
- Minimize the app (put in the background)
- Go to LogCat window and click on Terminate Application
- Then, reopen the app (click on Launcher icon)

I am currently on this and I don't know how to overcome it.

**Comment by batadamnjanovic** [comment]
So, the SavedStateHandle parameter must be the first parameter in the class where you inject it...

**Comment by rewgoes** [comment]
> So, the SavedStateHandle parameter must be the first parameter in the class where you inject it.
> 
> Now it works.

`SavedStateHandle` is already the first parameter for all `ViewModel`s that use it. I also think that this is something related to the app being in the background for too long, however, I've tried "simulating" that they way that you've said and I can't reproduce the crash. I also tried by enabling "Don't keep activities".

It only happened just a couple of times in production.

**Comment by valeriyo** [comment]
This happens when the app is restoring its saved state - from `android.app.ActivityThread.main` at the top of callstack, and by that time the Scope instance (where `org.koin.core.scope.Scope.resolveInstance` fails) has been created already.

Does Koin do anything asynchronously?

**Comment by Raghuramchowdary-tech** [comment]
Happening to me as well, any work around

**Comment by zhengxiaopeng** [comment]
Same issues...

**Comment by rafaelbradesco** [comment]
Same issue.
For us, it only occurs in new devices.

**Comment by andrewjapar** [comment]
Happening to me as well using `koin 2.1.6`. Any workaround for this issue?

**Comment by sher-loki** [comment]
Same issues... Don't know what to do ...

**Comment by sher-loki** [comment]
Same issues... Don't know what to do ...

**Comment by DenysZP** [comment]
It looks like a fragment is being restored along with an application. And, apparently, the fragment does it faster than the initialization of the Koin and its dependencies.
Therefore, you can try several options:
https://stackoverflow.com/questions/15519214/prevent-fragment-recovery-in-android
