### ISSUE TITLE
NoBeanDefFoundException: No defenition found for ListenableWorker

### ISSUE THREAD

**Issue by P1NG2WIN** [InsertKoinIO/koin#979]
**Describe the bug**
Very ofter my app crashes on boot with `NoBeanDefFoundException: No defenition found for ListenableWorker`

My Koin Settings 
```
        startKoin {
            androidContext(this@SubApplication)
            androidLogger(Level.ERROR)
            androidFileProperties()
            workManagerFactory()
            modules(listOf(
                AppModules.appModule(),
                NetworkModule.okHttpModule(),
                NetworkModule.retrofitModule(),
                NetworkModule.scarletModule(),
                AppModules.repoModule(),
                WorkersModule.workersModule(),
                DatabaseModule.appDatabaseModule(),
                ViewModelsModule.viewModelModule(),
            ))
        }
```

```
object WorkersModule {

    fun workersModule() = module {
        worker { SendLocationsWorker(androidContext(), get(), get(), get(), get()) }
        worker { UpdateDeviceInfoWorker(androidContext(), get(), get()) }
    }

}
```

**To Reproduce**
I don't know, this error appears intermittently. My workers use repositories from `AppModules.repoModule()`

**Koin project used and used version (please complete the following information):**
```
    def koin_version = "2.2.1"
    api("org.koin:koin-core:$koin_version")
    api("org.koin:koin-core-ext:$koin_version")
    testApi("org.koin:koin-test:$koin_version")
    api("org.koin:koin-androidx-scope:$koin_version")
    api("org.koin:koin-androidx-viewmodel:$koin_version")
    api("org.koin:koin-androidx-fragment:$koin_version")
    api("org.koin:koin-androidx-workmanager:$koin_version")
    api("org.koin:koin-androidx-ext:$koin_version")
```

**Comment by P1NG2WIN** [comment]
`${applicationId}` in manifest is it just stub or string interpolation?

```
<provider
    android:name="androidx.work.impl.WorkManagerInitializer"
    android:authorities="${applicationId}.workmanager-init"
    tools:node="remove" />
```

**Comment by P1NG2WIN** [comment]
Any help on it? Still quite often got this error on app start


```
E/WM-DelegatingWkrFctry: Unable to instantiate a ListenableWorker (com.ping2win.app.location.worker.DetectLocationWorker)
    org.koin.core.error.NoBeanDefFoundException: No definition found for class:'androidx.work.ListenableWorker' & qualifier:'com.ping2win.app.location.worker.DetectLocationWorker'. Check your definitions!
        at org.koin.core.scope.Scope.throwDefinitionNotFound(Scope.kt:282)
        at org.koin.core.scope.Scope.resolveInstance(Scope.kt:251)
        at org.koin.core.scope.Scope.get(Scope.kt:204)
        at org.koin.androidx.workmanager.factory.KoinWorkerFactory.createWorker(KoinWorkerFactory.kt:49)
        at androidx.work.DelegatingWorkerFactory.createWorker(DelegatingWorkerFactory.java:71)
        at androidx.work.WorkerFactory.createWorkerWithDefaultFallback(WorkerFactory.java:83)
        at androidx.work.impl.WorkerWrapper.runWorker(WorkerWrapper.java:242)
        at androidx.work.impl.WorkerWrapper.run(WorkerWrapper.java:136)
        at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
```

**Comment by P1NG2WIN** [comment]
Worker

```
class DetectLocationWorker(
    appContext: Context,
    workerParams: WorkerParameters,
    private val locationDetectSource: LocationDetectSource,
    private val localLocationPreferences: LocalLocationPreferences,
    private val locationSettingReceiver: LocationSettingReceiver
): CoroutineWorker(appContext, workerParams) {...}
```

init koin code in CustomApplication
```

    override fun onCreate() {
        super.onCreate()
        initTimber()
        Timber.d("Lifecycle - onCreate")

        initKoin()

    }

    private fun initKoin() {
        startKoin {
            androidContext(this@SubApplication)
            androidLogger(Level.ERROR)
            androidFileProperties()
            workManagerFactory()
            modules(listOf(
                AppModules.appModule(),
                NetworkModule.okHttpModule(),
                NetworkModule.retrofitModule(),
                NetworkModule.webSocketModule(),
                AppModules.repoModule(),
                WorkersModule.workersModule(),
                DatabaseModule.appDatabaseModule(),
                ViewModelsModule.viewModelModule(),
            ))
        }
    }

```

**Comment by P1NG2WIN** [comment]
@arnaudgiuliani maybe you can help me?

**Comment by P1NG2WIN** [comment]
still every second launch - crash

**Comment by jaimegc** [comment]
I have the same problem! The error appears intermittently as you said. Can you create a bug report?

**Comment by valentynsmetanin** [comment]
Issue isn't gone! Still reproducing with Koin `2.2.1`

**Comment by valentynsmetanin** [comment]
@P1NG2WIN as an option try to delete `build` folder in your project, make Clean and Invalidate Caches/Restart

**Comment by valentynsmetanin** [comment]
@arnaudgiuliani starts reproducing after any unhandled exception in ListenableWorker. Hope it's helpful.

**Comment by P1NG2WIN** [comment]
As workaround, remove koin custom worker factory and extend KoinComponent interface in workers

**Comment by ak47ex** [comment]
@P1NG2WIN is it happens on clean install? Is it possible that your worker `DetectLocationWorker` has been called in some definition in module declared above `workersModule`?

**Comment by P1NG2WIN** [comment]
> @P1NG2WIN is it happens on clean install? Is it possible that your worker `DetectLocationWorker` has been called in some definition in module declared above `workersModule`?

Actually, I migrate to the KoinComponent almost immediately after these errors appeared. However, workers were only called from repositories whose module was placed below the worker module inside koin initialization.

**Comment by valentynsmetanin** [comment]
@arnaudgiuliani are there any fixes for it in latest version?

**Comment by arnaudgiuliani** [comment]
The factory has been fixed in the latest 3.0.1. I would need more feedback to be sure 👍 I prefer to let reopen a new issue if needed

**Comment by alessandroToninelli** [comment]
the exception occurs in 3.1.0 and not in 3.0.1

Caused by: org.koin.core.error.NoBeanDefFoundException: No definition found for class:'androidx.work.WorkerParameters'. Check your definitions!

`2021-06-22 11:06:53.659 21215-21253/com.toninelli.ton_icat E/[Koin]: Instance creation error : could not create instance for [Factory:'com.toninelli.ton_icat.data.worker.SyncArticlesWorker',qualifier:q:'com.toninelli.ton_icat.data.worker.SyncArticlesWorker',binds:androidx.work.ListenableWorker]: org.koin.core.error.NoBeanDefFoundException: No definition found for class:'androidx.work.WorkerParameters'. Check your definitions!
    	org.koin.core.scope.Scope.throwDefinitionNotFound(Scope.kt:240)
    	org.koin.core.scope.Scope.resolveInstance(Scope.kt:209)
    	org.koin.core.scope.Scope.get(Scope.kt:188)
    	com.toninelli.ton_icat.di.DataInjection$workerModule$1$2.invoke(DataInjection.kt:148)
    	com.toninelli.ton_icat.di.DataInjection$workerModule$1$2.invoke(DataInjection.kt:132)
    	org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:57)
    	org.koin.core.instance.FactoryInstanceFactory.get(FactoryInstanceFactory.kt:38)
    	org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:94)
    	org.koin.core.scope.Scope.resolveInstance(Scope.kt:202)
    	org.koin.core.scope.Scope.get(Scope.kt:188)
    	org.koin.core.scope.Scope.getOrNull(Scope.kt:156)
    	org.koin.androidx.workmanager.factory.KoinWorkerFactory.createWorker(KoinWorkerFactory.kt:47)
    	androidx.work.DelegatingWorkerFactory.createWorker(DelegatingWorkerFactory.java:71)
    	androidx.work.WorkerFactory.createWorkerWithDefaultFallback(WorkerFactory.java:83)
    	androidx.work.impl.WorkerWrapper.runWorker(WorkerWrapper.java:244)
    	androidx.work.impl.WorkerWrapper.run(WorkerWrapper.java:136)
    	androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
    	java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    	java.lang.Thread.run(Thread.java:764)
2021-06-22 11:06:53.662 21215-21253/com.toninelli.ton_icat E/WM-DelegatingWkrFctry: Unable to instantiate a ListenableWorker (com.toninelli.ton_icat.data.worker.SyncArticlesWorker)
    org.koin.core.error.InstanceCreationException: Could not create instance for [Factory:'com.toninelli.ton_icat.data.worker.SyncArticlesWorker',qualifier:q:'com.toninelli.ton_icat.data.worker.SyncArticlesWorker',binds:androidx.work.ListenableWorker]
        at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:64)
        at org.koin.core.instance.FactoryInstanceFactory.get(FactoryInstanceFactory.kt:38)
        at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:94)
        at org.koin.core.scope.Scope.resolveInstance(Scope.kt:202)
        at org.koin.core.scope.Scope.get(Scope.kt:188)
        at org.koin.core.scope.Scope.getOrNull(Scope.kt:156)
        at org.koin.androidx.workmanager.factory.KoinWorkerFactory.createWorker(KoinWorkerFactory.kt:47)
        at androidx.work.DelegatingWorkerFactory.createWorker(DelegatingWorkerFactory.java:71)
        at androidx.work.WorkerFactory.createWorkerWithDefaultFallback(WorkerFactory.java:83)
        at androidx.work.impl.WorkerWrapper.runWorker(WorkerWrapper.java:244)
        at androidx.work.impl.WorkerWrapper.run(WorkerWrapper.java:136)
        at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: org.koin.core.error.NoBeanDefFoundException: No definition found for class:'androidx.work.WorkerParameters'. Check your definitions!
        at org.koin.core.scope.Scope.throwDefinitionNotFound(Scope.kt:240)
        at org.koin.core.scope.Scope.resolveInstance(Scope.kt:209)
        at org.koin.core.scope.Scope.get(Scope.kt:188)
        at com.toninelli.ton_icat.di.DataInjection$workerModule$1$2.invoke(DataInjection.kt:148)
        at com.toninelli.ton_icat.di.DataInjection$workerModule$1$2.invoke(DataInjection.kt:132)
        at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:57)
        at org.koin.core.instance.FactoryInstanceFactory.get(FactoryInstanceFactory.kt:38) 
        at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:94) 
        at org.koin.core.scope.Scope.resolveInstance(Scope.kt:202) 
        at org.koin.core.scope.Scope.get(Scope.kt:188) 
        at org.koin.core.scope.Scope.getOrNull(Scope.kt:156) 
        at org.koin.androidx.workmanager.factory.KoinWorkerFactory.createWorker(KoinWorkerFactory.kt:47) 
        at androidx.work.DelegatingWorkerFactory.createWorker(DelegatingWorkerFactory.java:71) 
        at androidx.work.WorkerFactory.createWorkerWithDefaultFallback(WorkerFactory.java:83) 
        at androidx.work.impl.WorkerWrapper.runWorker(WorkerWrapper.java:244) 
        at androidx.work.impl.WorkerWrapper.run(WorkerWrapper.java:136) 
        at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
2021-06-22 11:06:53.664 21215-21253/com.toninelli.ton_icat E/AndroidRuntime: FATAL EXCEPTION: pool-10-thread-2
    Process: com.toninelli.ton_icat, PID: 21215
    java.lang.Error: org.koin.core.error.InstanceCreationException: Could not create instance for [Factory:'com.toninelli.ton_icat.data.worker.SyncArticlesWorker',qualifier:q:'com.toninelli.ton_icat.data.worker.SyncArticlesWorker',binds:androidx.work.ListenableWorker]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1173)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: org.koin.core.error.InstanceCreationException: Could not create instance for [Factory:'com.toninelli.ton_icat.data.worker.SyncArticlesWorker',qualifier:q:'com.toninelli.ton_icat.data.worker.SyncArticlesWorker',binds:androidx.work.ListenableWorker]
        at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:64)
        at org.koin.core.instance.FactoryInstanceFactory.get(FactoryInstanceFactory.kt:38)
        at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:94)
        at org.koin.core.scope.Scope.resolveInstance(Scope.kt:202)
        at org.koin.core.scope.Scope.get(Scope.kt:188)
        at org.koin.core.scope.Scope.getOrNull(Scope.kt:156)
        at org.koin.androidx.workmanager.factory.KoinWorkerFactory.createWorker(KoinWorkerFactory.kt:47)
        at androidx.work.DelegatingWorkerFactory.createWorker(DelegatingWorkerFactory.java:71)
        at androidx.work.WorkerFactory.createWorkerWithDefaultFallback(WorkerFactory.java:83)
        at androidx.work.impl.WorkerWrapper.runWorker(WorkerWrapper.java:244)
        at androidx.work.impl.WorkerWrapper.run(WorkerWrapper.java:136)
        at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
     Caused by: org.koin.core.error.NoBeanDefFoundException: No definition found for class:'androidx.work.WorkerParameters'. Check your definitions!
        at org.koin.core.scope.Scope.throwDefinitionNotFound(Scope.kt:240)
        at org.koin.core.scope.Scope.resolveInstance(Scope.kt:209)
        at org.koin.core.scope.Scope.get(Scope.kt:188)
        at com.toninelli.ton_icat.di.DataInjection$workerModule$1$2.invoke(DataInjection.kt:148)
        at com.toninelli.ton_icat.di.DataInjection$workerModule$1$2.invoke(DataInjection.kt:132)
        at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:57)
        at org.koin.core.instance.FactoryInstanceFactory.get(FactoryInstanceFactory.kt:38) 
        at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:94) 
        at org.koin.core.scope.Scope.resolveInstance(Scope.kt:202) 
        at org.koin.core.scope.Scope.get(Scope.kt:188) 
        at org.koin.core.scope.Scope.getOrNull(Scope.kt:156) 
        at org.koin.androidx.workmanager.factory.KoinWorkerFactory.createWorker(KoinWorkerFactory.kt:47) 
        at androidx.work.DelegatingWorkerFactory.createWorker(DelegatingWorkerFactory.java:71) 
        at androidx.work.WorkerFactory.createWorkerWithDefaultFallback(WorkerFactory.java:83) 
        at androidx.work.impl.WorkerWrapper.runWorker(WorkerWrapper.java:244) 
        at androidx.work.impl.WorkerWrapper.run(WorkerWrapper.java:136) 
        at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) `

My worker extends just CoroutineWorker

`worker { SyncArticlesWorker(get(), get() }`

**Comment by arnaudgiuliani** [comment]
3.1.1 will fix back parameter resolution graph. It's almost ready 👍

**Comment by alessandroToninelli** [comment]
this work, I always need to specify WorkParameters like this


 ` worker {params ->
           SyncArticlesWorker(get(), params[0] ) }`
