### ISSUE TITLE
Crash by not founded definitions after migrating to 2.2.2 from 2.0.1

### ISSUE THREAD

**Issue by nikiJava** [InsertKoinIO/koin#985]
**Describe the bug**
Crashes occurred after upgrading from 2.0.1 to 2.2.2.

In my project I have:

**BaseFragment**
```
open class BaseFragment(
    val qualifier: String
) : Fragment() {
    protected val router: AppRouter by inject(named("${qualifier}_ROUTER"))
}
```

`const val SCREEN_A_QUALIFIER = "SCREEN_A"
`

`class ScreenAFragment : BaseFragment(qualifier = SCREEN_A_QUALIFIER)
`

**AppRouter** for navigation
`open class AppRouter
`

**ScreenARouter** is a router for ScreenA
`class ScreenARouter : AppRouter
`

```
val screenAModule = module {
    val routerQualifier = named("${SCREEN_A_QUALIFIER}_ROUTER")
    single(routerQualifier) {
        ScreenARouter()
    }
}
```

screenAModule is loaded at app startup in Application class.

**Expected behavior**
On version 2.0.1 I had no crashes and dependencies resolved correctly.
But after updating on 2.2.2 I get a crash that definitions not founded:
```
 Caused by: org.koin.core.error.NoBeanDefFoundException: No definition found for class:'ru.my.project.base.AppRouter' & qualifier:'SCREEN_A_ROUTER'. Check your definitions!
        at org.koin.core.scope.Scope.throwDefinitionNotFound(Scope.kt:282)
        at org.koin.core.scope.Scope.resolveInstance(Scope.kt:251)
        at org.koin.core.scope.Scope.get(Scope.kt:204)
        at ru.my.project.base.BaseFragment$$special$$inlined$inject$1.invoke(ComponentCallbackExt.kt:69)
```

**Koin project used and used version (please complete the following information):**
```
def koin_version = "2.2.2"
implementation "org.koin:koin-android:$koin_version"
implementation "org.koin:koin-androidx-scope:$koin_version"
implementation "org.koin:koin-androidx-viewmodel:$koin_version"
```

It seems to me that my problem is caused by that changes - https://github.com/InsertKoinIO/koin/commit/0a71742243c1fee49a64fa2e05f3035b9ec17ab3, where `KClass<*>` was replaced by `KClass<T>`. For example:

**Was:**
```
fun <T> get(
    clazz: KClass<*>,
    qualifier: Qualifier? = null,
    parameters: ParametersDefinition? = null
): T
```

**Now:**
```
fun <T : Any> get(
    clazz: KClass<T>,
    qualifier: Qualifier? = null,
    parameters: ParametersDefinition? = null
): T
```

And now I don't have a clue is it a bug or feature, but now it don't let to migrate to new version safely.

Thanks in advance for the help.

**Comment by fobo66** [comment]
Similar issue for me: `Caused by: org.koin.core.error.NoBeanDefFoundException: No definition found for class:'androidx.lifecycle.SavedStateHandle'. Check your definitions!`

**Comment by nikiJava** [comment]
@arnaudgiuliani Excuse me, would you explain something about my problem, please?

**Comment by arnaudgiuliani** [comment]
Really weird. Ok, let me see if I can revert this part. I will ping you all to have some feedback.

**Comment by nikiJava** [comment]
> Really weird. Ok, let me see if I can revert this part. I will ping you all to have some feedback.

Oh, it's a good news!)
I will wait for your answer.

**Comment by arnaudgiuliani** [comment]
Isn't it weir in terms of nameing here: 

```
val screenAModule = module {
    val routerQualifier = named("${SCREEN_A_QUALIFIER}_ROUTER")
    single(routerQualifier) {
        ScreenARouter()
    }
}
```

what is resolving `${SCREEN_A_QUALIFIER}`?

**Comment by nikiJava** [comment]
> Isn't it weir in terms of nameing here:
> 
> ```
> val screenAModule = module {
>     val routerQualifier = named("${SCREEN_A_QUALIFIER}_ROUTER")
>     single(routerQualifier) {
>         ScreenARouter()
>     }
> }
> ```
> 
> what is resolving `${SCREEN_A_QUALIFIER}`?

it is some string constant for class:
`const val SCREEN_A_QUALIFIER = "SCREEN_A"
`
Which is passed to BaseFragment's constructor and is used as postfix for all dependencies of the fragment including router.

It makes it possible to inject different routers into BaseFragment.

**Comment by nikiJava** [comment]
@arnaudgiuliani Excuse me, can I help you with this task to release new library version sooner? Can I create a Pull Request may be?

**Comment by arnaudgiuliani** [comment]
For 2.3.0 it will be there around May. As I have to backport all fixes from 3.0 to 2.x and push old 2.x to Maven central.

Really sorry 🙏

**Comment by nikiJava** [comment]
> For 2.3.0 it will be there around May. As I have to backport all fixes from 3.0 to 2.x and push old 2.x to Maven central.
> 
> Really sorry 🙏

Hello :)
Do you have any news about 2.3.0?

**Comment by jgavazzisp** [comment]
@arnaudgiuliani any news on this on? Thanks

**Comment by nikiJava** [comment]
@arnaudgiuliani Excuse me, can we help you with 2.3.0 release?

**Comment by arnaudgiuliani** [comment]
If you need more help, come here: https://github.com/InsertKoinIO/koin/issues/1212

**Comment by jgavazzisp** [comment]
thanks @arnaudgiuliani it worked for me so far, need to ask the QA to do a full regression but the tests haven't picked up anything wrong atm. 

Thanks again.

**Comment by nikiJava** [comment]
Sorry, upgrade to 3.1.3 or even to 3.1.4 is not working for me  :(
