### ISSUE TITLE
Using savedStateHandle while scoping viewModel to navGraph prevents koin from initializing viewModel

### ISSUE THREAD

**Issue by MarvzGM** [InsertKoinIO/koin#989]
I am trying to use the `savedStateHandle` in `viewModel` while scoping to `navGraph`. But when I use both together, the viewModel is not initialized. But if I just use them separately, they work perfectly. Please kindly advice me on what I am doing wrong. This is what I tried to follow [https://medium.com/koin-developers/whats-next-with-koin-2-2-3-0-releases-6c5464ae5e3d](url)
Btw, thank you @arnaudgiuliani, this article really helped me.

### SPECS

- Koin 2.0.0
- Tried Koin 2.2.2 but same problem
- Androidx

### CODE
<pre>
class TestViewModel(savedStateHandle: SavedStateHandle) : ViewModel() {
    val testLiveData: MutableLiveData<String> = savedStateHandle.getLiveData(TEST_KEY)

    companion object {
        private const val TEST_KEY= "TEST_KEY"
    }
}</pre>

<pre>
val testModule = module {
    viewModel { TestViewModel(get()) }
}
</pre>

<pre>
class TestFragment : Fragment() {

    private val sharedViewModel: TestViewModel by sharedViewModel(
        state = emptyState(),
        owner = { ViewModelOwner.from(findNavController().getViewModelStoreOwner(R.id.nav_main)) }
    )

    override fun onCreateView(
        inflater: LayoutInflater,
        container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View = inflater.inflate(R.layout.fragment_test, container, false)

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        sharedViewModel.testLiveData = "asd"
    }
}
</pre>

### ERROR
**Note: Needed to change the names of the fragment, viewModel, etc. Also line numbers will not be aligned to the code I gave**
<pre>
2021-01-07 13:36:11.928 8114-8114/test.dev E/AndroidRuntime: FATAL EXCEPTION: main
    Process: test.dev, PID: 8114
    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:503)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
     Caused by: org.koin.core.error.InstanceCreationException: Could not create instance for [Factory:'TestViewModel']
        at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:62)
        at org.koin.core.instance.FactoryInstanceFactory.get(FactoryInstanceFactory.kt:36)
        at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:103)
        at org.koin.core.scope.Scope.resolveInstance(Scope.kt:236)
        at org.koin.core.scope.Scope.get(Scope.kt:204)
        at org.koin.androidx.viewmodel.factory.DefaultViewModelFactory.create(DefaultViewModelFactory.kt:11)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:187)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:150)
        at org.koin.androidx.viewmodel.ViewModelResolverKt.get(ViewModelResolver.kt:23)
        at org.koin.androidx.viewmodel.ViewModelResolverKt.resolveInstance(ViewModelResolver.kt:12)
        at org.koin.androidx.viewmodel.scope.ScopeExtKt.getViewModel(ScopeExt.kt:86)
        at org.koin.androidx.viewmodel.scope.ScopeExtKt.getViewModel(ScopeExt.kt:72)
        at org.koin.androidx.viewmodel.koin.KoinExtKt.getViewModel(KoinExt.kt:41)
        at org.koin.androidx.viewmodel.ext.android.FragmentExtKt.getViewModel(FragmentExt.kt:71)
        at TestFragment$$special$$inlined$sharedViewModel$1.invoke(SharedViewModelExt.kt:79)
        at TestFragment$$special$$inlined$sharedViewModel$1.invoke(Unknown Source:0)
        at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81)
        at TestFragment.getSharedViewModel(Unknown Source:2)
        at TestFragment.onViewCreated(TestFragment.kt:69)
        at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:2922)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:562)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1324)
        at androidx.fragment.app.FragmentManager.addAddedFragments(FragmentManager.java:2392)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2137)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2061)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1957)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3056)
        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2990)
        at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2937)
        at androidx.fragment.app.FragmentStateManager.activityCreated(FragmentStateManager.java:577)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1329)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1477)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1555)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1608)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3046)
        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2990)
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:251)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:458)
2021-01-07 13:36:11.929 8114-8114/test.dev E/AndroidRuntime:     at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:210)
        at TestActivity.onStart(TestActivity.kt:21)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1391)
        at android.app.Activity.performStart(Activity.java:7157)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:2937)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        	... 3 more
     Caused by: org.koin.core.error.NoBeanDefFoundException: No definition found for class:'androidx.lifecycle.SavedStateHandle'. Check your definitions!
        at org.koin.core.scope.Scope.throwDefinitionNotFound(Scope.kt:282)
        at org.koin.core.scope.Scope.resolveInstance(Scope.kt:251)
        at org.koin.core.scope.Scope.get(Scope.kt:204)
        at TestModule$1$18.invoke(TestModule.kt:252)
        at TestModuleKt$TestModule$1$18.invoke(Unknown Source:4)
        at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:53)
        	... 53 more
</pre>

### Expected Behavior
For SavedStateHandle to work together with viewModel scoped to navGraph and for the viewModel to be initialized

**Comment by biberesser** [comment]
Same issue here.
Latest working compose version for me is compose alpha 09.

**Comment by arnaudgiuliani** [comment]
Why do you use `sahredViewModel` here? else it will try to initialize the Activity instance.

**Comment by MarvzGM** [comment]
> Why do you use `sharedViewModel` here? else it will try to initialize the Activity instance.

I was hoping to use this to avoid relying on arguments in certain scenarios like when i want to share data to other fragments while observing that data or something. 

Also depending on the scenario, to avoid the boilerplate needed, the cost of serializing and deserializing, and loosing observability when using arguments.

**Comment by arnaudgiuliani** [comment]
ok, I see. But it was more, do you need to share it with the activity?

**Comment by MarvzGM** [comment]
> ok, I see. But it was more, do you need to share it with the activity?

Nope, between fragments is fine.

**Comment by arnaudgiuliani** [comment]
is still relevant in 3.1.3, with `koinNavGraphViewModel`? https://insert-koin.io/docs/reference/koin-android/viewmodel/#navigation-graph-viewmodel-updated-in-313

**Comment by arnaudgiuliani** [comment]
closing it for now. Let's see if it still goes up in 3.1.4+
